// Real-data container for the Master data design (src/design/master/MasterDesign.tsx,
// generated by scripts/master-build.mjs from docs/Designs/UnifiedTree Master (offline).html).
//
// The design reads one in-memory `db` and changes it with update(collection, fn).
// Here `db` is built from the API (masterData.ts) and every update is diffed and
// sent to the backend (masterSync.ts). The change shows at once; the page's
// success toast waits until the server accepts it; a refusal puts the data back
// and shows the reason. What the backend can't store stays on screen as
// "Coming soon" — docs/Designs/STATIC-UI-TO-BUILD.md §6.
import '@/design/master/master.css'
import { useCallback, useMemo, useRef, useState, type ComponentType, type Context } from 'react'
import { useLocation, useNavigate, useSearchParams } from 'react-router-dom'
import { useQueries, useQuery, useQueryClient, type UseQueryResult } from '@tanstack/react-query'
import { usePermission, P } from '@unifiedtree/sdk'
import { apiJson } from '@/core/api/client'
import { PageSkeleton } from '@/shared/components/PageSkeleton'
import * as Design from '@/design/master/MasterDesign'
import { TODAY_ISO, pl } from '@/design/master/masterRuntime'
import { useCompanies, type Branch, type Department, type Designation, type Grade, type EmploymentTypeRecord } from '../api/useOrg'
import type { WorkforceEmployee, PageResponse } from '../api/useWorkforce'
import type { ShiftPolicy } from '../api/useShiftPolicies'
import type { LeaveTypeResponse } from '../api/useLeave'
import type { Policy, Page } from '../api/usePolicy'
import type { SalaryComponent, PayrollSettings, PtSlab } from '../api/usePayroll'
import type { HrConfigResponse, NextEmployeeCodePreview } from '../api/useSettings'
import {
  employeeRec, companyRec, branchRec, deptRec, desigRec, gradeRec, agencyRec, classRec, shiftRec, leaveRec, policyRec, componentRec, statutoryRecs,
  TYPE_LABEL, type Contractor, type Rec,
} from './masterData'
import { SYNC, diff, type SyncEnv } from './masterSync'
import { saveAndRecord } from '@/shared/export/fileExport'

// The generated design module is untyped JavaScript; these are the pieces used here.
const { NAV, TopTabs, Toasts, ICONS, deriveDB } = Design as any
const AppCtx = Design.AppCtx as unknown as Context<any>
const PAGES = Design.PAGES as unknown as Record<string, ComponentType>
const Empty = Design.Empty as unknown as ComponentType<{ icon?: string; title: string; body?: string; action?: React.ReactNode }>

/**
 * Where each Master page lives. The rules and payroll configuration pages are
 * settings, so they open inside HRMS settings (the one settings place in HRMS):
 * Master's own tabs and links lead there, and their old addresses redirect.
 */
export const MASTER_ROUTES: Record<string, string> = {
  overview: '/hrms/master', employees: '/hrms/employees', contractors: '/hrms/master/contractors', classes: '/hrms/master/classifications',
  companies: '/hrms/master/companies', branches: '/hrms/master/branches', departments: '/hrms/master/departments', designations: '/hrms/master/designations',
  grades: '/hrms/master/grades', shifts: '/hrms/settings/shift-rules', leaves: '/hrms/settings/leave-rules', policies: '/hrms/settings/policies',
  components: '/hrms/settings/salary-components', statutory: '/hrms/settings/statutory',
}
const PAGE_AT: Record<string, string> = Object.fromEntries(Object.entries(MASTER_ROUTES).map(([k, v]) => [v, k]))
/** The design's tweak defaults (its "Top tabs" layout). */
const TWEAKS = { nav: 'Top tabs', density: 'Comfortable', pageSize: '10' }
/** Links from elsewhere may carry the API's status names. */
const STATUS_PARAM: Record<string, string> = { ACTIVE: 'Active', PROBATION: 'Probation', NOTICE_PERIOD: 'On notice', EXITED: 'Exited', TERMINATED: 'Exited', SUSPENDED: 'Suspended' }
/** What each page reads — it waits for these before drawing. */
const NEEDS: Record<string, string[]> = {
  overview: [], employees: ['employees', 'companies', 'branches', 'depts', 'desigs', 'grades', 'classes', 'shifts', 'leaves', 'agencies'],
  contractors: ['agencies', 'branches'], classes: ['classes', 'employees', 'agencies'], companies: ['companies', 'branches', 'employees'],
  branches: ['branches', 'companies', 'employees'], departments: ['depts', 'employees', 'desigs'], designations: ['desigs', 'depts', 'grades', 'employees'],
  grades: ['grades', 'desigs', 'employees'], shifts: ['shifts', 'employees'], leaves: ['leaves', 'classes'], policies: ['policies', 'employees'],
  components: ['components'], statutory: ['statutory', 'components'],
}

interface ScheduleRow { employeeId: string; shiftName?: string | null }
interface ToastItem { id: number; msg: string; kind?: string }
interface Coll<T> { data: T[]; loading: boolean; error: unknown }

/** The directory's milestone filters: the dashboard's "Upcoming milestones" windows. */
const MILESTONES = [
  { v: 'birthday', l: 'Birthdays', sub: 'Next 14 days' },
  { v: 'anniversary', l: 'Work anniversaries', sub: 'Next 31 days' },
  { v: 'retirement', l: 'Retirements', sub: 'Next 6 months' },
]
/** Ids of the people with that milestone coming up, chosen by the server with the dashboard card's own rules. */
async function loadMilestone(kind: string) {
  const ids: string[] = []
  for (let page = 0; page < 10; page++) {
    const r = await apiJson<PageResponse<WorkforceEmployee>>(`/v1/hrms/employees?milestone=${encodeURIComponent(kind)}&page=${page}&pageSize=200`)
    ids.push(...r.content.map((e) => e.id))
    if (page + 1 >= r.totalPages) break
  }
  return ids
}

/** Every employee in the directory (pages of 200). */
async function loadDirectory() {
  const all: WorkforceEmployee[] = []
  for (let page = 0; page < 25; page++) {
    const r = await apiJson<PageResponse<WorkforceEmployee>>(`/v1/hrms/employees?page=${page}&pageSize=200`)
    all.push(...r.content)
    if (page + 1 >= r.totalPages) break
  }
  return all
}
const hrData = (rs: UseQueryResult<HrConfigResponse>[]) => rs.map((r) => r.data ?? null)
const listOf = <T,>(rs: UseQueryResult<T[]>[]): Coll<T> => ({ data: rs.flatMap((r) => r.data ?? []), loading: rs.some((r) => r.isLoading), error: rs.find((r) => r.isError)?.error ?? null })
const one = <T,>(r: UseQueryResult<T[]>, on: boolean): Coll<T> => ({ data: r.data ?? [], loading: on && r.isLoading, error: r.error ?? null })
const errText = (e: unknown) => (e instanceof Error && e.message) || 'Please try again.'
/** One CSV cell. Text a spreadsheet would run as a formula (= + - @) gets a leading ' — as the server export does. */
const csvCell = (v: unknown) => { let s = v == null ? '' : String(v); if (/^[=+\-@\t\r]/.test(s)) s = `'${s}`; return /[",\n']/.test(s) ? `"${s.replace(/"/g, '""')}"` : s }
const csvText = (lines: string[]) => new Blob(['﻿' + lines.join('\r\n')], { type: 'text/csv;charset=utf-8' })
function downloadCsv(name: string, lines: string[]) {
  const url = URL.createObjectURL(csvText(lines))
  const a = document.createElement('a'); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url)
}

export function MasterContainer() {
  const navigate = useNavigate()
  const location = useLocation()
  const [params, setParams] = useSearchParams()
  const qc = useQueryClient()

  // ── who may see and change what (the codes each endpoint checks) ──
  const canEmpRead = usePermission(P.HRMS_EMPLOYEE_READ), canEmpWrite = usePermission(P.HRMS_EMPLOYEE_WRITE)
  const canImport = usePermission(P.HRMS_EMPLOYEE_IMPORT), canInvite = usePermission(P.HRMS_EMPLOYEE_INVITE)
  const canContrRead = usePermission(P.HRMS_CONTRACTOR_READ), canContrWrite = usePermission(P.HRMS_CONTRACTOR_WRITE)
  const canCoRead = usePermission(P.ORG_COMPANY_READ), canCoWrite = usePermission(P.ORG_COMPANY_WRITE)
  const canDeptRead = usePermission(P.HRMS_DEPARTMENT_READ), canDeptWrite = usePermission(P.HRMS_DEPARTMENT_WRITE)
  const canDesRead = usePermission(P.HRMS_DESIGNATION_READ), canDesWrite = usePermission(P.HRMS_DESIGNATION_WRITE)
  const canBranchWrite = usePermission(P.HRMS_BRANCH_WRITE)
  const canGradeWrite = usePermission(P.HRMS_GRADE_WRITE), canTypeWrite = usePermission(P.HRMS_EMPLOYMENT_TYPE_WRITE)
  const canShiftAdmin = usePermission('attendance.workforce.admin'), canTeam = usePermission(P.ATTENDANCE_TEAM_READ)
  const canLeaveWrite = usePermission(P.LEAVE_TYPE_WRITE)
  // Pay bands are salary data (V143.22); linking a contract worker to an agency is part of their record.
  const canBands = usePermission('hrms.grade.band.read'), canAgencyLink = canContrWrite || canEmpWrite
  const canPolicyRead = usePermission('hrms.policy.read'), canPolicyWrite = usePermission('hrms.policy.write')
  const canCompRead = usePermission(P.PAYROLL_COMPONENTS_READ), canCompWrite = usePermission(P.PAYROLL_COMPONENTS_MANAGE)
  const canSetRead = usePermission(P.PAYROLL_SETTINGS_READ), canSetWrite = usePermission(P.PAYROLL_SETTINGS_UPDATE), canSlabs = usePermission(P.PAYROLL_PT_SLABS_READ)
  // Organisation Setup was a setup page (every employee holds department.read), so it keeps that gate.
  const orgSetup = canDeptWrite || canBranchWrite || canDesWrite
  const visible: Record<string, boolean> = {
    employees: canEmpRead, contractors: canContrRead, classes: canEmpRead,
    companies: orgSetup && canCoRead, branches: orgSetup && canCoRead, departments: orgSetup && canDeptRead, designations: orgSetup && canDesRead, grades: orgSetup,
    shifts: canShiftAdmin || canPolicyWrite, leaves: canLeaveWrite || canPolicyWrite, policies: canPolicyWrite && canPolicyRead,
    components: canCompRead, statutory: canSetRead,
  }
  const writable: Record<string, boolean> = {
    employees: canEmpWrite, agencies: canContrWrite, classes: canTypeWrite, companies: canCoWrite, branches: canCoWrite, depts: canDeptWrite,
    desigs: canDesWrite, grades: canGradeWrite, shifts: canShiftAdmin, leaves: canLeaveWrite, policies: canPolicyWrite, components: canCompWrite, statutory: canSetWrite,
  }

  // ── the page ──
  const nav = useMemo(() => NAV.map((g: any) => ({ ...g, items: g.items.filter((i: any) => visible[i.id]) })).filter((g: any) => g.items.length),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [JSON.stringify(visible)])
  const path = location.pathname.replace(/\/$/, '')
  const firstOf = (groupId: string) => nav.find((g: any) => g.id === groupId)?.items[0]?.id
  const page: string = PAGE_AT[path] || (path === '/hrms/organization' ? firstOf('org') || 'companies' : 'overview')
  const route = useMemo(() => ({
    p: page, q: params.get('q') || '', status: STATUS_PARAM[params.get('status') || ''] || params.get('status') || '',
    // departmentId=none (the dashboard's and reports' "No department") is the directory's "No department" option.
    co: params.get('co') || '', dept: ((d) => (d === 'none' ? '__none' : d))(params.get('departmentId') || params.get('dept') || ''), branch: params.get('branchId') || params.get('branch') || '',
    archived: page === 'branches' && params.get('archived') === '1',
  }), [page, params])
  const want = (k: string) => page === 'overview' || NEEDS[page]?.includes(k)

  // ── data ──
  const companiesQ = useCompanies()
  const companies = useMemo(() => companiesQ.data ?? [], [companiesQ.data])
  const coIds = useMemo(() => companies.map((c) => c.id), [companies])
  const defaultCo = coIds[0] || ''
  const opt = { staleTime: 300_000 }
  // Deactivated branches only on the Branches page's "Include inactive" filter, so they never reach a picker.
  const branchesQ = useQuery({
    queryKey: ['hrms', 'branches', 'all', route.archived ? 'with-archived' : 'active'],
    queryFn: () => apiJson<Branch[]>(route.archived ? '/v1/hrms/branches?includeArchived=true' : '/v1/hrms/branches'), enabled: canCoRead && want('branches'), ...opt,
  })
  const empQ = useQuery({ queryKey: ['hrms', 'employees', 'master-all'], queryFn: loadDirectory, enabled: canEmpRead && (want('employees') || want('depts')), staleTime: 120_000 })
  const schedQ = useQuery({ queryKey: ['master', 'schedule', TODAY_ISO], queryFn: () => apiJson<ScheduleRow[]>(`/v1/team/schedule?from=${TODAY_ISO}&to=${TODAY_ISO}`), enabled: canTeam && (want('employees') || want('shifts')), ...opt })
  const perCo = <T,>(key: string[], url: (cid: string) => string, on: boolean) => ({
    queries: coIds.map((cid) => ({ queryKey: [...key, cid], queryFn: () => apiJson<T[]>(url(cid)), enabled: on, ...opt })),
    combine: listOf as (rs: UseQueryResult<T[]>[]) => Coll<T>,
  })
  const depts = useQueries(perCo<Department>(['hrms', 'departments'], (c) => `/v1/hrms/departments?companyId=${c}`, canDeptRead && (want('depts') || want('employees'))))
  const desigs = useQueries({ queries: coIds.map((cid) => ({ queryKey: ['hrms', 'designations', cid, 'all'], queryFn: () => apiJson<Designation[]>(`/v1/hrms/designations?companyId=${cid}`), enabled: canDesRead && (want('desigs') || want('employees')), ...opt })), combine: listOf as (rs: UseQueryResult<Designation[]>[]) => Coll<Designation> })
  const grades = useQueries(perCo<Grade>(['hrms', 'org', 'grades'], (c) => `/v1/hrms/grades?companyId=${c}`, want('grades') || want('employees')))
  const types = useQueries(perCo<EmploymentTypeRecord>(['hrms', 'org', 'employment-types'], (c) => `/v1/hrms/employment-types?companyId=${c}`, want('classes') || want('leaves')))
  // Ended agencies too: they show as inactive with "Reactivate".
  const contractors = useQueries(perCo<Contractor>(['master', 'contractors'], (c) => `/v1/hrms/contractors?companyId=${c}&includeArchived=true`, canContrRead && want('agencies')))
  const shiftsL = useQueries(perCo<ShiftPolicy>(['hrms', 'shift-policies'], (c) => `/v1/shifts?companyId=${c}`, want('shifts') || want('employees')))
  const leavesL = useQueries(perCo<LeaveTypeResponse>(['hrms', 'leave', 'types'], (c) => `/v1/leave/types?companyId=${c}`, want('leaves') || want('employees')))
  const hrQs = useQueries({ queries: coIds.map((cid) => ({ queryKey: ['hrms', 'settings', 'hr-config', cid], queryFn: () => apiJson<HrConfigResponse>(`/v1/settings/hr-configuration?companyId=${cid}`), enabled: canEmpRead && (want('classes') || want('employees')), retry: false, staleTime: 60_000 })), combine: hrData })
  const nextCodeQ = useQuery({ queryKey: ['hrms', 'settings', 'next-employee-code', defaultCo], queryFn: () => apiJson<NextEmployeeCodePreview>(`/v1/settings/employee-code/preview?companyId=${defaultCo}`), enabled: !!defaultCo && canEmpWrite && page === 'employees', retry: false, staleTime: 0 })
  const polQs = useQueries({
    queries: (['ACTIVE', 'DRAFT', 'ARCHIVED'] as const).map((st) => ({
      queryKey: ['hrms', 'policy', 'master', st], queryFn: () => apiJson<Page<Policy>>(`/v1/policy/policies?status=${st}&page=0&size=200`).then((r) => r.content),
      // Drafts and archived policies need write access on the server.
      enabled: canPolicyRead && (st === 'ACTIVE' || canPolicyWrite) && want('policies'), ...opt,
    })),
    combine: listOf as (rs: UseQueryResult<Policy[]>[]) => Coll<Policy>,
  })
  const compQ = useQuery({ queryKey: ['hrms', 'payroll', 'components'], queryFn: () => apiJson<SalaryComponent[]>('/v1/payroll/components'), enabled: canCompRead && want('components'), staleTime: 30_000 })
  const setQ = useQuery({ queryKey: ['hrms', 'payroll', 'settings'], queryFn: () => apiJson<PayrollSettings>('/v1/payroll/settings'), enabled: canSetRead && (want('statutory') || want('components')), staleTime: 60_000 })
  const ptCode = setQ.data?.ptStateCode || ''
  // Milestone filter (URL filter=birthday|anniversary|retirement). Changing it keeps the page's other filters.
  const milestone = MILESTONES.some((m) => m.v === params.get('filter')) ? params.get('filter') as string : ''
  const setMilestone = useCallback((v: string) => setParams((cur) => { const n = new URLSearchParams(cur); if (v) n.set('filter', v); else n.delete('filter'); return n }, { replace: true }), [setParams])
  const milestoneQ = useQuery({ queryKey: ['hrms', 'employees', 'milestone', milestone], queryFn: () => loadMilestone(milestone), enabled: canEmpRead && !!milestone && page === 'employees', staleTime: 60_000 })
  const milestoneIds = useMemo(() => (milestoneQ.data ? new Set(milestoneQ.data) : null), [milestoneQ.data])
  const slabsQ = useQuery({ queryKey: ['hrms', 'payroll', 'pt-slabs', ptCode], queryFn: () => apiJson<PtSlab[]>(`/v1/payroll/pt-slabs/${ptCode}`), enabled: !!ptCode && canSlabs && want('statutory'), staleTime: Infinity })

  const colls: Record<string, Coll<unknown>> = {
    employees: one(empQ, canEmpRead), companies: { data: companies, loading: companiesQ.isLoading, error: companiesQ.error }, branches: one(branchesQ, canCoRead),
    depts, desigs, grades, classes: types, agencies: contractors, shifts: shiftsL, leaves: leavesL, policies: polQs,
    components: one(compQ, canCompRead), statutory: { data: [], loading: canSetRead && setQ.isLoading, error: setQ.error ?? null },
  }

  const server = useMemo(() => {
    const desigList = desigs.data, typeList = types.data, shiftList = shiftsL.data, branchList = branchesQ.data ?? []
    const gradeOfDesig = new Map(desigList.map((d) => [d.id, d.grade || '']))
    const shiftByName = new Map(shiftList.map((s) => [s.name, s.id]))
    const shiftOf = new Map((schedQ.data ?? []).filter((r) => r.shiftName && shiftByName.has(r.shiftName)).map((r) => [r.employeeId, shiftByName.get(r.shiftName!)!]))
    const agencyOf = new Map(contractors.data.flatMap((a) => (a.workerIds ?? []).map((w): [string, string] => [w, a.id])))
    const employees = (empQ.data ?? []).map((e): Rec => ({ ...employeeRec(e, gradeOfDesig, shiftOf), agency: agencyOf.get(e.id) || '' }))
    const nameOf = new Map(employees.map((e) => [e.id, e.name as string]))
    const hr = new Map(hrQs.map((h, i) => [coIds[i], h]))
    const many = companies.length > 1, coName = new Map(companies.map((c) => [c.id, c.name]))
    const known = new Set(Object.keys(ICONS))
    const gradesSorted = grades.data.slice().sort((a, b) => (a.level || 0) - (b.level || 0))
    const compCodes = new Set((compQ.data ?? []).map((c) => c.code))
    return {
      employees,
      companies: companies.map((c, i) => companyRec(c, i, branchList.find((b) => b.companyId === c.id && b.headquarters && b.active !== false))),
      branches: branchList.map(branchRec),
      depts: depts.data.map((d, i) => deptRec(d, i, d.departmentHeadEmployeeId ? nameOf.get(d.departmentHeadEmployeeId) || null : null, known)),
      desigs: desigList.map(desigRec),
      grades: gradesSorted.map(gradeRec),
      agencies: contractors.data.map(agencyRec),
      classes: typeList.map((t) => classRec(t, hr.get(t.companyId), [t.payrollEligible ? 'Paid through payroll' : 'Not paid through payroll', many ? coName.get(t.companyId) : ''].filter(Boolean).join(' · '))),
      shifts: shiftList.map(shiftRec),
      leaves: leavesL.data.map(leaveRec),
      policies: polQs.data.map(policyRec),
      components: (compQ.data ?? []).map((c) => componentRec(c, setQ.data)),
      statutory: setQ.data ? statutoryRecs(setQ.data, slabsQ.data ?? [], compCodes) : [],
    } as Record<string, Rec[]>
  }, [empQ.data, companies, branchesQ.data, depts.data, desigs.data, grades.data, types.data, contractors.data, shiftsL.data, leavesL.data, polQs.data, compQ.data, setQ.data, slabsQ.data, schedQ.data, hrQs, coIds])

  // ── local edits waiting for the server ──
  const [over, setOver] = useState<Record<string, Rec[]>>({})
  const db = useMemo(() => ({ ...server, ...over }), [server, over])
  const d = useMemo(() => deriveDB(db), [db])
  const dbRef = useRef(db); dbRef.current = db

  const [toasts, setToasts] = useState<ToastItem[]>([])
  const show = useCallback((msg: string, kind?: string) => {
    const id = Date.now() + Math.random()
    setToasts((x) => x.slice(-2).concat([{ id, msg, kind }]))
    setTimeout(() => setToasts((x) => x.filter((y) => y.id !== id)), kind === 'error' ? 6500 : 3600)
  }, [])

  const envRef = useRef<SyncEnv | null>(null)
  envRef.current = {
    today: TODAY_ISO, defaultCo, coOfDept: (id) => db.depts.find((x) => x.id === id)?.co, branches: db.branches, settings: setQ.data ?? null,
    nextGradeLevel: Math.max(0, ...grades.data.map((g) => g.level || 0)) + 1, canInvite, canAssignShift: canShiftAdmin, warn: (m) => show(m, 'info'),
    canBands, gradeIdOf: (code, co) => (code ? db.grades.find((g) => g.id === code && g.co === co)?._key : undefined),
  }
  const writableRef = useRef(writable); writableRef.current = writable
  /** Saves started by the handler that is running now; its success toast waits for them. */
  const tick = useRef<Promise<unknown>[] | null>(null)
  const inflight = useRef<Record<string, number>>({})

  const update = useCallback((k: string, fn: Rec[] | ((l: Rec[]) => Rec[])) => {
    const prev = dbRef.current[k] || []
    const next = typeof fn === 'function' ? fn(prev) : fn
    const sync = SYNC[k]
    const p: Promise<unknown[][]> = !writableRef.current[k] ? Promise.reject(new Error('You don’t have access to change this'))
      : sync ? sync(diff(prev, next), envRef.current!) : Promise.reject(new Error('Saving this isn’t supported yet'))
    if (!tick.current) { tick.current = []; queueMicrotask(() => { tick.current = null }) }
    tick.current.push(p)
    inflight.current[k] = (inflight.current[k] || 0) + 1
    setOver((o) => ({ ...o, [k]: next }))
    const settle = () => { inflight.current[k] -= 1; if (!inflight.current[k]) setOver((o) => { const n = { ...o }; delete n[k]; return n }) }
    p.then(async (keys) => { await Promise.all(keys.map((key) => qc.invalidateQueries({ queryKey: key }))); settle() }, (e) => { settle(); show(errText(e), 'error') })
  }, [qc, show])
  const toast = useCallback((msg: string, kind?: string) => {
    const ps = tick.current
    if (ps && ps.length) Promise.all(ps).then(() => show(msg, kind), () => {})
    else show(msg, kind)
  }, [show])

  const go = useCallback((p: string, extra?: Record<string, string>) => {
    const qs = new URLSearchParams(Object.entries(extra || {}).filter(([, v]) => v) as [string, string][]).toString()
    navigate((MASTER_ROUTES[p] || MASTER_ROUTES.overview) + (qs ? `?${qs}` : ''))
    document.getElementById('workspace-content')?.scrollTo({ top: 0 })
  }, [navigate])

  const hrDefault = hrQs[coIds.indexOf(defaultCo)]
  const act = {
    defaultCo, canAssignShift: canShiftAdmin, nextCode: nextCodeQ.data?.preview || '', noticeDays: hrDefault?.defaultNoticePeriodDays,
    canBands, showAgency: canContrRead, canAgency: canAgencyLink,
    /** The Branches page's status filter lives in the URL (?archived=1). */
    showArchivedBranches: (on: boolean, co: string) => navigate(MASTER_ROUTES.branches + '?' + new URLSearchParams(Object.entries({ co, archived: on ? '1' : '' }).filter(([, v]) => v)).toString()),
    importEmployees: () => (canImport ? navigate('/hrms/employees/import') : show('You don’t have access to import employees', 'error')),
    openRecord: (id: string) => navigate(`/hrms/employees/${id}`),
    milestone: { value: milestone, options: MILESTONES, set: setMilestone, ids: milestoneIds },
    exportEmployees: (rows: Rec[]) => {
      const nameOf = (m: Rec[]) => new Map(m.map((x) => [x.id, x.name as string]))
      const dept = nameOf(db.depts), des = nameOf(db.desigs), br = nameOf(db.branches), emp = nameOf(db.employees)
      // The same columns as the server's directory export (no salary, bank or identity fields).
      const head = ['Employee code', 'First name', 'Last name', 'Work email', 'Phone', 'Department', 'Designation', 'Branch', 'Reporting manager', 'Employment type', 'Status', 'Date of joining', 'Probation end', 'Notice start', 'Last working day']
      const lines = rows.map((e) => [e.code, e.first, e.last, e.email, e.phone, dept.get(e.dept), des.get(e.desig), br.get(e.branch), emp.get(e.mgrId), e.type, e.statusLabel || e.status, e.joined, e.probEnd, e._raw?.noticeStartDate, e.lwd || e.exitOn].map(csvCell).join(','))
      // Recorded in the workspace's export log (Reports Center → Recent downloads).
      saveAndRecord(`employees-${TODAY_ISO}.csv`, csvText([head.join(','), ...lines]), { report: 'employee-directory', fmt: 'CSV', rows: rows.length })
      show(`Exported ${pl(rows.length, 'employee', 'employees')} to CSV`)
    },
    exportAgencies: (rows: Rec[]) => {
      const head = ['Agency', 'Registration no.', 'Service', 'Contact person', 'Phone', 'Email', 'Active workers', 'Deployed at', 'Licence number', 'Licence valid till', 'Status']
      const site = new Map(db.branches.map((b) => [b.id, b.name as string]))
      downloadCsv(`agencies-${TODAY_ISO}.csv`, [head.join(','), ...rows.map((x) => [x.name, x.reg, x.service, x.contact, x.phone, x.email, x.workers, (x.sites || []).map((b: string) => site.get(b) || '').filter(Boolean).join('; '), x.licenceNo, x.licence, x.status].map(csvCell).join(','))])
      show(`Exported ${pl(rows.length, 'agency', 'agencies')} to CSV`)
    },
    /** "Remind N people" on a live policy: everyone who hasn't acknowledged, not anyone reminded in the last 24 hours. */
    remindPolicy: async (p: Rec) => {
      try {
        const r = await apiJson<{ reminded: number; skippedRecentlyReminded: number; notAcknowledged: number }>(`/v1/policy/policies/${p._key}/remind`, { method: 'POST' })
        if (r.reminded > 0) show(`Reminder sent to ${pl(r.reminded, 'person', 'people')}${r.skippedRecentlyReminded ? ` · ${pl(r.skippedRecentlyReminded, 'person was', 'people were')} already reminded in the last 24 hours` : ''}`)
        else show(r.notAcknowledged ? 'Everyone who hasn’t acknowledged was already reminded in the last 24 hours' : 'Everyone has acknowledged it', 'info')
      } catch (e) { show(errText(e), 'error') }
    },
    /** The employment types someone can be given — the ones linked to the employee record's type. */
    typeOptions: (cur?: string) => {
      const list = db.classes.filter((c) => c.status === 'Active' && c.co === defaultCo && TYPE_LABEL[c.code]).map((c) => c.type as string)
      const base = list.length ? list : ['Full-time', 'Part-time', 'Intern']
      return cur && !base.includes(cur) ? base.concat([cur]) : base
    },
  }

  const group = nav.find((g: any) => g.items.some((i: any) => i.id === page)) || null
  const counts: Record<string, string | number> = {
    employees: db.employees.length, contractors: db.agencies.length, classes: db.classes.length, companies: db.companies.length, branches: db.branches.length,
    departments: db.depts.length, designations: db.desigs.length, grades: db.grades.length, shifts: db.shifts.length, leaves: db.leaves.length,
    policies: db.policies.length, components: db.components.length, statutory: `${db.statutory.filter((s) => s.on).length}/${db.statutory.length}`,
  }
  const ctx = { db, d, update, toast, go, route, t: TWEAKS, group, counts, warn: {}, nav, act }

  // ── states the design didn't draw ──
  const needs = page === 'overview' ? Object.keys(colls) : NEEDS[page] || []
  const loading = needs.some((k) => colls[k]?.loading)
  const failed = page === 'overview' ? null : needs.map((k) => colls[k]?.error).find(Boolean)
  const allowed = page === 'overview' ? nav.length > 0 : visible[page]
  const Page = PAGES[page] || PAGES.overview
  const retry = () => { qc.invalidateQueries({ queryKey: ['hrms'] }); qc.invalidateQueries({ queryKey: ['master'] }) }
  const body = !allowed ? <div className="card"><Empty icon="lock" title="You don’t have access to this section" body="Ask an admin if you need it." /></div>
    : failed ? <div className="card"><Empty icon="alert-triangle" title="This page couldn’t load" body={errText(failed)} action={<button className="btn sm" onClick={retry}>Try again</button>} /></div>
      : loading ? <PageSkeleton path={location.pathname} bare />
        : <Page key={`${route.p}|${route.q}|${route.status}|${route.co}|${route.dept}|${route.branch}|${route.archived}`} />
  // Inside HRMS settings (/hrms/settings/…) the shell's settings tabs replace Master's own tabs and crumbs (master.css).
  const inHub = path.startsWith('/hrms/settings/')
  return (
    <div className="utm" data-master-page={page} data-in-hub={inHub || undefined}>
      <AppCtx.Provider value={ctx}>
        {!inHub && <TopTabs />}
        <div className="page" data-screen-label={group ? `${group.l} / ${group.items.find((i: any) => i.id === page)?.l}` : 'Master overview'}>{body}</div>
        <Toasts items={toasts} />
      </AppCtx.Provider>
    </div>
  )
}
