ALTER TABLE departments
    ADD COLUMN IF NOT EXISTS color_hex VARCHAR(20),
    ADD COLUMN IF NOT EXISTS icon_key VARCHAR(50);

ALTER TABLE branches
    ADD COLUMN IF NOT EXISTS color_hex VARCHAR(20),
    ADD COLUMN IF NOT EXISTS icon_key VARCHAR(50);
