apiVersion: v1
kind: Secret
metadata:
  name: unifiedtree-secrets
  namespace: unifiedtree
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://postgres-service:5432/unifiedtree"
  DB_USERNAME: "nexus"
  DB_PASSWORD: "CHANGE_ME"
  REDIS_PASSWORD: "CHANGE_ME"
  JWT_SECRET: "CHANGE_ME_MIN_256_BITS"
  S3_BUCKET: "unifiedtree-files"
