// Regenerates the Master data design (src/design/master/MasterDesign.tsx and
// master.css) from the Claude Design export in docs/Designs/. Run from
// apps/platform:
//
//   node scripts/master-build.mjs
//
// The export is a plain React prototype: a handful of scripts sharing one
// global scope plus three stylesheets. This script keeps the design's own
// components and CSS, drops the prototype-only parts (sample data, its stand-in
// rail and top bar, the tweaks panel), applies the documented PATCHES (real
// dates, real codes, backend limits) and writes one module. The real data and
// the API calls live in the hand-written MasterContainer.tsx.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { gunzipSync } from 'node:zlib'
import { fileURLToPath } from 'node:url'
import ts from 'typescript'
import { PATCHES, EXTRA_CSS } from './master-patches.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const EXPORT = resolve(here, '../../../docs/Designs/UnifiedTree Master (offline).html')
const OUT = resolve(here, '../src/design/master')

// ── unpack ───────────────────────────────────────────────────────────────────
const src = readFileSync(EXPORT, 'utf8')
const grab = (type) => { const open = `<script type="${type}">`; const a = src.indexOf(open); const b = src.indexOf('</script>', a); return src.slice(a + open.length, b) }
const manifest = JSON.parse(grab('__bundler/manifest'))
const template = JSON.parse(grab('__bundler/template'))
const text = (uuid) => { const e = manifest[uuid]; let b = Buffer.from(e.data, 'base64'); if (e.compressed) b = gunzipSync(b); return b.toString('utf8') }
const styles = [...template.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g)].map((m) => m[1])
const scripts = [...template.matchAll(/<script type="text\/babel" src="([0-9a-f-]+)"><\/script>/g)].map((m) => ({ id: m[1].slice(0, 8), code: text(m[1]) }))
const byId = Object.fromEntries(scripts.map((s) => [s.id, s.code]))

// ── css ──────────────────────────────────────────────────────────────────────
// style0 is the font faces (the app loads the same families) and style1 the
// tokens (identical to packages/design-system/src/tokens.css). style2 is the
// component CSS: it is scoped under .utm so it can't leak into the rest of the
// app, and the prototype shell's rules (its rail, top bar and side panel) are
// dropped because the app keeps its own shell.
const SHELL = /^\.(app|rail|rail-grp|logo|ri|top|gsearch|kbd|top-sp|tb|me|me-av|main|panel|content|pn-[a-z]+|pg|pg-h|pg-items|pi|pi-r|wd)(?![a-z-])/
const KEYFRAMES = ['popin', 'fade', 'slidein', 'modalin', 'rise', 'tin']
function scopeSelector(sel) {
  sel = sel.trim()
  if (SHELL.test(sel)) return null
  if (sel === 'html' || sel === 'body') return null
  if (sel === '*') return '.utm,.utm *'
  return '.utm ' + sel
}
function fixBody(body, sel) {
  for (const k of KEYFRAMES) body = body.replace(new RegExp(`animation:${k}\\b`, 'g'), `animation:utm-${k}`)
  // The prototype's body rule becomes the scope root's: same font, size and colour. The shell
  // already paints the canvas, and the app scrolls the page, not the body.
  if (sel === 'body') body = body.replace(/background:[^;]+;?/, '').replace(/;?overflow:hidden/, '')
  return body
}
function scopeCss(css) {
  const out = []
  let i = 0
  while (i < css.length) {
    const open = css.indexOf('{', i)
    if (open < 0) break
    const head = css.slice(i, open).trim()
    let depth = 1, j = open + 1
    while (depth && j < css.length) { if (css[j] === '{') depth++; else if (css[j] === '}') depth--; j++ }
    const body = css.slice(open + 1, j - 1)
    i = j
    if (head.startsWith('@keyframes')) { out.push(`@keyframes utm-${head.slice(10).trim()}{${body}}`); continue }
    if (head.startsWith('@media')) { const inner = scopeCss(body); if (inner.trim()) out.push(`${head}{${inner}}`); continue }
    if (head === 'body') { out.push(`.utm{${fixBody(body, 'body')}}`); continue }
    const sels = head.split(',').map(scopeSelector).filter(Boolean)
    if (sels.length) out.push(`${sels.join(',')}{${fixBody(body, head)}}`)
  }
  return out.join('\n')
}
const css = '/* Generated by scripts/master-build.mjs from docs/Designs/UnifiedTree Master (offline).html — do not edit. */\n' + scopeCss(styles[2]) + '\n' + EXTRA_CSS

// ── js ───────────────────────────────────────────────────────────────────────
// The scripts in load order, minus the tweaks panel (67bf89ea). Top-level
// declarations listed in DROP are prototype-only.
const ORDER = ['3f13d7f8', 'e72e9308', '444d22cf', 'beaaecf6', 'd6399539', 'aa085547', '68265841', '99fffcea', 'fb5a180e']
const DROP = new Set([
  // sample data (444d22cf) — the container builds the same shapes from the API
  'seededRand', 'COMPANIES', 'BRANCHES', 'DEPTS', 'GRADES', 'DESIGS', 'LEADERS', 'FIRST', 'LAST', 'buildEmployees', 'AGENCIES', 'CLASSES', 'SHIFTS', 'LEAVES', 'POLICIES', 'COMPONENTS', 'STATUTORY', 'initDB',
  // the prototype's stand-in chrome and root (the app has its own shell)
  'RAIL_GROUPS', 'Rail', 'Topbar', 'Panel', 'MasterApp',
])
function topLevel(code, file) {
  const sf = ts.createSourceFile(file + '.jsx', code, ts.ScriptTarget.Latest, true, ts.ScriptKind.JSX)
  return sf.statements.map((st) => {
    let names = []
    if (ts.isFunctionDeclaration(st) && st.name) names = [st.name.text]
    else if (ts.isVariableStatement(st)) names = st.declarationList.declarations.map((d) => d.name.getText(sf))
    else if (ts.isExpressionStatement(st)) names = ['<expr:' + st.expression.getText(sf).slice(0, 20) + '>']
    return { names, text: code.slice(st.getFullStart(), st.getEnd()) }
  })
}
// Each entry is [prototype text, replacement] — see scripts/master-patches.mjs.
let body = ''
const kept = []
for (const id of ORDER) {
  let code = byId[id]
  if (!code) throw new Error('script not found in export: ' + id)
  for (const [from, to] of PATCHES[id] || []) {
    if (!code.includes(from)) throw new Error(`${id}: patch target not found: ${from.slice(0, 90)}`)
    code = code.split(from).join(to)
  }
  for (const st of topLevel(code, id)) {
    const n = st.names[0] || ''
    if (n.startsWith('<expr:Object.assign(window') || n.startsWith('<expr:ReactDOM.createRoot')) continue
    if (st.names.some((x) => DROP.has(x))) continue
    kept.push(...st.names)
    body += st.text.replace(/^\n+/, '') + '\n'
  }
}
const EXPORTS = ['AppCtx', 'NAV', 'TopTabs', 'PAGES', 'Toasts', 'Icon', 'ICONS', 'Empty', 'tone', 'deriveDB', 'STATUS_TONE', 'TYPE_TONE']
for (const e of EXPORTS) if (!kept.includes(e)) throw new Error('export missing: ' + e)
const header = `/* eslint-disable */
// @ts-nocheck
// Generated by scripts/master-build.mjs from docs/Designs/UnifiedTree Master (offline).html — do not edit.
// The design's own components, verbatim apart from the PATCHES listed in the script.
import * as React from 'react'
import * as ReactDOM from 'react-dom'
import { portalHost, TODAY, TODAY_ISO, NEXT_MONTH, NONE, orNone, pl } from './masterRuntime'
`
const module = header + body + `export { ${EXPORTS.join(', ')} }\n`
mkdirSync(OUT, { recursive: true })
writeFileSync(resolve(OUT, 'master.css'), css)
writeFileSync(resolve(OUT, 'MasterDesign.tsx'), module)
console.log(`master.css ${css.length} bytes · MasterDesign.tsx ${module.length} bytes · ${kept.length} declarations`)
