/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        /* Semantic surface colors */
        'bg-base':             'var(--bg-base)',
        'bg-surface':          'var(--bg-surface)',
        'bg-surface-raised':   'var(--bg-surface-raised)',
        'bg-subtle':           'var(--bg-subtle)',
        'bg-muted':            'var(--bg-muted)',
        /* Accent */
        'accent-bg':           'var(--accent-bg)',
        'accent-bg-strong':    'var(--accent-bg-strong)',
        'accent-fg':           'var(--accent-fg)',
        'accent-fg-strong':    'var(--accent-fg-strong)',
        'accent-border':       'var(--accent-border)',
        /* Text */
        'text-primary':        'var(--text-primary)',
        'text-secondary':      'var(--text-secondary)',
        'text-tertiary':       'var(--text-tertiary)',
        'text-disabled':       'var(--text-disabled)',
        'text-inverse':        'var(--text-inverse)',
        'text-link':           'var(--text-link)',
        /* Border */
        'border-default':      'var(--border-default)',
        'border-strong':       'var(--border-strong)',
        'border-subtle':       'var(--border-subtle)',
        'border-focus':        'var(--border-focus)',
        /* Interactive */
        'interactive-primary':   'var(--interactive-primary)',
        'interactive-danger':    'var(--interactive-danger)',
        /* Status */
        'status-success':  'var(--status-success-fg)',
        'status-warning':  'var(--status-warning-fg)',
        'status-error':    'var(--status-error-fg)',
        'status-info':     'var(--status-info-fg)',
      },
      backgroundColor: {
        'surface':          'var(--bg-surface)',
        'surface-raised':   'var(--bg-surface-raised)',
        'subtle':           'var(--bg-subtle)',
        'accent':           'var(--accent-bg)',
        'accent-strong':    'var(--accent-bg-strong)',
        'success':          'var(--status-success-bg)',
        'warning':          'var(--status-warning-bg)',
        'error':            'var(--status-error-bg)',
        'info':             'var(--status-info-bg)',
      },
      textColor: {
        'primary':          'var(--text-primary)',
        'secondary':        'var(--text-secondary)',
        'tertiary':         'var(--text-tertiary)',
        'disabled':         'var(--text-disabled)',
        'inverse':          'var(--text-inverse)',
        'on-accent':        'var(--text-on-accent)',
        'link':             'var(--text-link)',
        'success':          'var(--status-success-fg)',
        'warning':          'var(--status-warning-fg)',
        'error':            'var(--status-error-fg)',
        'info':             'var(--status-info-fg)',
      },
      borderColor: {
        'default':          'var(--border-default)',
        'strong':           'var(--border-strong)',
        'subtle':           'var(--border-subtle)',
        'focus':            'var(--border-focus)',
        'accent':           'var(--border-accent)',
        'success':          'var(--status-success-border)',
        'warning':          'var(--status-warning-border)',
        'error':            'var(--status-error-border)',
        'info':             'var(--status-info-border)',
      },
      borderRadius: {
        'xs':   'var(--radius-xs)',
        'sm':   'var(--radius-sm)',
        'md':   'var(--radius-md)',
        'lg':   'var(--radius-lg)',
        'xl':   'var(--radius-xl)',
        '2xl':  'var(--radius-2xl)',
        'full': 'var(--radius-full)',
      },
      boxShadow: {
        'xs':   'var(--shadow-xs)',
        'sm':   'var(--shadow-sm)',
        'md':   'var(--shadow-md)',
        'lg':   'var(--shadow-lg)',
        'xl':   'var(--shadow-xl)',
        'glow': 'var(--shadow-glow)',
      },
      zIndex: {
        'dropdown':       '100',
        'sticky':         '200',
        'fixed':          '300',
        'modal-backdrop': '400',
        'modal':          '500',
        'toast':          '600',
        'tooltip':        '700',
      },
      transitionDuration: {
        fast: '100',
        base: '200',
        slow: '300',
      },
    },
  },
};
