package com.hrms.notification.enums;

public enum NotificationType {
    ATTENDANCE_CHECKED_IN, LEAVE_REQUESTED, LEAVE_APPROVED, LEAVE_REJECTED, LEAVE_CANCELLED,
    PAYSLIP_PUBLISHED, EXPENSE_SUBMITTED, EXPENSE_APPROVED, EXPENSE_REJECTED,
    PERFORMANCE_REVIEW_DUE, GOAL_UPDATED, INTERVIEW_SCHEDULED, OFFER_EXTENDED,
    COURSE_ENROLLED, CERTIFICATE_ISSUED, GENERAL
}
