// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component AreaChart.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { Fragment } from 'react'
import { arr, txt } from './dc-runtime'

export function AreaChartView({ v }: { v: any }) {
  return (
    <>
      <div style={{display: "grid", gap: "12px", minWidth: "0"}}>
        <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: "8px 16px"}}>
          <div style={{display: "flex", flexWrap: "wrap", gap: "6px 14px", fontSize: "12px", color: "#475569"}}>
            {arr(v.legend).map((s: any, $index: number) => (
              <Fragment key={$index}>
                <span style={{display: "inline-flex", alignItems: "center", gap: "6px"}}>
                  <svg width="10" height="10" aria-hidden="true">
                    <rect width="10" height="10" rx="3" fill={s?.color} />
                  </svg>
                  {txt(s?.label)}
                </span>
              </Fragment>
            ))}
          </div>
          <div aria-live="polite" style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "4px 12px", fontSize: "12px", color: "#475569", fontVariantNumeric: "tabular-nums", background: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: "8px", padding: "4px 10px"}}>
            <strong style={{color: "#0f172a", fontWeight: "700"}}>
              {txt(v.readout?.title)}
            </strong>
            {arr(v.readout?.items).map((it: any, $index: number) => (
              <Fragment key={$index}>
                <span style={{display: "inline-flex", alignItems: "center", gap: "5px"}}>
                  <svg width="8" height="8" aria-hidden="true">
                    <circle cx="4" cy="4" r="4" fill={it?.color} />
                  </svg>
                  <strong style={{color: "#0f172a", fontWeight: "700"}}>
                    {txt(it?.value)}
                  </strong>
                  {txt(it?.label)}
                </span>
              </Fragment>
            ))}
          </div>
        </div>
        <div style={{display: "grid", gridTemplateColumns: "auto minmax(0,1fr)", gap: "8px 10px"}}>
          <div style={{display: "flex", flexDirection: "column", justifyContent: "space-between", height: "200px", fontSize: "11px", color: "#94a3b8", textAlign: "right", fontVariantNumeric: "tabular-nums", lineHeight: "1", margin: "-5px 0"}}>
            {arr(v.yTicks).map((t: any, $index: number) => (
              <Fragment key={$index}>
                <span>
                  {txt(t)}
                </span>
              </Fragment>
            ))}
          </div>
          <div onMouseLeave={v.onLeave} style={{position: "relative", height: "200px"}}>
            <svg viewBox="0 0 100 50" preserveAspectRatio="none" aria-hidden="true" style={{position: "absolute", inset: "0", width: "100%", height: "100%", overflow: "visible"}}>
              <line x1="0" y1="0" x2="100" y2="0" stroke="#f1f5f9" vectorEffect="non-scaling-stroke" />
              <line x1="0" y1="12.5" x2="100" y2="12.5" stroke="#f1f5f9" vectorEffect="non-scaling-stroke" />
              <line x1="0" y1="25" x2="100" y2="25" stroke="#f1f5f9" vectorEffect="non-scaling-stroke" />
              <line x1="0" y1="37.5" x2="100" y2="37.5" stroke="#f1f5f9" vectorEffect="non-scaling-stroke" />
              <line x1="0" y1="50" x2="100" y2="50" stroke="#e2e8f0" vectorEffect="non-scaling-stroke" />
            </svg>
            <div style={{position: "absolute", inset: "0", display: "flex"}}>
              {arr(v.cols).map((c: any, $index: number) => (
                <Fragment key={$index}>
                  {c?.active ? (
                    <>
                      <div onMouseEnter={c?.onEnter} onClick={c?.onClick} data-tip={c?.tip} style={{flex: "1", cursor: "pointer", background: "rgba(15,110,86,.07)", borderRadius: "8px"}} />
                    </>
                  ) : null}
                  {c?.idle ? (
                    <>
                      <div onMouseEnter={c?.onEnter} onClick={c?.onClick} data-tip={c?.tip} style={{flex: "1", cursor: "pointer", borderRadius: "8px"}} />
                    </>
                  ) : null}
                </Fragment>
              ))}
            </div>
            {arr(v.ser).map((s: any, $index: number) => (
              <Fragment key={$index}>
                <svg viewBox="0 0 100 50" preserveAspectRatio="none" aria-hidden="true" style={{position: "absolute", inset: "0", width: "100%", height: "100%", overflow: "visible", pointerEvents: "none"}}>
                  <path d={s?.areaD} fill={s?.color} fillOpacity={s?.areaOpacity} />
                  <path d={s?.lineD} fill="none" stroke={s?.color} strokeWidth="2.25" strokeDasharray={s?.dash} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" />
                  <line x1={s?.hx} y1={s?.hy} x2={s?.hx} y2={s?.hy} stroke={s?.color} strokeWidth="10" strokeLinecap="round" vectorEffect="non-scaling-stroke" />
                  <line x1={s?.hx} y1={s?.hy} x2={s?.hx} y2={s?.hy} stroke="#ffffff" strokeWidth="4" strokeLinecap="round" vectorEffect="non-scaling-stroke" />
                </svg>
              </Fragment>
            ))}
          </div>
          <span />
          <div style={{display: "flex", fontSize: "11px", color: "#64748b", fontVariantNumeric: "tabular-nums"}}>
            {arr(v.cols).map((c: any, $index: number) => (
              <Fragment key={$index}>
                <span style={{flex: "1", minWidth: "0", textAlign: "center", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>
                  {txt(c?.label)}
                </span>
              </Fragment>
            ))}
          </div>
        </div>
      </div>
    </>
  )
}
