// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component AttOverview.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { Fragment } from 'react'
import { HrAvatar } from '@/shared/components/hr'
import { DataTable } from '@/shared/components/DataTable'
import { EmptyState } from '@/shared/components/EmptyState'
import { SkeletonBlock } from '@/shared/components/SkeletonCard'
import { arr, txt } from './dc-runtime'
import { SectionState } from './SectionState'
import { StatTile } from './StatTile'
import './AttOverview.view.css'

export function AttOverviewView({ v }: { v: any }) {
  return (
    <>
      <div style={{display: "grid", gap: "28px", minWidth: "0", fontFamily: "Inter,-apple-system,sans-serif", color: "#0f172a"}}>
        {v.isError ? (
          <>
            <div style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "18px", padding: "8px"}}>
              <SectionState kind="error" retry={v.retry} />
            </div>
          </>
        ) : null}
        {v.isEmpty ? (
          <>
            <div style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "18px"}}>
              <EmptyState icon={v.emptyIcon} title="No attendance yet this month" description="These charts fill in as soon as people start checking in." />
            </div>
          </>
        ) : null}
        {v.isLoading ? (
          <>
            <div style={{display: "grid", gap: "16px"}}>
              <div style={{display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(200px,1fr))", gap: "12px"}}>
                {arr(v.tiles).map((t: any, $index: number) => (
                  <Fragment key={$index}>
                    <StatTile tile={t} />
                  </Fragment>
                ))}
              </div>
              <div style={{display: "flex", flexWrap: "wrap", gap: "16px"}}>
                <div style={{flex: "1.25 1 380px", minWidth: "0"}}>
                  <SkeletonBlock {...(v.skBig || {})} />
                </div>
                <div style={{flex: "1 1 300px", minWidth: "0"}}>
                  <SkeletonBlock {...(v.skBig || {})} />
                </div>
              </div>
            </div>
          </>
        ) : null}
        {v.isLive ? (
          <>
            <section aria-labelledby="ov-today" style={{display: "grid", gap: "14px"}}>
              <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px 12px"}}>
                <h2 id="ov-today" style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "18px", fontWeight: "800", letterSpacing: "-.01em"}}>
                  {"Today"}
                </h2>
                <span style={{padding: "3px 10px", borderRadius: "999px", background: "#fff", border: "1px solid #e2e8f0", fontSize: "12px", fontWeight: "600", color: "#475569"}}>
                  {txt(v.todayLabel)}
                </span>
              </div>
              <div role="group" aria-label="Today’s numbers" style={{display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(200px,1fr))", gap: "12px"}}>
                {arr(v.tiles).map((t: any, $index: number) => (
                  <Fragment key={$index}>
                    <StatTile tile={t} />
                  </Fragment>
                ))}
              </div>
              <div style={{display: "flex", flexWrap: "wrap", gap: "16px", alignItems: "stretch"}}>
                <article style={{flex: "1.25 1 400px", minWidth: "0", display: "grid", gap: "16px", alignContent: "start", padding: "20px 22px", background: "#fff", border: "1px solid #e2e8f0", borderRadius: "18px", boxShadow: "0 1px 2px rgba(15,23,42,.04)"}}>
                  <div>
                    <h3 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "16px", fontWeight: "800"}}>
                      {"Who’s where today"}
                    </h3>
                    <p style={{margin: "4px 0 0", fontSize: "13px", color: "#64748b", textWrap: "pretty"}}>
                      {"All "}{txt(v.total)}{" people, grouped by what they’re doing. Tap a row to see who."}
                    </p>
                  </div>
                  <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "18px 28px"}}>
                    <div style={{position: "relative", flex: "0 0 172px", width: "172px", height: "172px", margin: "0 auto"}}>
                      <svg viewBox="0 0 172 172" width="172" height="172" role="img" aria-label={v.mixAria} style={{display: "block"}}>
                        <circle cx="86" cy="86" r="64" fill="none" stroke="#f1f5f9" strokeWidth="24" />
                        {arr(v.mix).map((m: any, $index: number) => (
                          <Fragment key={$index}>
                            <circle cx="86" cy="86" r="64" fill="none" stroke={m?.color} strokeWidth="24" strokeDasharray={m?.dash} strokeDashoffset={m?.off} transform="rotate(-90 86 86)">
                              <title>
                                {txt(m?.title)}
                              </title>
                            </circle>
                          </Fragment>
                        ))}
                      </svg>
                      <span style={{position: "absolute", inset: "0", display: "grid", placeContent: "center", justifyItems: "center", textAlign: "center", pointerEvents: "none"}}>
                        <strong style={{fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "30px", fontWeight: "800", lineHeight: "1", fontVariantNumeric: "tabular-nums"}}>
                          {txt(v.total)}
                        </strong>
                        <span style={{marginTop: "5px", fontSize: "11px", fontWeight: "700", letterSpacing: ".08em", textTransform: "uppercase", color: "#64748b"}}>
                          {"people"}
                        </span>
                      </span>
                    </div>
                    <ul style={{flex: "1 1 230px", minWidth: "0", margin: "0", padding: "0", listStyle: "none", display: "grid", gap: "2px"}}>
                      {arr(v.mix).map((m: any, $index: number) => (
                        <Fragment key={$index}>
                          <li>
                            {m?.canOpen ? (
                              <>
                                <button type="button" onClick={m?.onClick} data-tip={m?.tip} style={{width: "100%", display: "flex", alignItems: "center", gap: "10px", padding: "7px 10px", border: "0", borderRadius: "10px", background: "none", font: "inherit", fontSize: "13.5px", color: "#334155", cursor: "pointer", textAlign: "left"}} className="dc-att-overview-0">
                                  <svg width="10" height="10" aria-hidden="true">
                                    <circle cx="5" cy="5" r="5" fill={m?.color} />
                                  </svg>
                                  <span style={{flex: "1", minWidth: "0"}}>
                                    {txt(m?.label)}
                                  </span>
                                  <strong style={{fontVariantNumeric: "tabular-nums", color: "#0f172a"}}>
                                    {txt(m?.n)}
                                  </strong>
                                  <span style={{width: "38px", textAlign: "right", fontSize: "12px", color: "#64748b", fontVariantNumeric: "tabular-nums"}}>
                                    {txt(m?.pct)}
                                  </span>
                                </button>
                              </>
                            ) : null}
                            {m?.noOpen ? (
                              <>
                                <div style={{display: "flex", alignItems: "center", gap: "10px", padding: "7px 10px", fontSize: "13.5px", color: "#334155"}}>
                                  <svg width="10" height="10" aria-hidden="true">
                                    <circle cx="5" cy="5" r="5" fill={m?.color} />
                                  </svg>
                                  <span style={{flex: "1", minWidth: "0"}}>
                                    {txt(m?.label)}
                                  </span>
                                  <strong style={{fontVariantNumeric: "tabular-nums", color: "#0f172a"}}>
                                    {txt(m?.n)}
                                  </strong>
                                  <span style={{width: "38px", textAlign: "right", fontSize: "12px", color: "#64748b", fontVariantNumeric: "tabular-nums"}}>
                                    {txt(m?.pct)}
                                  </span>
                                </div>
                              </>
                            ) : null}
                          </li>
                        </Fragment>
                      ))}
                    </ul>
                  </div>
                </article>
                <article style={{flex: "1 1 320px", minWidth: "0", display: "grid", gap: "16px", alignContent: "start", padding: "20px 22px", background: "#fff", border: "1px solid #e2e8f0", borderRadius: "18px", boxShadow: "0 1px 2px rgba(15,23,42,.04)"}}>
                  <div>
                    <h3 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "16px", fontWeight: "800"}}>
                      {"How people checked in"}
                    </h3>
                    <p style={{margin: "4px 0 0", fontSize: "13px", color: "#64748b"}}>
                      {txt(v.srcTotal)}{" check-ins today, by the way they punched"}
                    </p>
                  </div>
                  <ul style={{margin: "0", padding: "0", listStyle: "none", display: "grid", gap: "14px"}}>
                    {arr(v.sources).map((s: any, $index: number) => (
                      <Fragment key={$index}>
                        <li style={{display: "grid", gridTemplateColumns: "auto minmax(0,1fr) auto", alignItems: "center", gap: "6px 12px"}}>
                          <span style={{gridRow: "span 2", width: "34px", height: "34px", borderRadius: "10px", background: "#f0fdfa", border: "1px solid #ccfbf1", color: "#0f766e", display: "inline-flex", alignItems: "center", justifyContent: "center"}}>
                            {txt(s?.icon)}
                          </span>
                          <span style={{fontSize: "13.5px", fontWeight: "600", color: "#334155"}}>
                            {txt(s?.label)}
                          </span>
                          <span style={{fontSize: "13px", fontVariantNumeric: "tabular-nums", whiteSpace: "nowrap"}}>
                            <strong>
                              {txt(s?.n)}
                            </strong>
                            <span style={{color: "#64748b"}}>
                              {" · "}{txt(s?.pct)}
                            </span>
                          </span>
                          <svg width="100%" height="8" aria-hidden="true" style={{gridColumn: "2 / 4", display: "block"}}>
                            <rect width="100%" height="8" rx="4" fill="#f1f5f9" />
                            <rect width={s?.w} height="8" rx="4" fill="#14b8a6" />
                          </svg>
                        </li>
                      </Fragment>
                    ))}
                  </ul>
                </article>
              </div>
            </section>
            <section aria-labelledby="ov-month" style={{display: "grid", gap: "14px"}}>
              <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px 12px"}}>
                <h2 id="ov-month" style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "18px", fontWeight: "800", letterSpacing: "-.01em"}}>
                  {"This month"}
                </h2>
                <span style={{padding: "3px 10px", borderRadius: "999px", background: "#fff", border: "1px solid #e2e8f0", fontSize: "12px", fontWeight: "600", color: "#475569"}}>
                  {txt(v.monthChip)}
                </span>
              </div>
              <div style={{display: "flex", flexWrap: "wrap", gap: "16px", alignItems: "stretch"}}>
                <article style={{flex: "1.7 1 460px", minWidth: "0", display: "grid", gap: "14px", alignContent: "start", padding: "20px 22px", background: "#fff", border: "1px solid #e2e8f0", borderRadius: "18px", boxShadow: "0 1px 2px rgba(15,23,42,.04)"}}>
                  <div style={{display: "flex", flexWrap: "wrap", alignItems: "flex-start", justifyContent: "space-between", gap: "10px 16px"}}>
                    <div>
                      <h3 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "16px", fontWeight: "800"}}>
                        {"Attendance trend"}
                      </h3>
                      <p style={{margin: "4px 0 0", fontSize: "13px", color: "#64748b"}}>
                        {"Each bar is one day. Tap a bar to open that day’s logs."}
                      </p>
                    </div>
                    <ul style={{display: "flex", flexWrap: "wrap", gap: "6px 14px", margin: "0", padding: "0", listStyle: "none", fontSize: "12px", color: "#475569"}}>
                      {arr(v.legend).map((l: any, $index: number) => (
                        <Fragment key={$index}>
                          <li style={{display: "inline-flex", alignItems: "center", gap: "6px"}}>
                            <svg width="10" height="10" aria-hidden="true">
                              <rect width="10" height="10" rx="3" fill={l?.color} />
                            </svg>
                            {txt(l?.label)}
                          </li>
                        </Fragment>
                      ))}
                    </ul>
                  </div>
                  <svg viewBox={v.tr?.vb} role="img" aria-label={v.tr?.aria} style={{display: "block", width: "100%", height: "auto", fontFamily: "Inter,sans-serif"}}>
                    {arr(v.tr?.grid).map((g: any, $index: number) => (
                      <Fragment key={$index}>
                        <line x1={g?.x1} x2={g?.x2} y1={g?.y} y2={g?.y} stroke="#e5ebe9" strokeDasharray={g?.dash} />
                        <text x={g?.tx} y={g?.ty} textAnchor="end" fontSize="10.5" fill="#94a3b8">
                          {txt(g?.label)}
                        </text>
                      </Fragment>
                    ))}
                    {arr(v.tr?.days).map((d: any, $index: number) => (
                      <Fragment key={$index}>
                        <g onClick={d?.onClick} data-tip={d?.tip} style={{cursor: "pointer"}}>
                          <title>
                            {txt(d?.tip)}
                          </title>
                          <rect x={d?.hx} y={d?.hy} width={d?.hw} height={d?.hh} rx="6" fill={d?.hl} />
                          <rect x={d?.x} y={d?.y1} width={d?.w} height={d?.h1} rx="2.5" fill={d?.c1} />
                          <rect x={d?.x} y={d?.y2} width={d?.w} height={d?.h2} rx="2.5" fill="#f59e0b" />
                          <rect x={d?.x} y={d?.y3} width={d?.w} height={d?.h3} rx="2.5" fill="#f43f5e" />
                          <text x={d?.cx} y={d?.ly} textAnchor="middle" fontSize="10.5" fontWeight={d?.lw} fill={d?.lc}>
                            {txt(d?.label)}
                          </text>
                        </g>
                      </Fragment>
                    ))}
                  </svg>
                </article>
                <article style={{flex: "1 1 300px", minWidth: "0", display: "grid", gap: "14px", alignContent: "start", padding: "20px 22px", background: "#fff", border: "1px solid #e2e8f0", borderRadius: "18px", boxShadow: "0 1px 2px rgba(15,23,42,.04)"}}>
                  <div>
                    <h3 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "16px", fontWeight: "800"}}>
                      {"Late most often"}
                    </h3>
                    <p style={{margin: "4px 0 0", fontSize: "13px", color: "#64748b"}}>
                      {"Times each person came in after the grace time"}
                    </p>
                  </div>
                  <div style={{display: "grid", gap: "8px"}}>
                    {arr(v.late).map((l: any, $index: number) => (
                      <Fragment key={$index}>
                        <button type="button" onClick={l?.onClick} data-tip={l?.tip} style={{display: "grid", gridTemplateColumns: "minmax(0,1fr) auto", alignItems: "center", gap: "8px 12px", padding: "10px 12px", border: "1px solid #f1f5f9", borderRadius: "12px", background: "#fff", textAlign: "left", font: "inherit", cursor: "pointer"}} className="dc-att-overview-1">
                          <HrAvatar name={l?.name} sub={l?.dept} />
                          <span style={{fontSize: "13px", fontWeight: "800", color: "#c2410c", whiteSpace: "nowrap"}}>
                            {txt(l?.times)}
                          </span>
                          <svg width="100%" height="8" aria-hidden="true" style={{gridColumn: "1 / -1", display: "block"}}>
                            <rect width="100%" height="8" rx="4" fill="#fff1e6" />
                            <rect width={l?.w} height="8" rx="4" fill="#f59e0b" />
                          </svg>
                        </button>
                      </Fragment>
                    ))}
                  </div>
                </article>
              </div>
              <article style={{minWidth: "0", background: "#fff", border: "1px solid #e2e8f0", borderRadius: "18px", boxShadow: "0 1px 2px rgba(15,23,42,.04)", overflow: "hidden"}}>
                <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: "10px 16px", padding: "18px 22px 14px"}}>
                  <div>
                    <h3 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "16px", fontWeight: "800"}}>
                      {"Everyone’s month"}
                    </h3>
                    <p style={{margin: "4px 0 0", fontSize: "13px", color: "#64748b"}}>
                      {"Days present, late marks, hours and overtime for September"}
                    </p>
                  </div>
                  <label style={{position: "relative", flex: "0 1 280px", minWidth: "200px"}}>
                    <span style={{position: "absolute", left: "12px", top: "50%", transform: "translateY(-50%)", display: "inline-flex", color: "#94a3b8"}}>
                      {txt(v.icSearch)}
                    </span>
                    <input type="search" value={v.q} onChange={v.setQ} placeholder="Find a person or team" aria-label="Find a person or team" style={{width: "100%", boxSizing: "border-box", height: "38px", padding: "0 12px 0 36px", border: "1px solid #e2e8f0", borderRadius: "10px", background: "#fff", font: "inherit", fontSize: "13.5px", outline: "none"}} className="dc-att-overview-2" />
                  </label>
                </div>
                {v.isDesktop ? (
                  <>
                    <div data-row-tips={v.rowTips}>
                      <DataTable columns={v.columns} data={v.rows} keyField="id" emptyMessage="No one matches that search." onRowClick={v.openRow} />
                    </div>
                  </>
                ) : null}
                {v.isMobile ? (
                  <>
                    <div style={{display: "grid", gap: "8px", padding: "0 14px 14px"}}>
                      {arr(v.rows).map((r: any, $index: number) => (
                        <Fragment key={$index}>
                          <button type="button" onClick={r?.onOpen} data-tip={r?.tip} style={{display: "grid", gap: "10px", padding: "12px 14px", border: "1px solid #e2e8f0", borderRadius: "14px", background: "#fff", textAlign: "left", font: "inherit", cursor: "pointer"}}>
                            <span style={{display: "flex", justifyContent: "space-between", alignItems: "center", gap: "8px"}}>
                              <HrAvatar name={r?.name} sub={r?.dept} />
                              <strong style={{fontSize: "13px", fontVariantNumeric: "tabular-nums", whiteSpace: "nowrap"}}>
                                {txt(r?.days)}{" days"}
                              </strong>
                            </span>
                            <span style={{display: "flex", flexWrap: "wrap", gap: "4px 14px", fontSize: "12px", color: "#475569"}}>
                              <span>
                                {"Late: "}{txt(r?.lateTxt)}
                              </span>
                              <span>
                                {txt(r?.avg)}{" a day"}
                              </span>
                              <span>
                                {"Overtime: "}{txt(r?.otTxt)}
                              </span>
                            </span>
                          </button>
                        </Fragment>
                      ))}
                    </div>
                  </>
                ) : null}
                <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: "8px", padding: "12px 22px", borderTop: "1px solid #f1f5f9", background: "#fbfdfc", fontSize: "12.5px", color: "#64748b"}}>
                  <span>
                    {txt(v.footLine)}
                  </span>
                  <button type="button" onClick={v.goReport} data-tip="→ /hrms/reports?type=attendance&month=2026-09" style={{display: "inline-flex", alignItems: "center", gap: "4px", padding: "0", border: "0", background: "none", font: "inherit", fontWeight: "700", color: "#0f6e56", cursor: "pointer"}}>
                    {"Open the full report "}{txt(v.icChevron)}
                  </button>
                </div>
              </article>
            </section>
          </>
        ) : null}
      </div>
    </>
  )
}
