// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component AttRegularization.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { Fragment } from 'react'
import { HrAvatar, HrButton, HrDrawer, HrStatusPill } from '@/shared/components/hr'
import { EmptyState } from '@/shared/components/EmptyState'
import { SkeletonBlock } from '@/shared/components/SkeletonCard'
import { arr, txt } from './dc-runtime'
import { ApprovalCard } from './ApprovalCard'
import { DatePicker } from './DatePicker'
import { SubTabs } from './SubTabs'
import { TimePicker } from './TimePicker'
import './AttRegularization.view.css'

export function AttRegularizationView({ v }: { v: any }) {
  return (
    <>
      <div style={{display: "grid", gap: "16px", minWidth: "0", fontFamily: "Inter,-apple-system,sans-serif", color: "#0f172a"}}>
        {v.canApprove ? (
          <>
            <SubTabs items={v.views} label="Regularization views" />
          </>
        ) : null}
        {v.viewTeam ? (
          <>
            <section aria-labelledby="reg-wait" style={{display: "grid", gap: "10px"}}>
              <h3 id="reg-wait" style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "16px", fontWeight: "800"}}>
                {"Waiting for your OK"}
              </h3>
              {v.isLoading ? (
                <>
                  <div style={{display: "grid", gap: "10px"}}>
                    <SkeletonBlock {...(v.sk || {})} />
                    <SkeletonBlock {...(v.sk || {})} />
                  </div>
                </>
              ) : null}
              {v.isError ? (
                <>
                  <div style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px"}}>
                    <EmptyState icon={v.errIcon} title="Unable to load requests" description="Fix requests didn’t load." action={v.retry} />
                  </div>
                </>
              ) : null}
              {v.caughtUp ? (
                <>
                  <div style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px"}}>
                    <EmptyState icon={v.okIcon} title="All caught up" description="No attendance fixes are waiting for you." />
                  </div>
                </>
              ) : null}
              {v.hasList ? (
                <>
                  <div style={{display: "grid", gap: "10px"}}>
                    {arr(v.list).map((r: any, $index: number) => (
                      <Fragment key={$index}>
                        <ApprovalCard request={r} onDecide={v.decide} onAttachment={v.attach} approveLabel="Approve fix" approveTip="Approves and updates attendance" />
                      </Fragment>
                    ))}
                  </div>
                </>
              ) : null}
            </section>
            {v.hasDecided ? (
              <>
                <section aria-labelledby="reg-done" style={{display: "grid", gap: "10px"}}>
                  <h3 id="reg-done" style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "16px", fontWeight: "800"}}>
                    {"Already decided"}
                  </h3>
                  <div style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px", overflow: "hidden"}}>
                    {arr(v.decided).map((r: any, $index: number) => (
                      <Fragment key={$index}>
                        <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px 16px", padding: "12px 16px", borderBottom: "1px solid #f1f5f9"}}>
                          <HrAvatar name={r?.name} sub={r?.sub} />
                          <span style={{flex: "1 1 220px", minWidth: "0", display: "grid", gap: "2px", fontSize: "13px"}}>
                            <strong style={{fontVariantNumeric: "tabular-nums"}}>
                              {txt(r?.date)}{" · "}{txt(r?.in)}{" – "}{txt(r?.out)}
                            </strong>
                            <span style={{color: "#64748b"}}>
                              {txt(r?.noteText)}
                            </span>
                          </span>
                          <HrStatusPill tone={r?.tone}>
                            {txt(r?.label)}
                          </HrStatusPill>
                        </div>
                      </Fragment>
                    ))}
                  </div>
                </section>
              </>
            ) : null}
          </>
        ) : null}
        {v.viewMine ? (
          <>
            <section style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "18px", boxShadow: "0 1px 2px rgba(15,23,42,.04)", padding: "18px 20px", display: "grid", gap: "12px"}}>
              <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: "10px"}}>
                <div>
                  <h3 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "16px", fontWeight: "800"}}>
                    {"Your fix requests"}
                  </h3>
                  <p style={{margin: "3px 0 0", fontSize: "13px", color: "#64748b"}}>
                    {"Times you asked HR to correct your own attendance."}
                  </p>
                </div>
                <HrButton onClick={v.openNew} data-tip="Opens New fix request">
                  {txt(v.icPlus)}{" New request"}
                </HrButton>
              </div>
              {v.mineEmpty ? (
                <>
                  <p style={{margin: "0", padding: "18px", textAlign: "center", border: "1px dashed #cbd5e1", borderRadius: "12px", fontSize: "13px", color: "#64748b"}}>
                    {"No requests yet. If you forget to punch, ask for a fix here."}
                  </p>
                </>
              ) : null}
              <div style={{display: "grid", gap: "8px"}}>
                {arr(v.mine).map((m: any, $index: number) => (
                  <Fragment key={$index}>
                    <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: "8px 16px", padding: "12px 14px", border: "1px solid #f1f5f9", borderRadius: "12px", background: "#f8fafc", fontSize: "13px"}}>
                      <span style={{display: "grid", gap: "2px"}}>
                        <strong style={{fontVariantNumeric: "tabular-nums"}}>
                          {txt(m?.date)}{" · "}{txt(m?.in)}{" – "}{txt(m?.out)}
                        </strong>
                        <span style={{color: "#64748b"}}>
                          {txt(m?.reason)}
                        </span>
                      </span>
                      <HrStatusPill tone={m?.tone}>
                        {txt(m?.label)}
                      </HrStatusPill>
                    </div>
                  </Fragment>
                ))}
              </div>
            </section>
          </>
        ) : null}
      </div>
      {v.newOpen ? (
        <>
          <HrDrawer title="Ask for a fix" onClose={v.closeNew} footer={v.newFooter} width="max-w-md">
            <div style={{display: "grid", gap: "14px", fontFamily: "Inter,-apple-system,sans-serif", color: "#0f172a"}}>
              <div style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
                <span>
                  {"Which day? *"}
                </span>
                <DatePicker value={v.f?.date} max={v.todayMax} onChange={v.setDate} label="Which day" />
              </div>
              <div style={{display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: "12px"}}>
                <div style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
                  <span>
                    {"You came in at *"}
                  </span>
                  <TimePicker value={v.f?.in} onChange={v.setIn} label="Came in at" />
                </div>
                <div style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
                  <span>
                    {"You left at *"}
                  </span>
                  <TimePicker value={v.f?.out} onChange={v.setOut} label="Left at" />
                </div>
              </div>
              {v.timeError ? (
                <>
                  <span style={{fontSize: "12px", color: "#be123c"}}>
                    {"The time you left must be after the time you came in."}
                  </span>
                </>
              ) : null}
              <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
                {"Proof (optional)"}
                <input type="file" disabled={v.proofOff} title={v.proofTip} onChange={v.onProof} accept=".pdf,.jpg,.png" style={{font: "inherit", fontSize: "13px", fontWeight: "400"}} />
                <span style={{fontSize: "12px", fontWeight: "400", color: "#64748b"}}>
                  {txt(v.proofHelp)}
                </span>
              </label>
              <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
                {"What happened? *"}
                <textarea value={v.f?.reason} onChange={v.setReason} rows={3} maxLength={300} placeholder="e.g. Forgot to punch out" style={{font: "inherit", fontWeight: "400", padding: "9px 12px", border: "1px solid #cbd5e1", borderRadius: "8px", outline: "none", resize: "vertical"}} className="dc-att-regularization-0">

                </textarea>
              </label>
            </div>
          </HrDrawer>
        </>
      ) : null}
    </>
  )
}
