// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component BranchDrawer.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { Fragment } from 'react'
import { HrDrawer } from '@/shared/components/hr'
import { arr, txt } from './dc-runtime'
import { GeofenceMap } from './GeofenceMap'
import './BranchDrawer.view.css'

export function BranchDrawerView({ v }: { v: any }) {
  return (
    <>
      <HrDrawer title={v.title} onClose={v.close} footer={v.footer} width="max-w-2xl">
        <div style={{display: "grid", gap: "18px", fontFamily: "Inter,-apple-system,sans-serif", color: "#0f172a"}}>
          <p style={{margin: "-8px 0 0", fontSize: "13px", color: "#475569"}}>
            {txt(v.subtitle)}
          </p>
          {v.readOnly ? (
            <>
              <div role="note" style={{display: "flex", gap: "10px", alignItems: "center", padding: "10px 12px", border: "1px solid #e2e8f0", background: "#f8fafc", borderRadius: "10px", fontSize: "13px", color: "#334155"}}>
                <span style={{display: "inline-flex", color: "#64748b"}}>
                  {txt(v.icLock)}
                </span>
                {"You can view but not change geofences."}
              </div>
            </>
          ) : null}
          <div style={{display: "flex", flexWrap: "wrap", gap: "18px", alignItems: "flex-start"}}>
            <ol aria-label="Steps" style={{flex: "0 0 150px", listStyle: "none", margin: "0", padding: "0", display: "grid", gap: "2px", position: "sticky", top: "0"}}>
              {arr(v.steps).map((s: any, $index: number) => (
                <Fragment key={$index}>
                  <li>
                    <button type="button" onClick={s?.onClick} style={{display: "flex", alignItems: "center", gap: "10px", width: "100%", padding: "7px 8px", border: "0", borderRadius: "8px", background: "transparent", cursor: "pointer", fontFamily: "inherit", fontSize: "12.5px", textAlign: "left", color: "#334155"}} className="dc-branch-drawer-0">
                      {s?.done ? (
                        <>
                          <span style={{width: "22px", height: "22px", flexShrink: "0", borderRadius: "999px", background: "#0f6e56", color: "#fff", display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: "11px", fontWeight: "800"}}>
                            {"✓"}
                          </span>
                        </>
                      ) : null}
                      {s?.current ? (
                        <>
                          <span style={{width: "22px", height: "22px", flexShrink: "0", borderRadius: "999px", background: "#ecfdf5", color: "#0f6e56", boxShadow: "inset 0 0 0 1.5px #0f6e56", display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: "11px", fontWeight: "800"}}>
                            {txt(s?.n)}
                          </span>
                        </>
                      ) : null}
                      {s?.todo ? (
                        <>
                          <span style={{width: "22px", height: "22px", flexShrink: "0", borderRadius: "999px", background: "#fff", color: "#64748b", boxShadow: "inset 0 0 0 1.5px #cbd5e1", display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: "11px", fontWeight: "700"}}>
                            {txt(s?.n)}
                          </span>
                        </>
                      ) : null}
                      <span style={{fontWeight: "600"}}>
                        {txt(s?.label)}
                      </span>
                    </button>
                  </li>
                </Fragment>
              ))}
            </ol>
            <div style={{flex: "1 1 330px", minWidth: "0", display: "grid", gap: "18px"}}>
              <section ref={v.secDetails} style={{display: "grid", gap: "12px", padding: "16px", border: "1px solid #e2e8f0", borderRadius: "14px", background: "#fff"}}>
                <div style={{display: "flex", gap: "10px", alignItems: "flex-start"}}>
                  <span style={{display: "inline-flex", width: "32px", height: "32px", borderRadius: "9px", background: "#ecfdf5", color: "#0f6e56", alignItems: "center", justifyContent: "center", flexShrink: "0"}}>
                    {txt(v.icBuilding)}
                  </span>
                  <div>
                    <h3 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "14px", fontWeight: "700"}}>
                      {"Branch information"}
                    </h3>
                    <p style={{margin: "2px 0 0", fontSize: "12px", color: "#64748b"}}>
                      {"Basic details about this branch."}
                    </p>
                  </div>
                </div>
                <div style={{display: "grid", gridTemplateColumns: "minmax(0,2fr) minmax(0,1fr)", gap: "12px"}}>
                  <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
                    {"Branch name *"}
                    <input value={v.f?.name} onChange={v.setName} onBlur={v.touchName} disabled={v.readOnly} maxLength={120} placeholder="e.g. Mumbai Office" style={{font: "inherit", fontWeight: "400", padding: "9px 12px", border: "1px solid #cbd5e1", borderRadius: "8px", color: "#0f172a", outline: "none", background: "#fff", width: "100%", boxSizing: "border-box"}} className="dc-branch-drawer-1" />
                    {v.nameError ? (
                      <>
                        <span style={{fontSize: "12px", fontWeight: "500", color: "#be123c"}}>
                          {"Enter a branch name."}
                        </span>
                      </>
                    ) : null}
                  </label>
                  <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600", alignContent: "start"}}>
                    {"Code"}
                    <input value={v.f?.code} onChange={v.setCode} disabled={v.readOnly} maxLength={6} placeholder="MUM" style={{font: "inherit", fontWeight: "400", padding: "9px 12px", border: "1px solid #cbd5e1", borderRadius: "8px", color: "#0f172a", outline: "none", background: "#fff", width: "100%", boxSizing: "border-box", fontFamily: "'JetBrains Mono',ui-monospace,monospace", textTransform: "uppercase"}} className="dc-branch-drawer-1" />
                  </label>
                </div>
              </section>
              <section ref={v.secLocation} style={{display: "grid", gap: "12px", padding: "16px", border: "1px solid #e2e8f0", borderRadius: "14px", background: "#fff"}}>
                <div style={{display: "flex", gap: "10px", alignItems: "flex-start"}}>
                  <span style={{display: "inline-flex", width: "32px", height: "32px", borderRadius: "9px", background: "#ecfdf5", color: "#0f6e56", alignItems: "center", justifyContent: "center", flexShrink: "0"}}>
                    {txt(v.icPin)}
                  </span>
                  <div>
                    <h3 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "14px", fontWeight: "700"}}>
                      {"Location"}
                    </h3>
                    <p style={{margin: "2px 0 0", fontSize: "12px", color: "#64748b"}}>
                      {"The physical address of this office."}
                    </p>
                  </div>
                </div>
                <div style={{display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: "12px"}}>
                  <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
                    {"City *"}
                    <input value={v.f?.city} onChange={v.setCity} disabled={v.readOnly} placeholder="Mumbai" style={{font: "inherit", fontWeight: "400", padding: "9px 12px", border: "1px solid #cbd5e1", borderRadius: "8px", color: "#0f172a", outline: "none", background: "#fff", width: "100%", boxSizing: "border-box"}} className="dc-branch-drawer-1" />
                  </label>
                  <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
                    {"State *"}
                    <select value={v.f?.state} onChange={v.setState} disabled={v.readOnly} style={{font: "inherit", fontWeight: "400", padding: "9px 12px", border: "1px solid #cbd5e1", borderRadius: "8px", color: "#0f172a", outline: "none", background: "#fff", width: "100%", boxSizing: "border-box"}}>
                      <option value="">
                        {"Select state"}
                      </option>
                      {arr(v.states).map((o: any, $index: number) => (
                        <Fragment key={$index}>
                          <option value={o}>
                            {txt(o)}
                          </option>
                        </Fragment>
                      ))}
                    </select>
                  </label>
                </div>
                <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
                  {"Country *"}
                  <select value="India" disabled={v.readOnly} style={{font: "inherit", fontWeight: "400", padding: "9px 12px", border: "1px solid #cbd5e1", borderRadius: "8px", color: "#0f172a", outline: "none", background: "#fff", width: "100%", boxSizing: "border-box"}}>
                    <option>
                      {"India"}
                    </option>
                  </select>
                </label>
                <label style={{display: "flex", gap: "10px", alignItems: "flex-start", padding: "10px 12px", border: "1px solid #f1f5f9", borderRadius: "10px", background: "#f8fafc", fontSize: "13px", fontWeight: "600", cursor: "pointer"}}>
                  <input type="checkbox" checked={v.f?.hq} onChange={v.setHq} disabled={v.readOnly} style={{width: "16px", height: "16px", marginTop: "2px", accentColor: "#0f6e56"}} />
                  <span style={{display: "grid", gap: "2px"}}>
                    {"Mark as headquarters"}
                    <span style={{fontSize: "12px", fontWeight: "400", color: "#64748b"}}>
                      {txt(v.hqHint)}
                    </span>
                  </span>
                </label>
              </section>
            </div>
          </div>
          <section ref={v.secGeo} style={{display: "grid", gap: "12px", padding: "16px", border: "1px solid #a7f3d0", borderRadius: "14px", background: "#f0fdf4"}}>
            <div style={{display: "flex", gap: "10px", alignItems: "flex-start", justifyContent: "space-between"}}>
              <div style={{display: "flex", gap: "10px", alignItems: "flex-start"}}>
                <span style={{display: "inline-flex", width: "32px", height: "32px", borderRadius: "9px", background: "#dcfce7", color: "#047857", alignItems: "center", justifyContent: "center", flexShrink: "0"}}>
                  {txt(v.icShield)}
                </span>
                <div>
                  <h3 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "14px", fontWeight: "700"}}>
                    {"Attendance geofence"}
                  </h3>
                  <p style={{margin: "2px 0 0", fontSize: "12px", color: "#475569"}}>
                    {"Mobile check-ins only count inside this area."}
                  </p>
                </div>
              </div>
              {v.geoOn ? (
                <>
                  <button type="button" role="switch" aria-checked="true" aria-label="Enforce geofence" onClick={v.toggleGeo} disabled={v.readOnly} style={{position: "relative", width: "44px", height: "26px", flexShrink: "0", borderRadius: "999px", border: "0", background: "#10b981", cursor: "pointer"}}>
                    <span style={{position: "absolute", top: "3px", left: "21px", width: "20px", height: "20px", borderRadius: "999px", background: "#fff", boxShadow: "0 1px 3px rgba(0,0,0,.25)"}} />
                  </button>
                </>
              ) : null}
              {v.geoOff ? (
                <>
                  <button type="button" role="switch" aria-checked="false" aria-label="Enforce geofence" onClick={v.toggleGeo} disabled={v.readOnly} style={{position: "relative", width: "44px", height: "26px", flexShrink: "0", borderRadius: "999px", border: "0", background: "#cbd5e1", cursor: "pointer"}}>
                    <span style={{position: "absolute", top: "3px", left: "3px", width: "20px", height: "20px", borderRadius: "999px", background: "#fff", boxShadow: "0 1px 3px rgba(0,0,0,.25)"}} />
                  </button>
                </>
              ) : null}
            </div>
            {v.geoOn ? (
              <>
                <GeofenceMap lat={v.f?.lat} lng={v.f?.lng} radius={v.f?.radius} readOnly={v.readOnly} onPick={v.pick} />
                <div style={{display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: "10px"}}>
                  <label style={{display: "grid", gap: "6px", fontSize: "12px", fontWeight: "600"}}>
                    {"Latitude"}
                    <input value={v.f?.lat} onChange={v.setLat} disabled={v.readOnly} inputMode="decimal" style={{font: "inherit", fontSize: "13px", fontWeight: "400", padding: "8px 10px", border: "1px solid #cbd5e1", borderRadius: "8px", color: "#0f172a", outline: "none", background: "#fff", width: "100%", boxSizing: "border-box", fontVariantNumeric: "tabular-nums"}} className="dc-branch-drawer-1" />
                  </label>
                  <label style={{display: "grid", gap: "6px", fontSize: "12px", fontWeight: "600"}}>
                    {"Longitude"}
                    <input value={v.f?.lng} onChange={v.setLng} disabled={v.readOnly} inputMode="decimal" style={{font: "inherit", fontSize: "13px", fontWeight: "400", padding: "8px 10px", border: "1px solid #cbd5e1", borderRadius: "8px", color: "#0f172a", outline: "none", background: "#fff", width: "100%", boxSizing: "border-box", fontVariantNumeric: "tabular-nums"}} className="dc-branch-drawer-1" />
                  </label>
                  <label style={{display: "grid", gap: "6px", fontSize: "12px", fontWeight: "600"}}>
                    {"Radius (metres)"}
                    <input type="number" min="25" max="5000" value={v.f?.radius} onChange={v.setRadius} disabled={v.readOnly} style={{font: "inherit", fontSize: "13px", fontWeight: "400", padding: "8px 10px", border: "1px solid #cbd5e1", borderRadius: "8px", color: "#0f172a", outline: "none", background: "#fff", width: "100%", boxSizing: "border-box", fontVariantNumeric: "tabular-nums"}} className="dc-branch-drawer-1" />
                  </label>
                </div>
                <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: "8px"}}>
                  {v.radiusError ? (
                    <>
                      <span style={{fontSize: "12px", color: "#be123c"}}>
                        {"Radius must be between 25 and 5,000 metres."}
                      </span>
                    </>
                  ) : null}
                  {v.canCentre ? (
                    <>
                      <button type="button" onClick={v.centre} style={{display: "inline-flex", alignItems: "center", gap: "6px", background: "none", border: "0", padding: "0", color: "#0f6e56", font: "inherit", fontSize: "12px", fontWeight: "600", cursor: "pointer"}}>
                        {txt(v.icCross)}{" Centre on "}{txt(v.f?.city)}
                      </button>
                    </>
                  ) : null}
                </div>
              </>
            ) : null}
            {v.geoOff ? (
              <>
                <p style={{margin: "0", fontSize: "13px", color: "#475569", lineHeight: "1.5"}}>
                  {"Employees at this branch can check in from anywhere. Turn the geofence on to restrict mobile check-ins to the office area."}
                </p>
              </>
            ) : null}
          </section>
          <section ref={v.secReview} style={{display: "grid", gap: "10px", padding: "16px", border: "1px dashed #cbd5e1", borderRadius: "14px"}}>
            <h3 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "14px", fontWeight: "700"}}>
              {"Review"}
            </h3>
            <dl style={{margin: "0", display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(150px,1fr))", gap: "10px 16px", fontSize: "13px"}}>
              {arr(v.review).map((r: any, $index: number) => (
                <Fragment key={$index}>
                  <div>
                    <dt style={{fontSize: "11px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#64748b"}}>
                      {txt(r?.k)}
                    </dt>
                    <dd style={{margin: "2px 0 0", fontWeight: "600", fontVariantNumeric: "tabular-nums"}}>
                      {txt(r?.v)}
                    </dd>
                  </div>
                </Fragment>
              ))}
            </dl>
          </section>
        </div>
      </HrDrawer>
    </>
  )
}
