// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component CompanyDrawer.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { HrButton, HrDrawer } from '@/shared/components/hr'
import { txt } from './dc-runtime'
import './CompanyDrawer.view.css'

export function CompanyDrawerView({ v }: { v: any }) {
  return (
    <>
      <HrDrawer title={v.title} onClose={v.close} footer={v.footer} width="max-w-lg">
        <div style={{display: "grid", gap: "14px", fontFamily: "Inter,-apple-system,sans-serif", color: "#0f172a"}}>
          <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
            {"Company name *"}
            <input value={v.f?.name} onChange={v.setName} onBlur={v.touch} maxLength={120} placeholder="e.g. Acme Technologies" style={{font: "inherit", fontWeight: "400", padding: "9px 12px", border: "1px solid #cbd5e1", borderRadius: "8px", color: "#0f172a", outline: "none", background: "#fff", width: "100%", boxSizing: "border-box"}} className="dc-company-drawer-0" />
            {v.nameError ? (
              <>
                <span style={{fontSize: "12px", fontWeight: "500", color: "#be123c"}}>
                  {"Enter the company name."}
                </span>
              </>
            ) : null}
          </label>
          <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
            {"Legal name"}
            <input value={v.f?.legal} onChange={v.setLegal} placeholder="Registered legal name" style={{font: "inherit", fontWeight: "400", padding: "9px 12px", border: "1px solid #cbd5e1", borderRadius: "8px", color: "#0f172a", outline: "none", background: "#fff", width: "100%", boxSizing: "border-box"}} className="dc-company-drawer-0" />
          </label>
          <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
            {"Industry"}
            <input value={v.f?.industry} onChange={v.setIndustry} placeholder="e.g. Technology" style={{font: "inherit", fontWeight: "400", padding: "9px 12px", border: "1px solid #cbd5e1", borderRadius: "8px", color: "#0f172a", outline: "none", background: "#fff", width: "100%", boxSizing: "border-box"}} className="dc-company-drawer-0" />
          </label>
          <div style={{display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: "12px"}}>
            <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
              {"Currency"}
              <select value="INR" style={{font: "inherit", fontWeight: "400", padding: "9px 12px", border: "1px solid #cbd5e1", borderRadius: "8px", color: "#0f172a", outline: "none", background: "#fff", width: "100%", boxSizing: "border-box"}}>
                <option value="INR">
                  {"INR · Indian rupee"}
                </option>
              </select>
            </label>
            <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
              {"Country"}
              <select value="India" style={{font: "inherit", fontWeight: "400", padding: "9px 12px", border: "1px solid #cbd5e1", borderRadius: "8px", color: "#0f172a", outline: "none", background: "#fff", width: "100%", boxSizing: "border-box"}}>
                <option>
                  {"India"}
                </option>
              </select>
            </label>
          </div>
          <section style={{display: "grid", gap: "12px", padding: "14px", border: "1px solid #e2e8f0", borderRadius: "12px", background: "#f8fafc"}}>
            <h3 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "14px", fontWeight: "700"}}>
              {"Statutory details"}
            </h3>
            <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
              {"Registration number (CIN)"}
              <input value={v.f?.cin} onChange={v.setCin} maxLength={21} placeholder="U72200MH2019PTC123456" style={{font: "inherit", fontWeight: "400", padding: "9px 12px", border: "1px solid #cbd5e1", borderRadius: "8px", color: "#0f172a", outline: "none", background: "#fff", width: "100%", boxSizing: "border-box", fontFamily: "'JetBrains Mono',ui-monospace,monospace", fontSize: "13px"}} className="dc-company-drawer-0" />
            </label>
            <div style={{display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: "12px"}}>
              <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
                {"Company PAN"}
                <input value={v.f?.pan} onChange={v.setPan} maxLength={10} placeholder="ABCDE1234F" style={{font: "inherit", fontWeight: "400", padding: "9px 12px", border: "1px solid #cbd5e1", borderRadius: "8px", color: "#0f172a", outline: "none", background: "#fff", width: "100%", boxSizing: "border-box", fontFamily: "'JetBrains Mono',ui-monospace,monospace", fontSize: "13px"}} className="dc-company-drawer-0" />
              </label>
              <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
                {"GSTIN"}
                <input value={v.f?.gstin} onChange={v.setGstin} maxLength={15} placeholder="22ABCDE1234F1Z5" style={{font: "inherit", fontWeight: "400", padding: "9px 12px", border: "1px solid #cbd5e1", borderRadius: "8px", color: "#0f172a", outline: "none", background: "#fff", width: "100%", boxSizing: "border-box", fontFamily: "'JetBrains Mono',ui-monospace,monospace", fontSize: "13px"}} className="dc-company-drawer-0" />
              </label>
            </div>
            <p style={{margin: "0", fontSize: "12px", color: "#64748b"}}>
              {"Used on PF, ESI and TDS filings. Leave blank if not yet registered."}
            </p>
          </section>
          {v.isEdit ? (
            <>
              <section style={{display: "grid", gap: "12px", padding: "14px", border: "1px solid #a7f3d0", borderRadius: "12px", background: "#f0fdf4"}}>
                <div style={{display: "flex", alignItems: "center", justifyContent: "space-between", gap: "10px"}}>
                  <h3 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "14px", fontWeight: "700"}}>
                    {"Employee ID auto-generation"}
                  </h3>
                  <HrButton variant="ghost" size="sm" onClick={v.saveFormat} disabled={v.formatInvalid}>
                    {"Save format"}
                  </HrButton>
                </div>
                <div style={{display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: "12px"}}>
                  <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
                    {"Prefix"}
                    <input value={v.f?.prefix} onChange={v.setPrefix} maxLength={10} style={{font: "inherit", fontWeight: "400", padding: "9px 12px", border: "1px solid #cbd5e1", borderRadius: "8px", color: "#0f172a", outline: "none", background: "#fff", width: "100%", boxSizing: "border-box", fontFamily: "'JetBrains Mono',ui-monospace,monospace", fontSize: "13px"}} className="dc-company-drawer-0" />
                  </label>
                  <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
                    {"Starting number"}
                    <input value={v.f?.next} onChange={v.setNext} maxLength={8} inputMode="numeric" style={{font: "inherit", fontWeight: "400", padding: "9px 12px", border: "1px solid #cbd5e1", borderRadius: "8px", color: "#0f172a", outline: "none", background: "#fff", width: "100%", boxSizing: "border-box", fontFamily: "'JetBrains Mono',ui-monospace,monospace", fontSize: "13px"}} className="dc-company-drawer-0" />
                  </label>
                </div>
                {v.prefixError ? (
                  <>
                    <span style={{fontSize: "12px", color: "#be123c"}}>
                      {"Prefix must be 1-10 letters or digits (no spaces or dashes)."}
                    </span>
                  </>
                ) : null}
                {v.nextError ? (
                  <>
                    <span style={{fontSize: "12px", color: "#be123c"}}>
                      {"Starting number must be 1-8 digits."}
                    </span>
                  </>
                ) : null}
                <p style={{margin: "0", display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px", fontSize: "13px", color: "#065f46"}}>
                  {"Next employee will be: "}
                  <code style={{fontFamily: "'JetBrains Mono',ui-monospace,monospace", fontSize: "13px", fontWeight: "700", color: "#0a5240", background: "#fff", border: "1px solid #a7f3d0", borderRadius: "6px", padding: "2px 8px"}}>
                    {txt(v.preview)}
                  </code>
                </p>
                <p style={{margin: "0", fontSize: "12px", color: "#475569"}}>
                  {"Changes only affect employees created after saving."}
                </p>
              </section>
            </>
          ) : null}
        </div>
      </HrDrawer>
    </>
  )
}
