// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component CompaniesPage.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { Fragment } from 'react'
import { HrButton, HrSelect, HrStatusPill, TableCard } from '@/shared/components/hr'
import { DataTable } from '@/shared/components/DataTable'
import { EmptyState } from '@/shared/components/EmptyState'
import { SkeletonBlock } from '@/shared/components/SkeletonCard'
import { Modal } from '@unifiedtree/ui-kit'
import { arr, txt } from './dc-runtime'
import { BranchDrawer } from './BranchDrawer'
import { CompanyDrawer } from './CompanyDrawer'
import './CompaniesPage.view.css'

export function CompaniesPageView({ v }: { v: any }) {
  return (
    <>
      <div style={{display: "grid", gap: "20px", minWidth: "0", fontFamily: "Inter,-apple-system,sans-serif", color: "#0f172a"}}>
        {v.hasCompanies ? (
          <>
            <div style={{display: "flex", flexWrap: "wrap", alignItems: "flex-start", gap: "20px", minWidth: "0"}}>
              <aside aria-label="Companies" style={{flex: "1 1 400px", minWidth: "0", display: "grid", gap: "12px", alignContent: "start"}}>
                <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: "10px 16px", minHeight: "40px", marginBottom: "4px"}}>
                  <h1 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "20px", fontWeight: "700", letterSpacing: "-.01em", color: "#0f172a"}}>
                    {"Companies & Branches"}
                  </h1>
                  {v.canEdit ? (
                    <>
                      <HrButton size="sm" onClick={v.addCompany} data-tip="Opens Add company">
                        {txt(v.icPlus)}{" Add company"}
                      </HrButton>
                    </>
                  ) : null}
                </div>
                <div ref={v.pickerRef} style={{position: "relative", zIndex: "5", display: "grid", gap: "6px"}}>
                  <div style={{display: "flex", alignItems: "baseline", justifyContent: "space-between", gap: "8px"}}>
                    <span id="co-pick-label" style={{fontSize: "11px", fontWeight: "700", letterSpacing: ".08em", textTransform: "uppercase", color: "#64748b"}}>
                      {"Company"}
                    </span>
                    <span style={{fontSize: "12px", color: "#64748b", fontVariantNumeric: "tabular-nums"}}>
                      {txt(v.totalsLabel)}
                    </span>
                  </div>
                  {v.pickerClosed ? (
                    <>
                      <button type="button" onClick={v.togglePicker} aria-haspopup="listbox" aria-expanded="false" aria-labelledby="co-pick-label" data-tip="Search and switch company" style={{width: "100%", display: "flex", alignItems: "center", gap: "12px", padding: "9px 12px", border: "1px solid #e2e8f0", borderRadius: "12px", background: "#fff", boxShadow: "0 1px 2px rgba(15,23,42,.04)", font: "inherit", color: "inherit", textAlign: "left", cursor: "pointer"}} className="dc-companies-page-0">
                        <span style={{width: "36px", height: "36px", borderRadius: "10px", background: "#0f6e56", color: "#fff", display: "inline-flex", alignItems: "center", justifyContent: "center", flexShrink: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "13px", fontWeight: "800", letterSpacing: "-.02em"}}>
                          {txt(v.co?.initials)}
                        </span>
                        <span style={{flex: "1", minWidth: "0", display: "grid", gap: "1px"}}>
                          <strong style={{overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontSize: "14px", fontWeight: "700", color: "#0f172a"}}>
                            {txt(v.co?.name)}
                          </strong>
                          <span style={{fontSize: "12px", color: "#64748b"}}>
                            {txt(v.co?.pickMeta)}
                          </span>
                        </span>
                        <span aria-hidden="true" style={{display: "inline-flex", color: "#64748b"}}>
                          {txt(v.icChevronDown)}
                        </span>
                      </button>
                    </>
                  ) : null}
                  {v.pickerOpen ? (
                    <>
                      <button type="button" onClick={v.togglePicker} aria-haspopup="listbox" aria-expanded="true" aria-labelledby="co-pick-label" style={{width: "100%", display: "flex", alignItems: "center", gap: "12px", padding: "9px 12px", border: "1px solid #34d399", borderRadius: "12px", background: "#fff", boxShadow: "0 0 0 3px rgba(16,185,129,.15)", font: "inherit", color: "inherit", textAlign: "left", cursor: "pointer"}}>
                        <span style={{width: "36px", height: "36px", borderRadius: "10px", background: "#0f6e56", color: "#fff", display: "inline-flex", alignItems: "center", justifyContent: "center", flexShrink: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "13px", fontWeight: "800", letterSpacing: "-.02em"}}>
                          {txt(v.co?.initials)}
                        </span>
                        <span style={{flex: "1", minWidth: "0", display: "grid", gap: "1px"}}>
                          <strong style={{overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontSize: "14px", fontWeight: "700", color: "#0f172a"}}>
                            {txt(v.co?.name)}
                          </strong>
                          <span style={{fontSize: "12px", color: "#64748b"}}>
                            {txt(v.co?.pickMeta)}
                          </span>
                        </span>
                        <span aria-hidden="true" style={{display: "inline-flex", color: "#0f6e56", transform: "rotate(180deg)"}}>
                          {txt(v.icChevronDown)}
                        </span>
                      </button>
                      <div role="dialog" aria-label="Choose a company" style={{position: "absolute", left: "0", right: "0", top: "calc(100% + 6px)", background: "#fff", border: "1px solid #e2e8f0", borderRadius: "14px", boxShadow: "0 18px 40px -12px rgba(15,23,42,.3)", padding: "8px", display: "grid", gap: "6px"}}>
                        <label style={{display: "flex", alignItems: "center", gap: "8px", height: "38px", padding: "0 10px", border: "1px solid #e2e8f0", borderRadius: "10px", background: "#f8fafc", color: "#64748b"}}>
                          {txt(v.icSearch)}
                          <input ref={v.searchRef} type="search" value={v.pickerQ} onChange={v.setPickerQ} onKeyDown={v.pickerKey} aria-label="Search companies" placeholder="Search by name or industry…" style={{flex: "1", minWidth: "0", border: "0", outline: "none", background: "transparent", font: "inherit", fontSize: "13px", color: "#0f172a"}} />
                        </label>
                        <div role="listbox" aria-label="Companies" style={{display: "grid", gap: "2px", maxHeight: "288px", overflowY: "auto"}}>
                          {arr(v.pickRows).map((c: any, $index: number) => (
                            <Fragment key={$index}>
                              {c?.sel ? (
                                <>
                                  <button type="button" role="option" aria-selected="true" onClick={c?.onPick} style={{width: "100%", display: "flex", alignItems: "center", gap: "10px", padding: "8px 10px", border: "0", borderRadius: "10px", background: "#ecfdf5", font: "inherit", color: "inherit", textAlign: "left", cursor: "pointer"}}>
                                    <span style={{width: "30px", height: "30px", borderRadius: "9px", background: "#0f6e56", color: "#fff", display: "inline-flex", alignItems: "center", justifyContent: "center", flexShrink: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "11.5px", fontWeight: "800", letterSpacing: "-.02em"}}>
                                      {txt(c?.initials)}
                                    </span>
                                    <span style={{flex: "1", minWidth: "0", display: "grid", gap: "1px"}}>
                                      <strong style={{overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontSize: "13.5px", fontWeight: "700", color: "#0a5240"}}>
                                        {txt(c?.name)}
                                      </strong>
                                      <span style={{fontSize: "12px", color: "#047857"}}>
                                        {txt(c?.meta)}
                                      </span>
                                    </span>
                                    <span aria-hidden="true" style={{display: "inline-flex", color: "#0f6e56"}}>
                                      {txt(v.icCheck)}
                                    </span>
                                  </button>
                                </>
                              ) : null}
                              {c?.unsel ? (
                                <>
                                  <button type="button" role="option" aria-selected="false" onClick={c?.onPick} style={{width: "100%", display: "flex", alignItems: "center", gap: "10px", padding: "8px 10px", border: "0", borderRadius: "10px", background: "transparent", font: "inherit", color: "inherit", textAlign: "left", cursor: "pointer"}} className="dc-companies-page-1">
                                    <span style={{width: "30px", height: "30px", borderRadius: "9px", background: "#ecfdf5", color: "#0f6e56", display: "inline-flex", alignItems: "center", justifyContent: "center", flexShrink: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "11.5px", fontWeight: "800", letterSpacing: "-.02em"}}>
                                      {txt(c?.initials)}
                                    </span>
                                    <span style={{flex: "1", minWidth: "0", display: "grid", gap: "1px"}}>
                                      <strong style={{overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontSize: "13.5px", fontWeight: "700", color: "#0f172a"}}>
                                        {txt(c?.name)}
                                      </strong>
                                      <span style={{fontSize: "12px", color: "#64748b"}}>
                                        {txt(c?.meta)}
                                      </span>
                                    </span>
                                    {c?.inactive ? (
                                      <>
                                        <HrStatusPill tone="gray">
                                          {"Inactive"}
                                        </HrStatusPill>
                                      </>
                                    ) : null}
                                  </button>
                                </>
                              ) : null}
                            </Fragment>
                          ))}
                          {v.pickNoMatch ? (
                            <>
                              <p style={{margin: "0", padding: "14px 10px", fontSize: "13px", color: "#64748b", textAlign: "center"}}>
                                {"No companies match “"}{txt(v.pickerQ)}{"”."}
                              </p>
                            </>
                          ) : null}
                        </div>
                      </div>
                    </>
                  ) : null}
                </div>
                <section style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px", boxShadow: "0 1px 2px rgba(15,23,42,.04)", padding: "18px 20px", display: "grid", gap: "16px"}}>
                  {v.isLoading ? (
                    <>
                      <div role="status" aria-label="Loading company" style={{display: "grid", gap: "12px"}}>
                        <SkeletonBlock {...(v.sk1 || {})} />
                        <SkeletonBlock {...(v.sk2 || {})} />
                        <SkeletonBlock {...(v.sk3 || {})} />
                      </div>
                    </>
                  ) : null}
                  {v.notLoading ? (
                    <>
                      <div style={{display: "flex", alignItems: "flex-start", gap: "12px"}}>
                        <div style={{flex: "1", minWidth: "0", display: "grid", gap: "6px"}}>
                          <h2 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "18px", fontWeight: "700", letterSpacing: "-.01em", lineHeight: "1.25", overflowWrap: "anywhere"}}>
                            {txt(v.co?.name)}
                          </h2>
                          <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "6px 8px", fontSize: "12.5px", color: "#64748b"}}>
                            <HrStatusPill tone={v.co?.tone}>
                              {txt(v.co?.statusLabel)}
                            </HrStatusPill>
                            <span>
                              {txt(v.co?.meta)}
                            </span>
                          </div>
                        </div>
                        {v.canEdit ? (
                          <>
                            <div style={{display: "flex", gap: "6px", flexShrink: "0"}}>
                              <HrButton variant="ghost" size="sm" onClick={v.editCompany} data-tip="Opens Edit company">
                                {txt(v.icPencil)}{" Edit"}
                              </HrButton>
                              <HrButton variant="ghost" size="sm" onClick={v.archiveCompany} data-tip="Archives this company">
                                {txt(v.icArchive)}{" Archive"}
                              </HrButton>
                            </div>
                          </>
                        ) : null}
                      </div>
                      <p style={{margin: "0", fontSize: "13px", color: "#475569", textWrap: "pretty"}}>
                        {txt(v.co?.desc)}
                      </p>
                      <div style={{display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: "8px"}}>
                        <button type="button" onClick={v.goEmployees} data-tip={v.employeesTip} style={{display: "grid", gap: "2px", padding: "10px 12px", border: "1px solid #d1fae5", borderRadius: "12px", background: "#f0fdf4", font: "inherit", color: "inherit", textAlign: "left", cursor: "pointer"}} className="dc-companies-page-2">
                          <span style={{fontSize: "11px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#047857"}}>
                            {"Employees"}
                          </span>
                          <strong style={{fontSize: "18px", fontWeight: "800", fontVariantNumeric: "tabular-nums", color: "#0a5240"}}>
                            {txt(v.co?.employees)}
                          </strong>
                        </button>
                        <div style={{display: "grid", gap: "2px", padding: "10px 12px", border: "1px solid #f1f5f9", borderRadius: "12px", background: "#f8fafc"}}>
                          <span style={{fontSize: "11px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#64748b"}}>
                            {"Branches"}
                          </span>
                          <strong style={{fontSize: "18px", fontWeight: "800", fontVariantNumeric: "tabular-nums"}}>
                            {txt(v.co?.branchCount)}
                          </strong>
                        </div>
                        <div style={{display: "grid", gap: "2px", padding: "10px 12px", border: "1px solid #f1f5f9", borderRadius: "12px", background: "#f8fafc"}}>
                          <span style={{fontSize: "11px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#64748b"}}>
                            {"Geofenced"}
                          </span>
                          <strong style={{fontSize: "18px", fontWeight: "800", fontVariantNumeric: "tabular-nums", whiteSpace: "nowrap"}}>
                            {txt(v.co?.geofenced)}
                          </strong>
                        </div>
                      </div>
                      <dl style={{margin: "0", display: "grid", gridTemplateColumns: "auto minmax(0,1fr)", gap: "8px 16px", fontSize: "13px"}}>
                        <dt style={{color: "#64748b"}}>
                          {"Legal name"}
                        </dt>
                        <dd style={{margin: "0", fontWeight: "600", overflowWrap: "anywhere"}}>
                          {txt(v.co?.legalLabel)}
                        </dd>
                        <dt style={{color: "#64748b"}}>
                          {"Headquarters"}
                        </dt>
                        <dd style={{margin: "0", fontWeight: "600"}}>
                          {txt(v.co?.hqName)}
                        </dd>
                      </dl>
                      <dl style={{margin: "0", display: "grid", gridTemplateColumns: "auto minmax(0,1fr)", gap: "6px 18px", alignContent: "start", padding: "12px 14px", background: "#f8fafc", border: "1px solid #f1f5f9", borderRadius: "12px", fontSize: "13px"}}>
                        <dt style={{gridColumn: "1/-1", fontSize: "11px", fontWeight: "700", letterSpacing: ".08em", textTransform: "uppercase", color: "#64748b"}}>
                          {"Statutory information"}
                        </dt>
                        <dt style={{color: "#64748b"}}>
                          {"CIN"}
                        </dt>
                        <dd style={{margin: "0", fontFamily: "'JetBrains Mono',ui-monospace,monospace", fontSize: "12.5px", overflowWrap: "anywhere"}}>
                          {txt(v.co?.cinLabel)}
                        </dd>
                        <dt style={{color: "#64748b"}}>
                          {"PAN"}
                        </dt>
                        <dd style={{margin: "0", fontFamily: "'JetBrains Mono',ui-monospace,monospace", fontSize: "12.5px"}}>
                          {txt(v.co?.panLabel)}
                        </dd>
                        <dt style={{color: "#64748b"}}>
                          {"GSTIN"}
                        </dt>
                        <dd style={{margin: "0", fontFamily: "'JetBrains Mono',ui-monospace,monospace", fontSize: "12.5px", overflowWrap: "anywhere"}}>
                          {txt(v.co?.gstinLabel)}
                        </dd>
                      </dl>
                      <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px 10px", padding: "10px 12px", border: "1px solid #a7f3d0", borderRadius: "12px", background: "#f0fdf4", fontSize: "13px", color: "#065f46"}}>
                        <strong>
                          {"Next employee ID"}
                        </strong>
                        <code style={{fontFamily: "'JetBrains Mono',ui-monospace,monospace", fontWeight: "700", color: "#0a5240", background: "#fff", border: "1px solid #a7f3d0", borderRadius: "6px", padding: "2px 8px"}}>
                          {txt(v.co?.nextId)}
                        </code>
                      </div>
                    </>
                  ) : null}
                </section>
              </aside>
              <section style={{flex: "999 1 0", minWidth: "min(100%,520px)", background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px", boxShadow: "0 1px 2px rgba(15,23,42,.04)", padding: "20px 22px", display: "grid", gap: "16px"}}>
                <div style={{display: "flex", flexWrap: "wrap", alignItems: "flex-start", justifyContent: "space-between", gap: "12px"}}>
                  <div style={{flex: "1 1 240px", minWidth: "0"}}>
                    <h2 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "17px", fontWeight: "700", display: "flex", alignItems: "center", gap: "8px"}}>
                      {"Branches"}
                      <span style={{padding: "1px 8px", borderRadius: "999px", background: "#ecfdf5", color: "#0a5240", fontFamily: "Inter,sans-serif", fontSize: "12px", fontWeight: "700", fontVariantNumeric: "tabular-nums"}}>
                        {txt(v.co?.branchCount)}
                      </span>
                    </h2>
                    <p style={{margin: "3px 0 0", fontSize: "13px", color: "#64748b", textWrap: "pretty"}}>
                      {"Offices under "}{txt(v.co?.name)}{" and their attendance boundaries."}
                    </p>
                  </div>
                  <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "10px"}}>
                    {v.showToggle ? (
                      <>
                        <div role="group" aria-label="View" style={{display: "inline-flex", padding: "3px", border: "1px solid #e2e8f0", borderRadius: "10px", background: "#f8fafc"}}>
                          {v.isCards ? (
                            <>
                              <button type="button" aria-pressed="true" style={{display: "inline-flex", alignItems: "center", gap: "6px", height: "30px", padding: "0 12px", border: "1px solid #a7f3d0", borderRadius: "8px", background: "#fff", color: "#0a5240", font: "inherit", fontSize: "12.5px", fontWeight: "700", cursor: "default"}}>
                                {txt(v.icGrid)}{" Cards"}
                              </button>
                              <button type="button" onClick={v.showTableView} data-tip="Switch to table view" style={{display: "inline-flex", alignItems: "center", gap: "6px", height: "30px", padding: "0 12px", border: "1px solid transparent", borderRadius: "8px", background: "transparent", color: "#475569", font: "inherit", fontSize: "12.5px", fontWeight: "600", cursor: "pointer"}}>
                                {txt(v.icList)}{" Table"}
                              </button>
                            </>
                          ) : null}
                          {v.isTable ? (
                            <>
                              <button type="button" onClick={v.showCardsView} data-tip="Switch to card view" style={{display: "inline-flex", alignItems: "center", gap: "6px", height: "30px", padding: "0 12px", border: "1px solid transparent", borderRadius: "8px", background: "transparent", color: "#475569", font: "inherit", fontSize: "12.5px", fontWeight: "600", cursor: "pointer"}}>
                                {txt(v.icGrid)}{" Cards"}
                              </button>
                              <button type="button" aria-pressed="true" style={{display: "inline-flex", alignItems: "center", gap: "6px", height: "30px", padding: "0 12px", border: "1px solid #a7f3d0", borderRadius: "8px", background: "#fff", color: "#0a5240", font: "inherit", fontSize: "12.5px", fontWeight: "700", cursor: "default"}}>
                                {txt(v.icList)}{" Table"}
                              </button>
                            </>
                          ) : null}
                        </div>
                      </>
                    ) : null}
                    {v.canEdit ? (
                      <>
                        <HrButton onClick={v.addBranch} data-tip="Opens Create branch">
                          {txt(v.icPlus)}{" Add branch"}
                        </HrButton>
                      </>
                    ) : null}
                  </div>
                </div>
                <div style={{display: "flex", flexWrap: "wrap", gap: "10px"}}>
                  <label style={{flex: "1 1 220px", display: "flex", alignItems: "center", gap: "8px", height: "38px", padding: "0 12px", border: "1px solid #e2e8f0", borderRadius: "10px", background: "#f8fafc", color: "#64748b"}}>
                    {txt(v.icSearch)}
                    <input type="search" value={v.q} onChange={v.setQ} aria-label="Search branches" placeholder="Search branches, cities or codes…" style={{flex: "1", minWidth: "0", border: "0", outline: "none", background: "transparent", font: "inherit", fontSize: "13px", color: "#0f172a"}} />
                  </label>
                  <div style={{flex: "0 1 160px", minWidth: "136px"}}>
                    <HrSelect size="sm" value={v.statusFilter} onChange={v.setStatus} options={v.statusOptions} />
                  </div>
                  <div style={{flex: "0 1 160px", minWidth: "136px"}}>
                    <HrSelect size="sm" value={v.cityFilter} onChange={v.setCity} options={v.cityOptions} />
                  </div>
                </div>
                {v.listLoading ? (
                  <>
                    <div role="status" aria-label="Loading branches" style={{display: "grid", gap: "10px"}}>
                      <SkeletonBlock {...(v.skRow || {})} />
                      <SkeletonBlock {...(v.skRow || {})} />
                      <SkeletonBlock {...(v.skRow || {})} />
                    </div>
                  </>
                ) : null}
                {v.listError ? (
                  <>
                    <EmptyState icon={v.emptyErrorIcon} title="Unable to load branches" description="The branch list didn't load. Other sections on this page are unaffected." action={v.retryAction} />
                  </>
                ) : null}
                {v.listEmpty ? (
                  <>
                    <EmptyState icon={v.emptyBuildingIcon} title="No branches yet" description="Add a branch to map your office locations and their attendance areas." action={v.addBranchAction} />
                  </>
                ) : null}
                {v.listNoMatch ? (
                  <>
                    <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "center", gap: "10px", padding: "28px 12px", border: "1px dashed #cbd5e1", borderRadius: "14px", fontSize: "13px", color: "#475569"}}>
                      {"No branches match these filters."}
                      <button type="button" onClick={v.clearFilters} style={{background: "none", border: "0", padding: "0", color: "#0f6e56", font: "inherit", fontWeight: "700", cursor: "pointer"}}>
                        {"Clear filters"}
                      </button>
                    </div>
                  </>
                ) : null}
                {v.showCards ? (
                  <>
                    <div style={{display: "grid", gap: "10px"}}>
                      {arr(v.rows).map((b: any, $index: number) => (
                        <Fragment key={$index}>
                          <article style={{display: "grid", gap: "12px", padding: "14px 16px", border: "1px solid #e2e8f0", borderRadius: "14px", background: "#fff"}} className="dc-companies-page-3">
                            <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "12px 14px"}}>
                              <span aria-hidden="true" style={{width: "48px", height: "48px", borderRadius: "12px", flexShrink: "0", display: "inline-flex", alignItems: "center", justifyContent: "center", color: "#0f6e56", background: "repeating-linear-gradient(135deg,#ecfdf5 0 8px,#f0fdf4 8px 16px)", border: "1px solid #d1fae5"}}>
                                {txt(v.icBuildingLg)}
                              </span>
                              <div style={{flex: "1 1 180px", minWidth: "0", display: "grid", gap: "4px"}}>
                                <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px"}}>
                                  <h4 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "15px", fontWeight: "700"}}>
                                    {txt(b?.name)}
                                  </h4>
                                  {b?.hq ? (
                                    <>
                                      <HrStatusPill tone="warn">
                                        {"Headquarters"}
                                      </HrStatusPill>
                                    </>
                                  ) : null}
                                </div>
                                <p style={{margin: "0", display: "flex", alignItems: "center", gap: "6px", fontSize: "13px", color: "#475569"}}>
                                  <span style={{display: "inline-flex", color: "#94a3b8"}}>
                                    {txt(v.icPin)}
                                  </span>
                                  {txt(b?.location)}
                                </p>
                              </div>
                              <div style={{display: "flex", gap: "8px", marginLeft: "auto"}}>
                                <HrButton variant="ghost" size="sm" onClick={b?.onManage} data-tip={b?.manageTip}>
                                  {txt(b?.manageLabel)}{" →"}
                                </HrButton>
                                {v.canEdit ? (
                                  <>
                                    <HrButton variant="ghost" size="sm" onClick={b?.onArchive} data-tip="Archives this branch">
                                      {"Archive"}
                                    </HrButton>
                                  </>
                                ) : null}
                              </div>
                            </div>
                            <dl style={{margin: "0", display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(100px,1fr))", gap: "10px", paddingTop: "12px", borderTop: "1px solid #f1f5f9", fontSize: "13px"}}>
                              <div>
                                <dt style={{fontSize: "11px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#64748b"}}>
                                  {"Code"}
                                </dt>
                                <dd style={{margin: "3px 0 0", fontFamily: "'JetBrains Mono',ui-monospace,monospace", fontWeight: "600"}}>
                                  {txt(b?.codeLabel)}
                                </dd>
                              </div>
                              <div>
                                <dt style={{fontSize: "11px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#64748b"}}>
                                  {"Employees"}
                                </dt>
                                <dd style={{margin: "3px 0 0"}}>
                                  <button type="button" onClick={b?.onEmployees} data-tip={b?.employeesTip} style={{background: "none", border: "0", padding: "0", font: "inherit", fontWeight: "700", color: "#0f6e56", cursor: "pointer", fontVariantNumeric: "tabular-nums", textDecoration: "underline", textDecorationColor: "#a7f3d0", textUnderlineOffset: "3px"}}>
                                    {txt(b?.employees)}
                                  </button>
                                </dd>
                              </div>
                              <div>
                                <dt style={{fontSize: "11px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#64748b"}}>
                                  {"Geofence"}
                                </dt>
                                <dd style={{margin: "3px 0 0", display: "flex", alignItems: "center", gap: "5px", fontWeight: "600"}}>
                                  {b?.geoOn ? (
                                    <>
                                      <span style={{display: "inline-flex", color: "#059669"}}>
                                        {txt(v.icShieldSm)}
                                      </span>
                                      <span style={{color: "#047857"}}>
                                        {txt(b?.geoLabel)}
                                      </span>
                                    </>
                                  ) : null}
                                  {b?.geoOff ? (
                                    <>
                                      <span style={{color: "#94a3b8"}}>
                                        {"Not set"}
                                      </span>
                                    </>
                                  ) : null}
                                </dd>
                              </div>
                              <div>
                                <dt style={{fontSize: "11px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#64748b"}}>
                                  {"Status"}
                                </dt>
                                <dd style={{margin: "3px 0 0"}}>
                                  <HrStatusPill tone={b?.tone}>
                                    {txt(b?.statusLabel)}
                                  </HrStatusPill>
                                </dd>
                              </div>
                            </dl>
                          </article>
                        </Fragment>
                      ))}
                    </div>
                  </>
                ) : null}
                {v.showTable ? (
                  <>
                    <div style={{margin: "0 -22px"}}>
                      <TableCard>
                        <DataTable columns={v.columns} data={v.rows} keyField="id" onRowClick={v.rowClick} />
                      </TableCard>
                    </div>
                  </>
                ) : null}
                {v.showAddMore ? (
                  <>
                    <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "center", gap: "12px 16px", padding: "18px", border: "1px dashed #cbd5e1", borderRadius: "14px", background: "#fcfdfd", textAlign: "center"}}>
                      <span style={{display: "inline-flex", color: "#0f6e56"}}>
                        {txt(v.icBuilding)}
                      </span>
                      <span style={{display: "grid", gap: "2px", textAlign: "left"}}>
                        <strong style={{fontSize: "13px"}}>
                          {"Add another branch"}
                        </strong>
                        <span style={{fontSize: "12px", color: "#64748b"}}>
                          {"Map more office locations and their check-in areas."}
                        </span>
                      </span>
                      <HrButton size="sm" onClick={v.addBranch} data-tip="Opens Create branch">
                        {txt(v.icPlus)}{" Add branch"}
                      </HrButton>
                    </div>
                  </>
                ) : null}
              </section>
            </div>
          </>
        ) : null}
        {v.noCompanies ? (
          <>
            <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: "10px 16px"}}>
              <h1 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "20px", fontWeight: "700", letterSpacing: "-.01em", color: "#0f172a"}}>
                {"Companies & Branches"}
              </h1>
              {v.canEdit ? (
                <>
                  <HrButton size="sm" onClick={v.addCompany} data-tip="Opens Add company">
                    {txt(v.icPlus)}{" Add company"}
                  </HrButton>
                </>
              ) : null}
            </div>
            <section style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px", boxShadow: "0 1px 2px rgba(15,23,42,.04)"}}>
              <EmptyState icon={v.emptyBuildingIcon} title="No companies yet" description="Add your first company to get started." action={v.addCompanyAction} />
            </section>
          </>
        ) : null}
      </div>
      {v.companyDrawerOpen ? (
        <>
          <CompanyDrawer company={v.drawerCompany} onSave={v.saveCompany} onSaveFormat={v.saveFormat} onClose={v.closeDrawer} />
        </>
      ) : null}
      {v.branchDrawerOpen ? (
        <>
          <BranchDrawer branch={v.drawerBranch} companyName={v.co?.name} currentHq={v.currentHq} readOnly={v.readOnly} onSave={v.saveBranch} onClose={v.closeDrawer} />
        </>
      ) : null}
      <Modal open={v.confirmOpen} onOpenChange={v.setConfirmOpen} title={v.confirmTitle} description="It will be hidden from lists and pickers. Existing employee assignments are kept." size="sm">
        <div style={{display: "flex", justifyContent: "flex-end", gap: "8px", marginTop: "8px"}}>
          <HrButton variant="ghost" onClick={v.cancelConfirm}>
            {"Cancel"}
          </HrButton>
          <HrButton variant="danger" onClick={v.doArchive}>
            {"Archive"}
          </HrButton>
        </div>
      </Modal>
    </>
  )
}
