// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component DashCalendar.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { Fragment } from 'react'
import { HrButton, HrStatusPill } from '@/shared/components/hr'
import { CalChip, MonthGrid, YearGrid } from '@/shared/components/calendar'
import { arr, txt } from './dc-runtime'
import './DashCalendar.view.css'

export function DashCalendarView({ v }: { v: any }) {
  return (
    <>
      <div ref={v.rootRef} role="dialog" aria-modal="true" aria-label="Choose dashboard date" tabIndex={-1} onKeyDown={v.onKey} style={{display: "flex", flexWrap: "wrap", background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px", boxShadow: "0 24px 48px -16px rgba(15,23,42,.32)", overflow: "hidden", outline: "none", fontFamily: "Inter,-apple-system,sans-serif", color: "#0f172a"}}>
        <div style={{flex: "1 1 300px", minWidth: "0", padding: "16px 16px 14px", display: "grid", gap: "12px", alignContent: "start"}}>
          <div style={{display: "flex", alignItems: "center", justifyContent: "space-between", gap: "10px"}}>
            <div>
              <p style={{margin: "0", fontSize: "11px", fontWeight: "700", letterSpacing: ".08em", textTransform: "uppercase", color: "#0f6e56"}}>
                {"Dashboard date · IST"}
              </p>
              <h3 aria-label={v.monthLabel} style={{margin: "2px 0 0 0", display: "flex", alignItems: "center", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "17px", fontWeight: "700", letterSpacing: "-.01em"}}>
                <CalChip label={v.monthChip} active={v.isMonths} onClick={v.showMonths} ariaLabel={v.isMonths ? 'Back to days' : 'Choose month'} />
                <CalChip label={v.yearChip} active={v.isYears} onClick={v.showYears} ariaLabel={v.isYears ? 'Close year list' : 'Choose year'} />
              </h3>
            </div>
            <div style={{display: "flex", gap: "6px"}}>
              <button type="button" aria-label={v.prevAria} onClick={v.prevMonth} disabled={v.prevOff} style={{width: "34px", height: "34px", display: "inline-flex", alignItems: "center", justifyContent: "center", border: "1px solid #e2e8f0", borderRadius: "9px", background: "#fff", color: v.prevOff ? "#cbd5e1" : "#334155", cursor: v.prevOff ? "not-allowed" : "pointer"}} className="dc-dash-calendar-0">
                {txt(v.icPrev)}
              </button>
              <button type="button" aria-label={v.nextAria} onClick={v.nextMonth} disabled={v.nextOff} style={{width: "34px", height: "34px", display: "inline-flex", alignItems: "center", justifyContent: "center", border: "1px solid #e2e8f0", borderRadius: "9px", background: "#fff", color: v.nextOff ? "#cbd5e1" : "#334155", cursor: v.nextOff ? "not-allowed" : "pointer"}} className="dc-dash-calendar-0">
                {txt(v.icNext)}
              </button>
            </div>
          </div>
          <div style={{display: "flex", gap: "6px", flexWrap: "wrap"}}>
            <button type="button" onClick={v.pickToday} style={{height: "28px", padding: "0 10px", borderRadius: "999px", border: "1px solid #a7f3d0", background: "#ecfdf5", color: "#0a5240", font: "inherit", fontSize: "12px", fontWeight: "600", cursor: "pointer"}} className="dc-dash-calendar-1">
              {"Today"}
            </button>
            <button type="button" onClick={v.pickYesterday} style={{height: "28px", padding: "0 10px", borderRadius: "999px", border: "1px solid #e2e8f0", background: "#fff", color: "#334155", font: "inherit", fontSize: "12px", fontWeight: "600", cursor: "pointer"}} className="dc-dash-calendar-2">
              {"Yesterday"}
            </button>
            <button type="button" onClick={v.pickLastWorking} style={{height: "28px", padding: "0 10px", borderRadius: "999px", border: "1px solid #e2e8f0", background: "#fff", color: "#334155", font: "inherit", fontSize: "12px", fontWeight: "600", cursor: "pointer"}} className="dc-dash-calendar-2">
              {"Last working day"}
            </button>
          </div>
          {v.isMonths ? (
            <>
              <div style={{height: "272px"}}>
                <MonthGrid uid={v.grids?.uid} year={Number(String(v.grids?.curMonth).slice(0, 4))} today={v.grids?.today} min={v.grids?.min} max={v.grids?.max} selected={v.grids?.selectedMonth} cursor={v.grids?.curMonth} showCursor={v.grids?.kbd} onPick={v.grids?.pickMonth} />
              </div>
            </>
          ) : null}
          {v.isYears ? (
            <>
              <div style={{height: "272px"}}>
                <YearGrid uid={v.grids?.uid} lo={v.grids?.lo} hi={v.grids?.hi} today={v.grids?.today} min={v.grids?.min} max={v.grids?.max} selected={v.grids?.selectedYear} cursor={v.grids?.curYear} showCursor={v.grids?.kbd} onPick={v.grids?.pickYear} />
              </div>
            </>
          ) : null}
          {v.isDays ? (
            <>
          <div style={{display: "grid", gridTemplateColumns: "repeat(7,minmax(0,1fr))", gap: "4px", fontSize: "11px", fontWeight: "700", letterSpacing: ".04em", textTransform: "uppercase", textAlign: "center"}}>
            <span style={{color: "#64748b"}}>
              {"Mon"}
            </span>
            <span style={{color: "#64748b"}}>
              {"Tue"}
            </span>
            <span style={{color: "#64748b"}}>
              {"Wed"}
            </span>
            <span style={{color: "#64748b"}}>
              {"Thu"}
            </span>
            <span style={{color: "#64748b"}}>
              {"Fri"}
            </span>
            <span style={{color: "#64748b"}}>
              {"Sat"}
            </span>
            <span style={{color: "#94a3b8"}}>
              {"Sun"}
            </span>
          </div>
          <div role="grid" aria-label={v.monthLabel} style={{display: "grid", gridTemplateColumns: "repeat(7,minmax(0,1fr))", gap: "4px"}}>
            {arr(v.cells).map((c: any, $index: number) => (
              <Fragment key={$index}>
                {c?.isSel ? (
                  <>
                    <button type="button" role="gridcell" aria-selected="true" aria-label={c?.label} title={c?.label} onClick={c?.onClick} style={{height: "42px", border: "0", borderRadius: "10px", background: "#0f6e56", color: "#fff", font: "inherit", fontSize: "13px", fontWeight: "700", fontVariantNumeric: "tabular-nums", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: "4px", cursor: "pointer", boxShadow: "0 6px 14px -6px rgba(15,110,86,.6)"}}>
                      <span>
                        {txt(c?.day)}
                      </span>
                      <svg width="14" height="3" aria-hidden="true">
                        <rect width="14" height="3" rx="1.5" fill={c?.markColor} fillOpacity={c?.markOpacity} />
                      </svg>
                    </button>
                  </>
                ) : null}
                {c?.isToday ? (
                  <>
                    <button type="button" role="gridcell" aria-current="date" aria-label={c?.label} title={c?.label} onClick={c?.onClick} style={{height: "42px", border: "0", borderRadius: "10px", background: "#fff", color: "#0f6e56", font: "inherit", fontSize: "13px", fontWeight: "800", fontVariantNumeric: "tabular-nums", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: "4px", cursor: "pointer", boxShadow: "inset 0 0 0 1.5px #0f6e56"}} className="dc-dash-calendar-3">
                      <span>
                        {txt(c?.day)}
                      </span>
                      <svg width="14" height="3" aria-hidden="true">
                        <rect width="14" height="3" rx="1.5" fill={c?.markColor} fillOpacity={c?.markOpacity} />
                      </svg>
                    </button>
                  </>
                ) : null}
                {c?.isDay ? (
                  <>
                    <button type="button" role="gridcell" aria-label={c?.label} title={c?.label} onClick={c?.onClick} style={{height: "42px", border: "0", borderRadius: "10px", background: "transparent", color: "#0f172a", font: "inherit", fontSize: "13px", fontWeight: "500", fontVariantNumeric: "tabular-nums", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: "4px", cursor: "pointer"}} className="dc-dash-calendar-0">
                      <span>
                        {txt(c?.day)}
                      </span>
                      <svg width="14" height="3" aria-hidden="true">
                        <rect width="14" height="3" rx="1.5" fill={c?.markColor} fillOpacity={c?.markOpacity} />
                      </svg>
                    </button>
                  </>
                ) : null}
                {c?.isOff ? (
                  <>
                    <button type="button" role="gridcell" aria-label={c?.label} title={c?.label} onClick={c?.onClick} style={{height: "42px", border: "0", borderRadius: "10px", background: "#f8fafc", color: "#94a3b8", font: "inherit", fontSize: "13px", fontWeight: "500", fontVariantNumeric: "tabular-nums", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: "4px", cursor: "pointer"}} className="dc-dash-calendar-4">
                      <span>
                        {txt(c?.day)}
                      </span>
                      <svg width="14" height="4" aria-hidden="true">
                        <circle cx="7" cy="2" r="2" fill="#f59e0b" fillOpacity={c?.holidayOpacity} />
                      </svg>
                    </button>
                  </>
                ) : null}
                {c?.isFuture ? (
                  <>
                    <button type="button" role="gridcell" aria-disabled="true" aria-label={c?.label} title={c?.label} style={{height: "42px", border: "0", borderRadius: "10px", background: "transparent", color: "#cbd5e1", font: "inherit", fontSize: "13px", fontWeight: "500", fontVariantNumeric: "tabular-nums", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: "4px", cursor: "not-allowed"}}>
                      <span>
                        {txt(c?.day)}
                      </span>
                      <svg width="14" height="4" aria-hidden="true">
                        <circle cx="7" cy="2" r="2" fill="#f59e0b" fillOpacity={c?.holidayOpacity} />
                      </svg>
                    </button>
                  </>
                ) : null}
                {c?.isOut ? (
                  <>
                    <span aria-hidden="true" style={{height: "42px", display: "flex", alignItems: "center", justifyContent: "center", color: "#e2e8f0", fontSize: "13px", fontVariantNumeric: "tabular-nums"}}>
                      {txt(c?.day)}
                    </span>
                  </>
                ) : null}
              </Fragment>
            ))}
          </div>
            </>
          ) : null}
          <div style={{display: "flex", flexWrap: "wrap", gap: "6px 14px", paddingTop: "10px", borderTop: "1px solid #f1f5f9", fontSize: "11px", color: "#64748b"}}>
            <span style={{display: "inline-flex", alignItems: "center", gap: "5px"}}>
              <i style={{width: "12px", height: "12px", borderRadius: "4px", boxShadow: "inset 0 0 0 1.5px #0f6e56", display: "inline-block"}} />
              {"Today"}
            </span>
            <span style={{display: "inline-flex", alignItems: "center", gap: "5px"}}>
              <i style={{width: "12px", height: "12px", borderRadius: "4px", background: "#0f6e56", display: "inline-block"}} />
              {"Selected"}
            </span>
            <span style={{display: "inline-flex", alignItems: "center", gap: "5px"}}>
              <i style={{width: "6px", height: "6px", borderRadius: "999px", background: "#f59e0b", display: "inline-block"}} />
              {"Holiday"}
            </span>
            <span style={{display: "inline-flex", alignItems: "center", gap: "5px"}}>
              <svg width="34" height="3" aria-hidden="true">
                <rect width="10" height="3" rx="1.5" fill={v.rate?.hi} />
                <rect x="12" width="10" height="3" rx="1.5" fill={v.rate?.mid} />
                <rect x="24" width="10" height="3" rx="1.5" fill={v.rate?.lo} />
              </svg>
              {"Attendance ≥90 · 75–89 · <75%"}
            </span>
          </div>
        </div>
        <div style={{flex: "1 1 230px", minWidth: "0", background: "#f8fafc", padding: "18px 16px 16px", display: "flex", flexDirection: "column", gap: "12px", boxShadow: "inset 1px 0 0 #e2e8f0"}}>
          <div>
            <p style={{margin: "0 0 4px", fontSize: "11px", fontWeight: "700", letterSpacing: ".08em", textTransform: "uppercase", color: "#64748b"}}>
              {"Selected day"}
            </p>
            <h4 style={{margin: "0 0 8px", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "16px", fontWeight: "700", lineHeight: "1.3"}}>
              {txt(v.panel?.title)}
            </h4>
            <HrStatusPill tone={v.panel?.tone}>
              {txt(v.panel?.tag)}
            </HrStatusPill>
          </div>
          {v.panel?.hasData ? (
            <>
              <div style={{display: "grid", gap: "6px"}}>
                <div style={{display: "flex", alignItems: "baseline", gap: "8px"}}>
                  <span style={{fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "28px", fontWeight: "800", lineHeight: "1", letterSpacing: "-.02em", fontVariantNumeric: "tabular-nums"}}>
                    {txt(v.panel?.rate)}
                  </span>
                  <span style={{fontSize: "12px", color: "#64748b"}}>
                    {"attendance"}
                  </span>
                </div>
                <svg viewBox="0 0 100 6" preserveAspectRatio="none" aria-hidden="true" style={{display: "block", width: "100%", height: "6px", borderRadius: "3px", overflow: "hidden"}}>
                  <rect width="100" height="6" fill="#e2e8f0" />
                  <rect width={v.panel?.ratePct} height="6" fill={v.panel?.rateColor} />
                </svg>
                <p style={{margin: "0", fontSize: "12px", color: "#64748b", fontVariantNumeric: "tabular-nums"}}>
                  {txt(v.panel?.scheduled)}
                </p>
              </div>
              <div style={{display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: "8px"}}>
                {arr(v.panel?.stats).map((s: any, $index: number) => (
                  <Fragment key={$index}>
                    <div style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "10px", padding: "8px 10px"}}>
                      <p style={{margin: "0", display: "flex", alignItems: "center", gap: "6px", fontSize: "11px", color: "#64748b"}}>
                        <svg width="8" height="8" aria-hidden="true">
                          <circle cx="4" cy="4" r="4" fill={s?.color} />
                        </svg>
                        {txt(s?.label)}
                      </p>
                      <p style={{margin: "2px 0 0", fontSize: "17px", fontWeight: "700", fontVariantNumeric: "tabular-nums"}}>
                        {txt(s?.value)}
                      </p>
                    </div>
                  </Fragment>
                ))}
              </div>
            </>
          ) : null}
          {v.panel?.noData ? (
            <>
              <p style={{margin: "0", fontSize: "13px", lineHeight: "1.5", color: "#64748b", textWrap: "pretty"}}>
                {txt(v.panel?.note)}
              </p>
            </>
          ) : null}
          <div style={{marginTop: "auto", display: "grid", gap: "8px", paddingTop: "4px"}}>
            <HrButton onClick={v.apply}>
              {txt(v.applyLabel)}
            </HrButton>
            <div style={{display: "flex", alignItems: "center", justifyContent: "space-between", gap: "8px"}}>
              <HrButton variant="ghost" size="sm" onClick={v.close}>
                {"Cancel"}
              </HrButton>
              <button type="button" onClick={v.openTracking} style={{background: "none", border: "0", padding: "0", color: "#0f6e56", font: "inherit", fontSize: "12px", fontWeight: "600", cursor: "pointer"}}>
                {"Daily Tracking for this day →"}
              </button>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
