// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component DatePicker.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { Fragment } from 'react'
import { arr, txt, UTPortal } from './dc-runtime'
import './DatePicker.view.css'

export function DatePickerView({ v }: { v: any }) {
  return (
    <>
      <div ref={v.rootRef} style={{position: "relative", width: "100%", minWidth: "0", fontFamily: "Inter,-apple-system,sans-serif", color: "#0f172a"}}>
        <button ref={v.triggerRef} type="button" onClick={v.toggle} onKeyDown={v.triggerKey} aria-haspopup="dialog" aria-expanded={v.open} aria-label={v.triggerAria} style={{position: "relative", width: "100%", height: "42px", display: "flex", alignItems: "center", gap: "10px", padding: "0 12px", boxSizing: "border-box", border: "1px solid #cbd5e1", borderRadius: "10px", background: "#fff", font: "inherit", fontSize: "14px", fontWeight: "500", color: "#0f172a", textAlign: "left", cursor: "pointer", outline: "none", transition: "border-color .15s,box-shadow .15s"}} className="dc-date-picker-0 dc-date-picker-1">
          {v.open ? (
            <>
              <span aria-hidden="true" style={{position: "absolute", inset: "-1px", borderRadius: "10px", boxShadow: "0 0 0 1px #0f6e56,0 0 0 4px #a7f3d0", pointerEvents: "none"}} />
            </>
          ) : null}
          <span aria-hidden="true" style={{display: "inline-flex", flexShrink: "0", color: "#0f6e56"}}>
            {txt(v.icCal)}
          </span>
          {v.hasValue ? (
            <>
              <span style={{flex: "1", minWidth: "0", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontVariantNumeric: "tabular-nums"}}>
                {txt(v.display)}
              </span>
            </>
          ) : null}
          {v.noValue ? (
            <>
              <span style={{flex: "1", minWidth: "0", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", color: "#94a3b8", fontWeight: "400"}}>
                {txt(v.placeholder)}
              </span>
            </>
          ) : null}
          <span aria-hidden="true" style={{display: "inline-flex", flexShrink: "0", color: "#94a3b8"}}>
            {txt(v.icChev)}
          </span>
        </button>
        {v.open ? (
          <>
            <UTPortal>
              <div ref={v.setPop} role="dialog" aria-label="Choose a date" onMouseDown={v.keepFocus} style={{position: "fixed", top: "0", left: "0", zIndex: "1200", width: "316px", boxSizing: "border-box", padding: "14px", background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px", boxShadow: "0 24px 48px -16px rgba(15,23,42,.32),0 2px 6px rgba(15,23,42,.06)", display: "grid", gap: "10px", fontFamily: "Inter,-apple-system,sans-serif", fontSize: "13px", fontWeight: "500", color: "#0f172a", textAlign: "left", userSelect: "none"}}>
                <div style={{display: "flex", alignItems: "center", justifyContent: "space-between", gap: "8px"}}>
                  <button type="button" tabIndex={-1} onClick={v.toggleView} aria-label={v.viewAria} style={{display: "inline-flex", alignItems: "center", gap: "6px", height: "32px", padding: "0 8px", marginLeft: "-6px", border: "0", borderRadius: "8px", background: "transparent", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "15px", fontWeight: "700", letterSpacing: "-.01em", color: "#0f172a", cursor: "pointer"}} className="dc-date-picker-2">
                    {txt(v.title)}
                    <span aria-hidden="true" style={{display: "inline-flex", color: "#64748b"}}>
                      {txt(v.icCaret)}
                    </span>
                  </button>
                  <div style={{display: "flex", gap: "4px"}}>
                    {v.prevOn ? (
                      <>
                        <button type="button" tabIndex={-1} aria-label={v.prevAria} onClick={v.prev} style={{width: "32px", height: "32px", display: "inline-flex", alignItems: "center", justifyContent: "center", border: "1px solid #e2e8f0", borderRadius: "9px", background: "#fff", color: "#334155", cursor: "pointer"}} className="dc-date-picker-3">
                          {txt(v.icPrev)}
                        </button>
                      </>
                    ) : null}
                    {v.prevOff ? (
                      <>
                        <button type="button" tabIndex={-1} aria-label={v.prevAria} disabled={true} style={{width: "32px", height: "32px", display: "inline-flex", alignItems: "center", justifyContent: "center", border: "1px solid #f1f5f9", borderRadius: "9px", background: "#fff", color: "#cbd5e1", cursor: "not-allowed"}}>
                          {txt(v.icPrev)}
                        </button>
                      </>
                    ) : null}
                    {v.nextOn ? (
                      <>
                        <button type="button" tabIndex={-1} aria-label={v.nextAria} onClick={v.next} style={{width: "32px", height: "32px", display: "inline-flex", alignItems: "center", justifyContent: "center", border: "1px solid #e2e8f0", borderRadius: "9px", background: "#fff", color: "#334155", cursor: "pointer"}} className="dc-date-picker-3">
                          {txt(v.icNext)}
                        </button>
                      </>
                    ) : null}
                    {v.nextOff ? (
                      <>
                        <button type="button" tabIndex={-1} aria-label={v.nextAria} disabled={true} style={{width: "32px", height: "32px", display: "inline-flex", alignItems: "center", justifyContent: "center", border: "1px solid #f1f5f9", borderRadius: "9px", background: "#fff", color: "#cbd5e1", cursor: "not-allowed"}}>
                          {txt(v.icNext)}
                        </button>
                      </>
                    ) : null}
                  </div>
                </div>
                {v.isDays ? (
                  <>
                    <div aria-hidden="true" style={{display: "grid", gridTemplateColumns: "repeat(7,minmax(0,1fr))", gap: "4px", fontSize: "11px", fontWeight: "700", letterSpacing: ".04em", textTransform: "uppercase", textAlign: "center", color: "#64748b"}}>
                      <span>
                        {"Mo"}
                      </span>
                      <span>
                        {"Tu"}
                      </span>
                      <span>
                        {"We"}
                      </span>
                      <span>
                        {"Th"}
                      </span>
                      <span>
                        {"Fr"}
                      </span>
                      <span>
                        {"Sa"}
                      </span>
                      <span style={{color: "#94a3b8"}}>
                        {"Su"}
                      </span>
                    </div>
                    <div role="grid" aria-label={v.title} style={{display: "grid", gridTemplateColumns: "repeat(7,minmax(0,1fr))", gap: "4px"}}>
                      {arr(v.cells).map((c: any, $index: number) => (
                        <Fragment key={$index}>
                          <div style={{position: "relative"}}>
                            {c?.isCursor ? (
                              <>
                                <span aria-hidden="true" style={{position: "absolute", inset: "-2px", borderRadius: "12px", boxShadow: "0 0 0 2px #34d399", pointerEvents: "none"}} />
                              </>
                            ) : null}
                            {c?.isSel ? (
                              <>
                                <button type="button" tabIndex={-1} aria-label={c?.aria} aria-pressed="true" onClick={c?.onClick} style={{width: "100%", height: "38px", border: "0", borderRadius: "10px", background: "#0f6e56", color: "#fff", font: "inherit", fontSize: "13px", fontWeight: "700", fontVariantNumeric: "tabular-nums", cursor: "pointer", boxShadow: "0 6px 14px -6px rgba(15,110,86,.7)"}}>
                                  {txt(c?.day)}
                                </button>
                              </>
                            ) : null}
                            {c?.isToday ? (
                              <>
                                <button type="button" tabIndex={-1} aria-label={c?.aria} aria-current="date" onClick={c?.onClick} style={{width: "100%", height: "38px", border: "0", borderRadius: "10px", background: "#fff", color: "#0f6e56", font: "inherit", fontSize: "13px", fontWeight: "800", fontVariantNumeric: "tabular-nums", cursor: "pointer", boxShadow: "inset 0 0 0 1.5px #0f6e56"}} className="dc-date-picker-4">
                                  {txt(c?.day)}
                                </button>
                              </>
                            ) : null}
                            {c?.isDay ? (
                              <>
                                <button type="button" tabIndex={-1} aria-label={c?.aria} onClick={c?.onClick} style={{width: "100%", height: "38px", border: "0", borderRadius: "10px", background: "transparent", color: "#0f172a", font: "inherit", fontSize: "13px", fontWeight: "500", fontVariantNumeric: "tabular-nums", cursor: "pointer"}} className="dc-date-picker-5">
                                  {txt(c?.day)}
                                </button>
                              </>
                            ) : null}
                            {c?.isOut ? (
                              <>
                                <button type="button" tabIndex={-1} aria-label={c?.aria} onClick={c?.onClick} style={{width: "100%", height: "38px", border: "0", borderRadius: "10px", background: "transparent", color: "#94a3b8", font: "inherit", fontSize: "13px", fontWeight: "500", fontVariantNumeric: "tabular-nums", cursor: "pointer"}} className="dc-date-picker-6">
                                  {txt(c?.day)}
                                </button>
                              </>
                            ) : null}
                            {c?.isDis ? (
                              <>
                                <button type="button" tabIndex={-1} aria-label={c?.aria} disabled={true} style={{width: "100%", height: "38px", border: "0", borderRadius: "10px", background: "transparent", color: "#cbd5e1", font: "inherit", fontSize: "13px", fontWeight: "500", fontVariantNumeric: "tabular-nums", cursor: "not-allowed"}}>
                                  {txt(c?.day)}
                                </button>
                              </>
                            ) : null}
                          </div>
                        </Fragment>
                      ))}
                    </div>
                  </>
                ) : null}
                {v.isMonths ? (
                  <>
                    <div role="grid" aria-label={v.title} style={{display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: "6px", padding: "2px 0"}}>
                      {arr(v.months).map((mo: any, $index: number) => (
                        <Fragment key={$index}>
                          <div style={{position: "relative"}}>
                            {mo?.isCursor ? (
                              <>
                                <span aria-hidden="true" style={{position: "absolute", inset: "-2px", borderRadius: "12px", boxShadow: "0 0 0 2px #34d399", pointerEvents: "none"}} />
                              </>
                            ) : null}
                            {mo?.isSel ? (
                              <>
                                <button type="button" tabIndex={-1} aria-pressed="true" onClick={mo?.onClick} style={{width: "100%", height: "50px", border: "0", borderRadius: "11px", background: "#0f6e56", color: "#fff", font: "inherit", fontSize: "13.5px", fontWeight: "700", cursor: "pointer", boxShadow: "0 6px 14px -6px rgba(15,110,86,.7)"}}>
                                  {txt(mo?.label)}
                                </button>
                              </>
                            ) : null}
                            {mo?.isCur ? (
                              <>
                                <button type="button" tabIndex={-1} onClick={mo?.onClick} style={{width: "100%", height: "50px", border: "0", borderRadius: "11px", background: "#fff", color: "#0f6e56", font: "inherit", fontSize: "13.5px", fontWeight: "800", cursor: "pointer", boxShadow: "inset 0 0 0 1.5px #0f6e56"}} className="dc-date-picker-4">
                                  {txt(mo?.label)}
                                </button>
                              </>
                            ) : null}
                            {mo?.isNorm ? (
                              <>
                                <button type="button" tabIndex={-1} onClick={mo?.onClick} style={{width: "100%", height: "50px", border: "0", borderRadius: "11px", background: "#f8fafc", color: "#0f172a", font: "inherit", fontSize: "13.5px", fontWeight: "600", cursor: "pointer"}} className="dc-date-picker-5">
                                  {txt(mo?.label)}
                                </button>
                              </>
                            ) : null}
                            {mo?.isDis ? (
                              <>
                                <button type="button" tabIndex={-1} disabled={true} style={{width: "100%", height: "50px", border: "0", borderRadius: "11px", background: "#fff", color: "#cbd5e1", font: "inherit", fontSize: "13.5px", fontWeight: "600", cursor: "not-allowed"}}>
                                  {txt(mo?.label)}
                                </button>
                              </>
                            ) : null}
                          </div>
                        </Fragment>
                      ))}
                    </div>
                  </>
                ) : null}
                {v.hasFooter ? (
                  <>
                    <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "6px", paddingTop: "10px", borderTop: "1px solid #f1f5f9"}}>
                      {arr(v.presets).map((pr: any, $index: number) => (
                        <Fragment key={$index}>
                          {pr?.active ? (
                            <>
                              <button type="button" tabIndex={-1} onClick={pr?.onClick} style={{height: "28px", padding: "0 10px", borderRadius: "999px", border: "1px solid #6ee7b7", background: "#ecfdf5", color: "#0a5240", font: "inherit", fontSize: "12px", fontWeight: "700", cursor: "pointer"}}>
                                {txt(pr?.label)}
                              </button>
                            </>
                          ) : null}
                          {pr?.inactive ? (
                            <>
                              <button type="button" tabIndex={-1} onClick={pr?.onClick} style={{height: "28px", padding: "0 10px", borderRadius: "999px", border: "1px solid #e2e8f0", background: "#fff", color: "#334155", font: "inherit", fontSize: "12px", fontWeight: "600", cursor: "pointer"}} className="dc-date-picker-7">
                                {txt(pr?.label)}
                              </button>
                            </>
                          ) : null}
                        </Fragment>
                      ))}
                      {v.showClear ? (
                        <>
                          <button type="button" tabIndex={-1} onClick={v.clear} style={{marginLeft: "auto", height: "28px", padding: "0 8px", border: "0", borderRadius: "8px", background: "transparent", font: "inherit", fontSize: "12px", fontWeight: "700", color: "#be123c", cursor: "pointer"}} className="dc-date-picker-8">
                            {"Clear"}
                          </button>
                        </>
                      ) : null}
                    </div>
                  </>
                ) : null}
              </div>
            </UTPortal>
          </>
        ) : null}
      </div>
    </>
  )
}
