// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component EmployeeWorkspace.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { Fragment } from 'react'
import { HrAvatar, HrButton, HrDrawer, HrSelect, HrStatusPill, HrTabPanel, HrTabs, TableCard } from '@/shared/components/hr'
import { DataTable } from '@/shared/components/DataTable'
import { EmptyState } from '@/shared/components/EmptyState'
import { SkeletonBlock, SkeletonCardGrid } from '@/shared/components/SkeletonCard'
import { Input, Label, Modal } from '@unifiedtree/ui-kit'
import { DateField } from '@/shared/components/calendar'
import { arr, txt } from './dc-runtime'
import './EmployeeWorkspace.view.css'

export function EmployeeWorkspaceView({ v }: { v: any }) {
  return (
    <>
      <div style={{display: "flex", flexDirection: "column", gap: "12px", fontFamily: "'Plus Jakarta Sans',sans-serif", color: "#0f172a", minWidth: "0", fontSize: "13.5px"}}>
        <a onClick={v.back} style={{display: "inline-flex", alignItems: "center", gap: "6px", fontSize: "13.5px", fontWeight: "600", color: "#475569", textDecoration: "none", cursor: "pointer", alignSelf: "flex-start"}} className="dc-employee-workspace-0">
          {"← Back"}
        </a>
        {v.pLoading ? (
          <>
            <div role="status" aria-label="Loading employee" style={{display: "flex", flexDirection: "column", gap: "12px"}}>
              <div style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "14px", padding: "16px 18px", display: "flex", alignItems: "center", gap: "14px"}}>
                <SkeletonBlock className="h-12 w-12 rounded-xl" />
                <div style={{display: "flex", flexDirection: "column", gap: "8px", flex: "1"}}>
                  <SkeletonBlock className="h-3 w-40" />
                  <SkeletonBlock className="h-3 w-20" />
                </div>
              </div>
              <SkeletonCardGrid count={v.four} />
            </div>
          </>
        ) : null}
        {v.pFailed ? (
          <>
            <div role="alert" style={{background: "#fff", border: "1px solid #fecdd3", borderRadius: "14px", padding: "18px", display: "flex", flexWrap: "wrap", alignItems: "center", gap: "12px 16px"}}>
              <span style={{width: "40px", height: "40px", borderRadius: "11px", background: "#fff1f2", color: "#e11d48", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: "800"}}>
                {"!"}
              </span>
              <div style={{flex: "1 1 220px"}}>
                <div style={{fontSize: "15px", fontWeight: "700"}}>
                  {"Failed to load employee"}
                </div>
                <div style={{fontSize: "13px", color: "#64748b", marginTop: "2px"}}>
                  {"Something went wrong on our side. Nothing was changed."}
                </div>
              </div>
              <HrButton variant="ghost" onClick={v.retry}>
                {"Retry"}
              </HrButton>
            </div>
          </>
        ) : null}
        {v.pMissing ? (
          <>
            <div style={{background: "#fff", border: "1.5px dashed #cbd5e1", borderRadius: "14px"}}>
              <EmptyState icon={v.boxIcon} title="Employee not found" description="Check the details and try again." action={v.backAction} />
            </div>
          </>
        ) : null}
        {v.pReady ? (
          <>
            <section style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px", boxShadow: "0 1px 2px rgba(15,23,42,.05)"}}>
              <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: "12px 18px", padding: "14px 18px"}}>
                <div style={{flex: "1 1 380px", minWidth: "0", display: "flex", flexDirection: "column", gap: "4px"}}>
                  <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "6px 10px"}}>
                    <div style={{zoom: "1.45"}}>
                      <HrAvatar name={v.name} seed={v.seed} />
                    </div>
                    <span style={{fontFamily: "'JetBrains Mono',ui-monospace,monospace", fontSize: "12px", fontWeight: "600", padding: "2px 8px", borderRadius: "7px", background: "#f1f5f9", border: "1px solid #e2e8f0", color: "#334155", whiteSpace: "nowrap"}}>
                      {txt(v.code)}
                    </span>
                    <HrStatusPill tone={v.tone}>
                      {txt(v.status)}
                    </HrStatusPill>
                  </div>
                  <div style={{paddingLeft: "70px", fontSize: "13px", color: "#475569", fontWeight: "500"}}>
                    {txt(v.metaLine)}
                  </div>
                </div>
                <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px", whiteSpace: "nowrap"}}>
                  {v.canShift ? (
                    <>
                      <HrButton variant="ghost" size="sm" onClick={v.openShift}>
                        {"Change shift"}
                      </HrButton>
                    </>
                  ) : null}
                  {v.canEdit ? (
                    <>
                      <HrButton variant="ghost" size="sm" onClick={v.openEdit}>
                        {"Edit employee"}
                      </HrButton>
                    </>
                  ) : null}
                  {v.hasActs ? (
                    <>
                      <div ref={v.menuRef} style={{position: "relative"}}>
                        <HrButton size="sm" onClick={v.toggleMenu}>
                          {"Actions ▾"}
                        </HrButton>
                        {v.menu ? (
                          <>
                            <div role="menu" style={{position: "absolute", right: "0", top: "calc(100% + 6px)", zIndex: "60", minWidth: "200px", background: "#fff", border: "1px solid #e2e8f0", borderRadius: "12px", boxShadow: "0 16px 40px -14px rgba(15,110,86,.3)", padding: "5px"}}>
                              {arr(v.acts).map((a: any, $index: number) => (
                                <Fragment key={$index}>
                                  <button type="button" role="menuitem" onClick={a?.on} style={{display: "block", width: "100%", textAlign: "left", padding: "8px 11px", border: "0", background: "transparent", borderRadius: "8px", font: "600 13.5px 'Plus Jakarta Sans',sans-serif", color: "#0f172a", cursor: "pointer"}} className="dc-employee-workspace-1">
                                    {txt(a?.label)}
                                  </button>
                                </Fragment>
                              ))}
                            </div>
                          </>
                        ) : null}
                      </div>
                    </>
                  ) : null}
                </div>
              </div>
              {v.showBanner ? (
                <>
                  <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px 14px", padding: "10px 18px", background: "#fffbeb", borderTop: "1px solid #fde68a"}}>
                    <span style={{fontSize: "15px"}}>
                      {"⏳"}
                    </span>
                    <div style={{flex: "1 1 240px", minWidth: "0"}}>
                      <b style={{fontSize: "13.5px", color: "#92400e"}}>
                        {txt(v.bTitle)}
                      </b>
                      <span style={{fontSize: "12.5px", color: "#a16207"}}>
                        {" · "}{txt(v.bSub)}
                      </span>
                    </div>
                    <div style={{display: "flex", flexWrap: "wrap", gap: "6px", whiteSpace: "nowrap"}}>
                      {v.canLifecycle ? (
                        <>
                          <HrButton size="sm" onClick={v.mConfirm}>
                            {"Confirm as permanent"}
                          </HrButton>
                        </>
                      ) : null}
                      {v.canLifecycle ? (
                        <>
                          <HrButton size="sm" variant="ghost" onClick={v.mExtend}>
                            {"Extend"}
                          </HrButton>
                        </>
                      ) : null}
                      {v.canLifecycle ? (
                        <>
                          <HrButton size="sm" variant="ghost" onClick={v.mNotice}>
                            {"Begin exit"}
                          </HrButton>
                        </>
                      ) : null}
                    </div>
                  </div>
                </>
              ) : null}
              <div style={{padding: "8px 12px 0", borderTop: "1px solid #f1f5f9", marginBottom: "-14px"}}>
                <HrTabs tabs={v.tabs} active={v.tab} onChange={v.setTab} />
              </div>
            </section>
            {v.isOverview ? (
              <>
                <HrTabPanel tabKey="overview">
                  <div style={{display: "flex", flexDirection: "column", gap: "12px"}}>
                    <div style={{display: "flex", flexWrap: "wrap", gap: "12px", alignItems: "stretch"}}>
                      <div style={{flex: "2 1 440px", minWidth: "0", background: "#fff", border: "1px solid #e2e8f0", borderRadius: "14px", padding: "14px 16px"}}>
                        <div style={{display: "flex", alignItems: "center", gap: "10px", marginBottom: "12px"}}>
                          <div style={{flex: "1", minWidth: "0"}}>
                            <div style={{fontSize: "15px", fontWeight: "700"}}>
                              {txt(v.jobTitle)}
                            </div>
                            <div style={{fontSize: "12.5px", color: "#64748b"}}>
                              {txt(v.jobSub)}
                            </div>
                          </div>
                          <HrStatusPill tone={v.tone}>
                            {txt(v.status)}
                          </HrStatusPill>
                        </div>
                        <div style={{display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(170px,1fr))", gap: "10px 16px"}}>
                          {arr(v.emp).map((f: any, $index: number) => (
                            <Fragment key={$index}>
                              <div style={{minWidth: "0", padding: "8px 10px", borderRadius: "10px", background: "#f8fafc"}}>
                                <div style={{fontSize: "11.5px", fontWeight: "600", color: "#64748b"}}>
                                  {txt(f?.l)}
                                </div>
                                <div style={{fontSize: "13.5px", fontWeight: "600", marginTop: "2px"}}>
                                  {txt(f?.v)}
                                </div>
                              </div>
                            </Fragment>
                          ))}
                          <div style={{minWidth: "0", padding: "6px 10px", borderRadius: "10px", background: "#f8fafc", cursor: "pointer"}} onClick={v.openMgr} className="dc-employee-workspace-2">
                            <div style={{fontSize: "11.5px", fontWeight: "600", color: "#64748b", marginBottom: "3px"}}>
                              {"Reports to"}
                            </div>
                            {v.hasMgr ? (
                              <>
                                <div style={{zoom: ".85"}}>
                                  <HrAvatar name={v.mgrName} sub={v.mgrSub} seed={v.mgrSeed} />
                                </div>
                              </>
                            ) : null}
                            {v.noMgr ? (
                              <>
                                <div style={{fontSize: "13.5px", fontWeight: "600", marginTop: "2px"}}>
                                  {"—"}
                                </div>
                              </>
                            ) : null}
                          </div>
                        </div>
                      </div>
                      <div style={{flex: "1 1 260px", minWidth: "0", background: "#fff", border: "1px solid #e2e8f0", borderRadius: "14px", padding: "14px 16px", display: "flex", flexDirection: "column", gap: "10px"}}>
                        <h2 style={{margin: "0", fontSize: "15px", fontWeight: "700"}}>
                          {"Account"}
                        </h2>
                        {v.accActive ? (
                          <>
                            <div style={{padding: "9px 11px", borderRadius: "10px", background: "#ecfdf5", border: "1px solid #a7f3d0", fontWeight: "700", color: "#0a5240"}}>
                              {"Account active ✓"}
                              <div style={{fontSize: "12px", fontWeight: "500", color: "#047857", marginTop: "1px"}}>
                                {txt(v.accActiveSub)}
                              </div>
                            </div>
                          </>
                        ) : null}
                        {v.accNone ? (
                          <>
                            <div style={{display: "flex", alignItems: "center", gap: "10px", flexWrap: "wrap", padding: "9px 11px", borderRadius: "10px", background: "#f8fafc", border: "1px solid #e2e8f0"}}>
                              <div style={{flex: "1 1 140px"}}>
                                <div style={{fontWeight: "700"}}>
                                  {txt(v.accTitle)}
                                </div>
                                <div style={{fontSize: "12px", color: "#64748b"}}>
                                  {txt(v.accSub)}
                                </div>
                              </div>
                              {v.canInvite ? (
                                <>
                                  <HrButton size="sm" variant={v.accVariant} onClick={v.invite}>
                                    {txt(v.accCta)}
                                  </HrButton>
                                </>
                              ) : null}
                            </div>
                          </>
                        ) : null}
                        <div style={{borderTop: "1px solid #f1f5f9", paddingTop: "10px"}}>
                          <div style={{display: "flex", alignItems: "center", gap: "8px", flexWrap: "wrap"}}>
                            <div style={{flex: "1 1 140px", fontSize: "13px", fontWeight: "600"}}>
                              {"Face enrollment"}
                              <div style={{fontSize: "12px", fontWeight: "500", color: "#64748b"}}>
                                {txt(v.faceSub)}
                              </div>
                            </div>
                            {txt(v.faceEnroll)}
                            {v.noAsk ? (
                              <>
                                {v.canFace ? (
                                  <>
                                    <HrButton size="sm" variant="ghost" onClick={v.askReset}>
                                      {"Reset face enrollment"}
                                    </HrButton>
                                  </>
                                ) : null}
                              </>
                            ) : null}
                          </div>
                          {v.resetAsk ? (
                            <>
                              <div style={{marginTop: "8px", padding: "10px 11px", borderRadius: "10px", background: "#fff7ed", border: "1px solid #fed7aa", fontSize: "12.5px", color: "#9a3412", lineHeight: "1.45"}}>
                                {"This clears stored face templates and unlocks any verification lockout."}
                                <div style={{display: "flex", gap: "6px", marginTop: "8px"}}>
                                  <HrButton size="sm" variant="danger" onClick={v.doReset}>
                                    {"Yes, reset"}
                                  </HrButton>
                                  <HrButton size="sm" variant="ghost" onClick={v.noReset}>
                                    {"Cancel"}
                                  </HrButton>
                                </div>
                              </div>
                            </>
                          ) : null}
                        </div>
                      </div>
                    </div>
                    <div style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "14px", overflow: "hidden"}}>
                      <div role="heading" aria-level={2} style={{padding: "11px 16px", fontSize: "14px", fontWeight: "700", borderBottom: "1px solid #f1f5f9"}}>
                        {"Needs attention "}
                        <span style={{fontSize: "12px", color: "#be123c", background: "#fff1f2", borderRadius: "99px", padding: "1px 7px", marginLeft: "4px"}}>
                          {txt(v.attCount)}
                        </span>
                      </div>
                      {arr(v.att).map((n: any, $index: number) => (
                        <Fragment key={$index}>
                          <div onClick={n?.on} role="button" style={{display: "flex", alignItems: "center", gap: "10px", padding: "9px 16px", borderTop: "1px solid #f8fafc", cursor: "pointer"}} className="dc-employee-workspace-3">
                            {n?.red ? (
                              <>
                                <span style={{width: "8px", height: "8px", borderRadius: "50%", background: "#e11d48", flexShrink: "0"}} />
                              </>
                            ) : null}
                            {n?.amber ? (
                              <>
                                <span style={{width: "8px", height: "8px", borderRadius: "50%", background: "#f59e0b", flexShrink: "0"}} />
                              </>
                            ) : null}
                            {n?.orange ? (
                              <>
                                <span style={{width: "8px", height: "8px", borderRadius: "50%", background: "#f97316", flexShrink: "0"}} />
                              </>
                            ) : null}
                            <div style={{flex: "1", minWidth: "0", fontWeight: "600"}}>
                              {txt(n?.title)}
                            </div>
                            <span style={{fontSize: "12.5px", fontWeight: "700", color: "#0f6e56", whiteSpace: "nowrap"}}>
                              {txt(n?.cta)}{" ›"}
                            </span>
                          </div>
                        </Fragment>
                      ))}
                      {v.noAtt ? (
                        <>
                          <div style={{padding: "10px 16px", borderTop: "1px solid #f8fafc", fontSize: "13px", color: "#64748b"}}>
                            {"Nothing needs attention right now."}
                          </div>
                        </>
                      ) : null}
                    </div>
                    <div style={{display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(170px,1fr))", gap: "10px"}}>
                      {arr(v.glance).map((g: any, $index: number) => (
                        <Fragment key={$index}>
                          <div onClick={g?.on} role="button" style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "14px", padding: "12px 14px", cursor: "pointer", display: "flex", flexDirection: "column", gap: "2px"}} className="dc-employee-workspace-4">
                            <div style={{fontSize: "12px", fontWeight: "600", color: "#64748b"}}>
                              {txt(g?.l)}
                            </div>
                            <div style={{fontSize: "19px", fontWeight: "800", letterSpacing: "-.02em"}}>
                              {txt(g?.v)}
                            </div>
                            <div style={{fontSize: "12px", color: "#64748b"}}>
                              {txt(g?.s)}
                            </div>
                          </div>
                        </Fragment>
                      ))}
                    </div>
                    {v.showOnb ? (
                      <>
                        <div style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "14px", padding: "14px 16px", display: "flex", flexDirection: "column", gap: "12px"}}>
                          <div>
                            <h2 style={{margin: "0", fontSize: "15px", fontWeight: "700"}}>
                              {"Onboarding record"}
                            </h2>
                            <div style={{fontSize: "12.5px", color: "#64748b"}}>
                              {txt(v.onbSub)}
                            </div>
                          </div>
                          {v.onbNote ? (
                            <>
                              <div style={{fontSize: "13px", color: "#64748b"}}>
                                {txt(v.onbNoteText)}
                              </div>
                            </>
                          ) : null}
                          {v.hasOnb ? (
                            <>
                              <div style={{display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(160px,1fr))", gap: "8px 16px"}}>
                                {arr(v.onb).map((f: any, $index: number) => (
                                  <Fragment key={$index}>
                                    <div>
                                      <div style={{fontSize: "11.5px", fontWeight: "600", color: "#64748b"}}>
                                        {txt(f?.l)}
                                      </div>
                                      <div style={{fontWeight: "600", marginTop: "1px"}}>
                                        {txt(f?.v)}
                                      </div>
                                    </div>
                                  </Fragment>
                                ))}
                              </div>
                            </>
                          ) : null}
                          {v.hasAssets ? (
                            <>
                              <div>
                                <div style={{fontSize: "13px", fontWeight: "700", marginBottom: "6px"}}>
                                  {"Recorded asset issues"}
                                </div>
                                <TableCard>
                                  <DataTable columns={v.assetCols} data={v.assets} keyField="id" />
                                </TableCard>
                              </div>
                            </>
                          ) : null}
                          {v.hasPolicies ? (
                            <>
                              <div>
                                <div style={{fontSize: "13px", fontWeight: "700", marginBottom: "6px"}}>
                                  {"Policies selected for the hire"}
                                </div>
                                <div style={{display: "flex", flexWrap: "wrap", gap: "6px"}}>
                                  {arr(v.policies).map((p: any, $index: number) => (
                                    <Fragment key={$index}>
                                      <span style={{padding: "4px 10px", borderRadius: "8px", background: "#f1f5f9", fontSize: "12.5px", fontWeight: "600", color: "#334155"}}>
                                        {txt(p)}
                                      </span>
                                    </Fragment>
                                  ))}
                                </div>
                              </div>
                            </>
                          ) : null}
                          {v.hasChecklists ? (
                            <>
                              <div style={{display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(260px,1fr))", gap: "12px"}}>
                                {arr(v.checklists).map((c: any, $index: number) => (
                                  <Fragment key={$index}>
                                    <div style={{border: "1px solid #f1f5f9", borderRadius: "12px", overflow: "hidden"}}>
                                      <div style={{padding: "8px 12px", background: "#f8fafc", fontSize: "13px", fontWeight: "700"}}>
                                        {txt(c?.title)}
                                      </div>
                                      {arr(c?.rows).map((r: any, $index: number) => (
                                        <Fragment key={$index}>
                                          <div style={{display: "flex", alignItems: "center", gap: "8px", padding: "7px 12px", borderTop: "1px solid #f1f5f9"}}>
                                            <div style={{flex: "1", fontSize: "13px"}}>
                                              {txt(r?.l)}
                                            </div>
                                            <HrStatusPill tone={r?.t}>
                                              {txt(r?.s)}
                                            </HrStatusPill>
                                          </div>
                                        </Fragment>
                                      ))}
                                    </div>
                                  </Fragment>
                                ))}
                              </div>
                            </>
                          ) : null}
                        </div>
                      </>
                    ) : null}
                  </div>
                </HrTabPanel>
              </>
            ) : null}
            {v.isOther ? (
              <>
                <HrTabPanel tabKey={v.tab}>
                  {v.otherPlaceholder ? (
                    <>
                      <div style={{background: "#fff", border: "1.5px dashed #cbd5e1", borderRadius: "14px", padding: "18px", display: "flex", flexWrap: "wrap", alignItems: "center", gap: "10px 16px"}}>
                        <div style={{flex: "1 1 260px"}}>
                          <div style={{fontSize: "15px", fontWeight: "700"}}>
                            {txt(v.otherLabel)}
                          </div>
                          <div style={{fontSize: "13px", color: "#64748b", marginTop: "2px"}}>
                            {txt(v.otherNote)}
                          </div>
                        </div>
                        <HrButton size="sm" variant="ghost" onClick={v.otherAction}>
                          {txt(v.otherCta)}
                        </HrButton>
                      </div>
                    </>
                  ) : null}
                  {txt(v.otherContent)}
                </HrTabPanel>
              </>
            ) : null}
          </>
        ) : null}
        {v.dShift ? (
          <>
            <HrDrawer title="Change employee shift" onClose={v.closeD} footer={v.shiftFooter}>
              <div style={{display: "flex", flexDirection: "column", gap: "16px", fontFamily: "'Plus Jakarta Sans',sans-serif", fontSize: "13.5px"}}>
                <div style={{padding: "10px 12px", borderRadius: "10px", background: "#f8fafc", border: "1px solid #e2e8f0"}}>
                  <div style={{fontSize: "11.5px", fontWeight: "700", color: "#64748b", textTransform: "uppercase", letterSpacing: ".06em"}}>
                    {"Current shift"}
                  </div>
                  <div style={{fontWeight: "700", marginTop: "2px"}}>
                    {txt(v.curShift)}
                  </div>
                  {v.hasUpcoming ? (
                    <>
                      <div style={{fontSize: "12.5px", color: "#64748b", marginTop: "2px"}}>
                        {txt(v.upcoming)}
                      </div>
                    </>
                  ) : null}
                </div>
                <div style={{display: "flex", flexDirection: "column", gap: "6px"}}>
                  <Label>
                    {"New shift"}
                  </Label>
                  <HrSelect value={v.newShift} options={v.shiftOpts} onChange={v.setShift} />
                </div>
                <div style={{display: "flex", flexDirection: "column", gap: "6px"}}>
                  <Label>
                    {"Effective from"}
                  </Label>
                  <DateField value={v.eff} min={v.effMin} onChange={v.setEff} />
                  <div style={{fontSize: "12.5px", color: "#64748b"}}>
                    {txt(v.effHint)}
                  </div>
                </div>
              </div>
            </HrDrawer>
          </>
        ) : null}
        {v.dEdit ? (
          <>
            <HrDrawer title="Edit employee" onClose={v.closeD} footer={v.editFooter}>
              <div style={{display: "flex", flexDirection: "column", gap: "14px", fontFamily: "'Plus Jakarta Sans',sans-serif", fontSize: "13.5px"}}>
                <div style={{display: "flex", gap: "8px"}}>
                  {arr(v.steps).map((s: any, $index: number) => (
                    <Fragment key={$index}>
                      {s?.on ? (
                        <>
                          <div style={{flex: "1", padding: "8px 10px", borderRadius: "10px", background: "#ecfdf5", border: "1px solid #6ee7b7", fontWeight: "700", color: "#0a5240"}}>
                            {txt(s?.l)}
                          </div>
                        </>
                      ) : null}
                      {s?.off ? (
                        <>
                          <div style={{flex: "1", padding: "8px 10px", borderRadius: "10px", background: "#f8fafc", border: "1px solid #e2e8f0", fontWeight: "600", color: "#64748b"}}>
                            {txt(s?.l)}
                          </div>
                        </>
                      ) : null}
                    </Fragment>
                  ))}
                </div>
                {arr(v.editFields).map((f: any, $index: number) => (
                  <Fragment key={$index}>
                    <div style={{display: "flex", flexDirection: "column", gap: "6px"}}>
                      <Label>
                        {txt(f?.l)}
                      </Label>
                      {f?.isSelect ? (
                        <>
                          <HrSelect value={f?.v} options={f?.opts} onChange={f?.onSel} />
                        </>
                      ) : null}
                      {f?.isInput ? (
                        <>
                          {f?.type === 'date' ? <DateField value={f?.v} disabled={f?.off} onChange={f?.on} /> : <Input type={f?.type} value={f?.v} placeholder={f?.ph} disabled={f?.off} onChange={f?.on} />}
                        </>
                      ) : null}
                      {f?.hasErr ? (
                        <>
                          <div style={{fontSize: "12.5px", fontWeight: "600", color: "#be123c"}}>
                            {txt(f?.err)}
                          </div>
                        </>
                      ) : null}
                      {f?.hasHint ? (
                        <>
                          <div style={{fontSize: "12px", color: "#64748b"}}>
                            {txt(f?.hint)}
                          </div>
                        </>
                      ) : null}
                    </div>
                  </Fragment>
                ))}
              </div>
            </HrDrawer>
          </>
        ) : null}
        <Modal open={v.mOpen} onOpenChange={v.mChange} title={v.mTitle} description={v.mDesc} size="sm">
          <div style={{display: "flex", flexDirection: "column", gap: "12px", marginTop: "14px", fontFamily: "'Plus Jakarta Sans',sans-serif"}}>
            {arr(v.mFields).map((f: any, $index: number) => (
              <Fragment key={$index}>
                <div style={{display: "flex", flexDirection: "column", gap: "6px"}}>
                  <Label>
                    {txt(f?.l)}
                  </Label>
                  {f?.isSelect ? (
                    <>
                      <HrSelect value={f?.v} options={f?.opts} onChange={f?.onSel} />
                    </>
                  ) : null}
                  {f?.isInput ? (
                    <>
                      {f?.type === 'date' ? <DateField value={f?.v} onChange={f?.on} /> : <Input type={f?.type} value={f?.v} maxLength={f?.max} placeholder={f?.ph} onChange={f?.on} />}
                    </>
                  ) : null}
                  {f?.hasErr ? (
                    <>
                      <div style={{fontSize: "12.5px", fontWeight: "600", color: "#be123c"}}>
                        {txt(f?.err)}
                      </div>
                    </>
                  ) : null}
                  {f?.hasHint ? (
                    <>
                      <div style={{fontSize: "12px", color: "#64748b"}}>
                        {txt(f?.hint)}
                      </div>
                    </>
                  ) : null}
                </div>
              </Fragment>
            ))}
            <div style={{display: "flex", justifyContent: "flex-end", gap: "8px", marginTop: "4px"}}>
              <HrButton variant="ghost" onClick={v.mClose}>
                {"Cancel"}
              </HrButton>
              <HrButton variant={v.mVariant} disabled={v.mBusy} onClick={v.mOk}>
                {txt(v.mCta)}
              </HrButton>
            </div>
          </div>
        </Modal>
        {v.hasToast ? (
          <>
            <div role="status" style={{position: "fixed", left: "50%", bottom: "24px", transform: "translateX(-50%)", zIndex: "1200", background: "#0f172a", color: "#fff", borderRadius: "12px", padding: "10px 16px", fontSize: "13.5px", fontWeight: "500", boxShadow: "0 18px 36px -12px rgba(15,23,42,.45)", maxWidth: "calc(100vw - 32px)"}}>
              {v.toastOk ? (
                <>
                  <span style={{color: "#34d399", fontWeight: "800", marginRight: "8px"}}>
                    {"✓"}
                  </span>
                </>
              ) : null}
              {v.toastErr ? (
                <>
                  <span style={{color: "#fb7185", fontWeight: "800", marginRight: "8px"}}>
                    {"!"}
                  </span>
                </>
              ) : null}
              {txt(v.toast)}
            </div>
          </>
        ) : null}
      </div>
    </>
  )
}
