// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component NewRunModal.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { Fragment } from 'react'
import { HrButton, HrSelect } from '@/shared/components/hr'
import { Modal } from '@unifiedtree/ui-kit'
import { arr, txt } from './dc-runtime'
import './NewRunModal.view.css'

export function NewRunModalView({ v }: { v: any }) {
  return (
    <>
      <Modal open={v.isOpen} onOpenChange={v.onOpenChange} title="New payroll run" description="Choose the company and month to pay. You’ll process it on the next screen." size="md" preventOutsideClose={v.busy}>
        <div style={{display: "grid", gap: "18px", fontFamily: "Inter,-apple-system,sans-serif", color: "#0f172a"}}>
          <div style={{display: "grid", gap: "6px"}}>
            <span style={{fontSize: "13px", fontWeight: "600"}}>
              {"Company"}
            </span>
            <HrSelect value={v.company} onChange={v.setCompany} options={v.companyOptions} placeholder="Select a company" disabled={v.busy} />
            {v.single ? (
              <>
                <span style={{fontSize: "12px", color: "#64748b"}}>
                  {"Selected for you — it’s the only company in this workspace."}
                </span>
              </>
            ) : null}
          </div>
          <div style={{display: "grid", gap: "10px"}}>
            <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: "8px 12px"}}>
              <span style={{fontSize: "13px", fontWeight: "600"}}>
                {"Month"}
              </span>
              <div style={{display: "flex", alignItems: "center", gap: "8px"}}>
                <span style={{fontSize: "12.5px", fontWeight: "600", color: "#475569"}}>
                  {"Year"}
                </span>
                <div style={{width: "104px"}}>
                  <HrSelect value={v.year} onChange={v.setYear} options={v.yearOptions} size="sm" disabled={v.busy} />
                </div>
              </div>
            </div>
            <div role="group" aria-label="Month" style={{display: "grid", gridTemplateColumns: "repeat(4,minmax(0,1fr))", gap: "8px"}}>
              {arr(v.months).map((m: any, $index: number) => (
                <Fragment key={$index}>
                  <HrButton {...(m?.btn || {})}>
                    <span style={{fontSize: "13.5px", fontWeight: "700"}}>
                      {txt(m?.label)}
                    </span>
                    {m?.subSel ? (
                      <>
                        <span style={{fontSize: "10.5px", fontWeight: "600", color: "#ffffff"}}>
                          {txt(m?.sub)}
                        </span>
                      </>
                    ) : null}
                    {m?.subNext ? (
                      <>
                        <span style={{fontSize: "10.5px", fontWeight: "700", color: "#0f6e56"}}>
                          {txt(m?.sub)}
                        </span>
                      </>
                    ) : null}
                    {m?.subPlain ? (
                      <>
                        <span style={{fontSize: "10.5px", fontWeight: "600", color: "#64748b"}}>
                          {txt(m?.sub)}
                        </span>
                      </>
                    ) : null}
                  </HrButton>
                </Fragment>
              ))}
            </div>
          </div>
          {v.hintNeutral ? (
            <>
              <p aria-live="polite" style={{margin: "0", display: "flex", alignItems: "center", gap: "8px", padding: "10px 12px", borderRadius: "12px", background: "#f8fafc", border: "1px solid #e2e8f0", fontSize: "13px", color: "#475569"}}>
                <span style={{display: "inline-flex", color: "#64748b"}}>
                  {txt(v.icInfo)}
                </span>
                {txt(v.neutralText)}
              </p>
            </>
          ) : null}
          {v.hintOk ? (
            <>
              <p aria-live="polite" style={{margin: "0", display: "flex", alignItems: "center", gap: "8px", padding: "10px 12px", borderRadius: "12px", background: "#ecfdf5", border: "1px solid #a7f3d0", fontSize: "13px", fontWeight: "500", color: "#065f46"}}>
                <span style={{display: "inline-flex", color: "#0f6e56"}}>
                  {txt(v.icOk)}
                </span>
                {txt(v.okText)}
              </p>
            </>
          ) : null}
          {v.hintDup ? (
            <>
              <p aria-live="polite" style={{margin: "0", display: "flex", flexWrap: "wrap", alignItems: "center", gap: "6px 8px", padding: "10px 12px", borderRadius: "12px", background: "#fffbeb", border: "1px solid #fde68a", fontSize: "13px", color: "#92400e"}}>
                <span style={{display: "inline-flex"}}>
                  {txt(v.icWarn)}
                </span>
                <span>
                  {txt(v.dupText)}
                </span>
                <button type="button" onClick={v.openDup} style={{border: "0", background: "none", padding: "0", font: "inherit", fontWeight: "700", color: "#0f6e56", textDecoration: "underline", textUnderlineOffset: "3px", cursor: "pointer"}}>
                  {"Open it"}
                </button>
              </p>
            </>
          ) : null}
          <div style={{display: "flex", flexWrap: "wrap", justifyContent: "flex-end", gap: "10px", paddingTop: "14px", borderTop: "1px solid #eef2f1"}}>
            <HrButton variant="ghost" onClick={v.cancel} disabled={v.busy}>
              {"Cancel"}
            </HrButton>
            <HrButton {...(v.createBtn || {})}>
              {txt(v.createInner)}
            </HrButton>
          </div>
        </div>
      </Modal>
    </>
  )
}
