// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component PayBank.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { Fragment } from 'react'
import { HrButton, HrDrawer, HrStatusPill, TableCard } from '@/shared/components/hr'
import { DataTable } from '@/shared/components/DataTable'
import { EmptyState } from '@/shared/components/EmptyState'
import { SkeletonBlock } from '@/shared/components/SkeletonCard'
import { Modal } from '@unifiedtree/ui-kit'
import { arr, txt } from './dc-runtime'
import './PayBank.view.css'

export function PayBankView({ v }: { v: any }) {
  return (
    <>
      <div style={{display: "grid", gridTemplateColumns: "minmax(0,1fr)", gap: "16px", minWidth: "0", fontFamily: "Inter,-apple-system,sans-serif", color: "#0f172a"}}>
        <header style={{position: "relative", overflow: "hidden", background: "#fff", border: "1px solid #e2e8f0", borderRadius: "20px", boxShadow: "0 1px 2px rgba(15,23,42,.04)"}}>
          <span aria-hidden="true" style={{position: "absolute", right: "-60px", top: "-150px", width: "380px", height: "320px", borderRadius: "999px", background: "rgba(16,185,129,.10)", filter: "blur(60px)", pointerEvents: "none"}} />
          <div style={{position: "relative", display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: "16px 24px", padding: "clamp(18px,2.4vw,26px) clamp(18px,2.6vw,30px)"}}>
            <div style={{flex: "999 1 300px", minWidth: "0", display: "grid", gap: "6px"}}>
              <p style={{margin: "0", fontSize: "12.5px", fontWeight: "700", letterSpacing: ".08em", textTransform: "uppercase", color: "#0f6e56"}}>
                {"Payroll / Disbursement"}
              </p>
              <h1 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "clamp(22px,2.4vw,28px)", fontWeight: "800", letterSpacing: "-.02em", lineHeight: "1.2"}}>
                {"Bank Disbursement"}
              </h1>
              <p style={{margin: "0", fontSize: "14px", lineHeight: "1.5", color: "#475569", textWrap: "pretty"}}>
                {"Download the NEFT/RTGS files for your corporate banking portal, then confirm each transfer."}
              </p>
            </div>
            <div style={{flex: "1 1 auto", display: "flex", flexWrap: "wrap", justifyContent: "flex-end", gap: "8px"}}>
              <HrButton variant="ghost" onClick={v.openProfiles} data-tip="Opens bank profile setup">
                {txt(v.icBankSm)}{" Bank profiles"}
              </HrButton>
              <HrButton variant="ghost" onClick={v.openRun} data-tip={v.runTip}>
                {txt(v.icRun)}{" "}{txt(v.runLabel)}{" run"}
              </HrButton>
            </div>
          </div>
        </header>
        {v.isLoading ? (
          <>
            <div role="status" aria-label="Loading" style={{display: "grid", gap: "10px"}}>
              <SkeletonBlock {...(v.skA || {})} />
              <SkeletonBlock {...(v.skB || {})} />
            </div>
          </>
        ) : null}
        {v.isError ? (
          <>
            <div style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px"}}>
              <EmptyState icon={v.errIcon} title="Couldn’t load bank files" description="Something went wrong on our side and nothing was changed. Try again in a moment." action={v.retry} />
            </div>
          </>
        ) : null}
        {v.isEmpty ? (
          <>
            <div style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px"}}>
              <EmptyState icon={v.emptyIcon} title="No bank files yet" description="Files appear here after you lock a payroll run and prepare its disbursement." action={v.runAction} />
            </div>
          </>
        ) : null}
        {v.live ? (
          <>
            {v.allDone ? (
              <>
                <section role="status" style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "10px 14px", padding: "14px 16px", border: "1px solid #a7f3d0", borderRadius: "16px", background: "#ecfdf5"}}>
                  <span style={{display: "inline-flex", color: "#0f6e56"}}>
                    {txt(v.icOk)}
                  </span>
                  <span style={{flex: "1 1 260px", fontSize: "13.5px", lineHeight: "1.5", color: "#065f46"}}>
                    {txt(v.allDoneText)}
                  </span>
                  <HrButton size="sm" onClick={v.openRun}>
                    {"Open "}{txt(v.runLabel)}{" run"}
                  </HrButton>
                </section>
              </>
            ) : null}
            <section style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px", boxShadow: "0 1px 2px rgba(15,23,42,.04)", padding: "20px 22px", display: "grid", gap: "12px"}}>
              <div style={{display: "flex", flexWrap: "wrap", alignItems: "baseline", justifyContent: "space-between", gap: "4px 12px"}}>
                <h2 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "16px", fontWeight: "700"}}>
                  {txt(v.runLabel)}{" · "}{txt(v.totalLabel)}
                </h2>
                <span style={{fontSize: "13px", color: "#64748b"}}>
                  {txt(v.runNote)}
                </span>
              </div>
              {arr(v.batches).map((b: any, $index: number) => (
                <Fragment key={$index}>
                  <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "10px 16px", padding: "14px 16px", border: "1px solid #e2e8f0", borderRadius: "14px"}}>
                    <span style={{flex: "0 0 40px", width: "40px", height: "40px", borderRadius: "11px", background: "#f8fafc", border: "1px solid #e2e8f0", color: "#334155", display: "inline-flex", alignItems: "center", justifyContent: "center"}}>
                      {txt(v.icBank)}
                    </span>
                    <div style={{flex: "1 1 200px", minWidth: "0", display: "grid", gap: "2px"}}>
                      <strong style={{fontFamily: "'JetBrains Mono',ui-monospace,monospace", fontSize: "13px"}}>
                        {txt(b?.id)}
                      </strong>
                      <span style={{fontSize: "12.5px", color: "#64748b"}}>
                        {txt(b?.bank)}{" · "}{txt(b?.count)}{" employees"}
                      </span>
                    </div>
                    <strong style={{flex: "0 0 auto", fontSize: "15px", fontVariantNumeric: "tabular-nums"}}>
                      {txt(b?.amountL)}
                    </strong>
                    <HrStatusPill tone={b?.tone}>
                      {txt(b?.statusLabel)}
                    </HrStatusPill>
                    <div style={{display: "flex", flexWrap: "wrap", gap: "6px", marginLeft: "auto"}}>
                      <HrButton size="sm" variant="ghost" onClick={b?.onView} data-tip="Shows who is in this file">
                        {"View"}
                      </HrButton>
                      {b?.canDownload ? (
                        <>
                          <HrButton size="sm" variant="ghost" onClick={b?.onDownload} data-tip={b?.fileTip}>
                            {txt(v.icDownload)}{" Download"}
                          </HrButton>
                        </>
                      ) : null}
                      {b?.canConfirm ? (
                        <>
                          <HrButton size="sm" onClick={b?.onConfirm} data-tip="Opens Confirm transfer?">
                            {txt(v.icCheck)}{" Mark transferred"}
                          </HrButton>
                        </>
                      ) : null}
                      {b?.needsRun ? (
                        <>
                          <HrButton size="sm" onClick={v.openRun} data-tip={v.runTip}>
                            {txt(b?.runCta)}
                          </HrButton>
                        </>
                      ) : null}
                    </div>
                  </div>
                </Fragment>
              ))}
            </section>
            <section style={{display: "grid", gap: "10px"}}>
              <h2 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "16px", fontWeight: "700"}}>
                {"Past files"}
              </h2>
              <TableCard>
                <DataTable columns={v.columns} data={v.history} keyField="id" emptyMessage="No past files." />
              </TableCard>
            </section>
          </>
        ) : null}
      </div>
      {v.viewOpen ? (
        <>
          <HrDrawer title={v.vTitle} onClose={v.closeView} width="max-w-md">
            <div style={{display: "grid", gap: "12px", fontFamily: "Inter,-apple-system,sans-serif", color: "#0f172a"}}>
              <p style={{margin: "0", fontSize: "13px", color: "#64748b"}}>
                {txt(v.vSub)}
              </p>
              {arr(v.people).map((e: any, $index: number) => (
                <Fragment key={$index}>
                  <div style={{display: "flex", alignItems: "center", gap: "10px", padding: "10px 0", borderBottom: "1px solid #f1f5f9"}}>
                    <div style={{flex: "1", minWidth: "0", display: "grid", gap: "1px"}}>
                      <strong style={{fontSize: "13.5px"}}>
                        {txt(e?.name)}
                      </strong>
                      <span style={{fontSize: "12px", color: "#64748b"}}>
                        <span style={{fontFamily: "'JetBrains Mono',ui-monospace,monospace"}}>
                          {txt(e?.code)}
                        </span>
                        {" · A/c ••••"}{txt(e?.acct)}
                      </span>
                    </div>
                    <strong style={{fontSize: "13.5px", fontVariantNumeric: "tabular-nums"}}>
                      {txt(e?.netL)}
                    </strong>
                  </div>
                </Fragment>
              ))}
              <p style={{margin: "0", fontSize: "12.5px", color: "#64748b"}}>
                {txt(v.moreLabel)}
              </p>
            </div>
          </HrDrawer>
        </>
      ) : null}
      <Modal open={v.confirmOpen} onOpenChange={v.setConfirmOpen} title={v.cTitle} description={v.cDesc} size="sm">
        {" "}
        <label style={{display: "grid", gap: "6px", marginTop: "4px", fontSize: "13px", fontWeight: "600", color: "#0f172a", fontFamily: "Inter,-apple-system,sans-serif"}}>
          {"Bank reference (UTR) *"}
          <input value={v.utr} onChange={v.setUtr} maxLength={120} placeholder="e.g. HDFCN52026092012345" style={{font: "inherit", fontWeight: "400", padding: "9px 12px", border: "1px solid #cbd5e1", borderRadius: "10px", outline: "none"}} className="dc-pay-bank-0" />
          <span style={{fontSize: "12px", fontWeight: "400", color: "#64748b"}}>
            {"From your bank’s transfer confirmation. Saved with the payment."}
          </span>
        </label>
        {" "}
        <div style={{display: "flex", flexWrap: "wrap", justifyContent: "flex-end", gap: "8px", marginTop: "8px"}}>
          <HrButton variant="ghost" onClick={v.closeConfirm}>
            {"Cancel"}
          </HrButton>
          <HrButton onClick={v.doConfirm} disabled={v.confirmOff}>
            {"Confirm transfer"}
          </HrButton>
        </div>
      </Modal>
    </>
  )
}
