// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component PayPli.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { Fragment } from 'react'
import { HrButton, HrDrawer, TableCard } from '@/shared/components/hr'
import { DataTable } from '@/shared/components/DataTable'
import { EmptyState } from '@/shared/components/EmptyState'
import { SkeletonBlock } from '@/shared/components/SkeletonCard'
import { Modal } from '@unifiedtree/ui-kit'
import { arr, txt } from './dc-runtime'
import './PayPli.view.css'

export function PayPliView({ v }: { v: any }) {
  return (
    <>
      <div style={{display: "grid", gridTemplateColumns: "minmax(0,1fr)", gap: "16px", minWidth: "0", fontFamily: "Inter,-apple-system,sans-serif", color: "#0f172a"}}>
        <header style={{position: "relative", overflow: "hidden", background: "#fff", border: "1px solid #e2e8f0", borderRadius: "20px", boxShadow: "0 1px 2px rgba(15,23,42,.04)"}}>
          <span aria-hidden="true" style={{position: "absolute", right: "-60px", top: "-150px", width: "380px", height: "320px", borderRadius: "999px", background: "rgba(16,185,129,.10)", filter: "blur(60px)", pointerEvents: "none"}} />
          <div style={{position: "relative", display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: "16px 24px", padding: "clamp(18px,2.4vw,26px) clamp(18px,2.6vw,30px)"}}>
            <div style={{flex: "999 1 300px", minWidth: "0", display: "grid", gap: "6px"}}>
              <p style={{margin: "0", fontSize: "12.5px", fontWeight: "700", letterSpacing: ".08em", textTransform: "uppercase", color: "#0f6e56"}}>
                {"Payroll / Incentives"}
              </p>
              <h1 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "clamp(22px,2.4vw,28px)", fontWeight: "800", letterSpacing: "-.02em", lineHeight: "1.2"}}>
                {"Production-Linked Incentive (PLI)"}
              </h1>
              <p style={{margin: "0", fontSize: "14px", lineHeight: "1.5", color: "#475569", textWrap: "pretty"}}>
                {txt(v.monthName)}{" targets and bonuses by team."}
              </p>
            </div>
            <div style={{flex: "1 1 auto", display: "flex", flexWrap: "wrap", justifyContent: "flex-end", gap: "8px"}}>
              <HrButton onClick={v.openTargets} data-tip="Opens Set monthly targets">
                {txt(v.icTarget)}{" Set monthly targets"}
              </HrButton>
            </div>
          </div>
        </header>
        {v.isLoading ? (
          <>
            <div role="status" aria-label="Loading" style={{display: "grid", gap: "10px"}}>
              <SkeletonBlock {...(v.skA || {})} />
              <SkeletonBlock {...(v.skB || {})} />
            </div>
          </>
        ) : null}
        {v.isError ? (
          <>
            <div style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px"}}>
              <EmptyState icon={v.errIcon} title="Couldn’t load incentives" description="Something went wrong on our side and nothing was changed. Try again in a moment." action={v.retry} />
            </div>
          </>
        ) : null}
        {v.isEmpty ? (
          <>
            <div style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px"}}>
              <EmptyState icon={v.emptyIcon} title="No incentive targets yet" description="Set a monthly production target for a team to start paying PLI bonuses." action={v.targetsAction} />
            </div>
          </>
        ) : null}
        {v.live ? (
          <>
            <p style={{margin: "0", display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px 12px", padding: "12px 16px", borderRadius: "14px", background: "#ecfdf5", border: "1px solid #a7f3d0", fontSize: "13.5px", lineHeight: "1.5", color: "#065f46"}}>
              <span style={{display: "inline-flex", color: "#0f6e56"}}>
                {txt(v.icInfo)}
              </span>
              <span style={{flex: "1 1 260px"}}>
                {txt(v.pliLead)}{" "}
                <strong>
                  {txt(v.totalLabel)}
                </strong>
                {" for "}{txt(v.paidPeople)}{" people."}
              </span>
              <button type="button" onClick={v.openRun} data-tip={v.runTip} style={{padding: "0", border: "0", background: "none", font: "inherit", fontWeight: "700", color: "#0f6e56", cursor: "pointer"}} className="dc-pay-pli-0">
                {txt(v.pliLink)}
              </button>
            </p>
            <TableCard search={v.search} actions={v.actions}>
              {v.isDesktop ? (
                <>
                  <DataTable columns={v.columns} data={v.rows} keyField="id" emptyMessage="No teams match." onRowClick={v.openRow} />
                </>
              ) : null}
              {v.isMobile ? (
                <>
                  <div style={{display: "grid", gap: "8px", padding: "12px"}}>
                    {arr(v.rows).map((r: any, $index: number) => (
                      <Fragment key={$index}>
                        <article style={{display: "grid", gap: "10px", padding: "12px 14px", border: "1px solid #e2e8f0", borderRadius: "14px"}}>
                          <div style={{display: "flex", alignItems: "center", justifyContent: "space-between", gap: "8px"}}>
                            <strong style={{fontSize: "14px"}}>
                              {txt(r?.team)}
                            </strong>
                            <HrButton size="sm" variant="ghost" onClick={r?.onEdit}>
                              {"Edit"}
                            </HrButton>
                          </div>
                          <dl style={{margin: "0", display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: "6px", fontSize: "12px"}}>
                            <div>
                              <dt style={{color: "#64748b"}}>
                                {"Target"}
                              </dt>
                              <dd style={{margin: "2px 0 0", fontWeight: "600"}}>
                                {txt(r?.targetL)}
                              </dd>
                            </div>
                            <div>
                              <dt style={{color: "#64748b"}}>
                                {"Achieved"}
                              </dt>
                              <dd style={{margin: "2px 0 0", fontWeight: "700"}}>
                                {txt(r?.actualL)}
                              </dd>
                            </div>
                            <div>
                              <dt style={{color: "#64748b"}}>
                                {"Bonus pool"}
                              </dt>
                              <dd style={{margin: "2px 0 0", fontWeight: "800", color: "#0f6e56"}}>
                                {txt(r?.poolL)}
                              </dd>
                            </div>
                          </dl>
                        </article>
                      </Fragment>
                    ))}
                  </div>
                </>
              ) : null}
            </TableCard>
          </>
        ) : null}
      </div>
      {v.editOpen ? (
        <>
          <HrDrawer title={v.eTitle} onClose={v.closeEdit} footer={v.eFooter} width="max-w-md">
            <div style={{display: "grid", gap: "14px", fontFamily: "Inter,-apple-system,sans-serif", color: "#0f172a"}}>
              <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
                {"Production target (units) *"}
                <input type="number" min="1" value={v.fTarget} onChange={v.setTarget} style={{font: "inherit", fontWeight: "500", height: "42px", padding: "0 12px", boxSizing: "border-box", border: "1px solid #cbd5e1", borderRadius: "10px", outline: "none"}} className="dc-pay-pli-1" />
              </label>
              <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
                {"Actual achieved (units) *"}
                <input type="number" min="0" value={v.fActual} onChange={v.setActual} style={{font: "inherit", fontWeight: "500", height: "42px", padding: "0 12px", boxSizing: "border-box", border: "1px solid #cbd5e1", borderRadius: "10px", outline: "none"}} className="dc-pay-pli-1" />
              </label>
              <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
                {"Bonus per person when target is met (₹) *"}
                <input type="number" min="0" step="100" value={v.fPer} onChange={v.setPer} style={{font: "inherit", fontWeight: "500", height: "42px", padding: "0 12px", boxSizing: "border-box", border: "1px solid #cbd5e1", borderRadius: "10px", outline: "none"}} className="dc-pay-pli-1" />
              </label>
              <div style={{display: "grid", gap: "4px", padding: "14px 16px", borderRadius: "14px", background: "#ecfdf5", border: "1px solid #a7f3d0"}}>
                <span style={{fontSize: "12.5px", color: "#047857"}}>
                  {txt(v.ePreviewNote)}
                </span>
                <strong style={{fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "22px", fontWeight: "800", color: "#0f6e56", fontVariantNumeric: "tabular-nums"}}>
                  {txt(v.ePool)}
                </strong>
              </div>
            </div>
          </HrDrawer>
        </>
      ) : null}
      <Modal open={v.targetsOpen} onOpenChange={v.setTargetsOpen} title="Set monthly targets" description={v.targetsDesc} size="sm">
        <div style={{display: "grid", gap: "12px", marginTop: "4px", fontFamily: "Inter,-apple-system,sans-serif", color: "#0f172a"}}>
          {arr(v.targetRows).map((t: any, $index: number) => (
            <Fragment key={$index}>
              <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
                {txt(t?.team)}{" (units)"}
                <input type="number" min="1" value={t?.value} onChange={t?.onChange} style={{font: "inherit", fontWeight: "500", height: "42px", padding: "0 12px", boxSizing: "border-box", border: "1px solid #cbd5e1", borderRadius: "10px", outline: "none"}} className="dc-pay-pli-1" />
              </label>
            </Fragment>
          ))}
          <div style={{display: "flex", flexWrap: "wrap", justifyContent: "flex-end", gap: "8px", marginTop: "4px"}}>
            <HrButton variant="ghost" onClick={v.closeTargets}>
              {"Cancel"}
            </HrButton>
            <HrButton onClick={v.saveTargets}>
              {"Save targets"}
            </HrButton>
          </div>
        </div>
      </Modal>
    </>
  )
}
