// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component PayrollRunPage.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { Fragment } from 'react'
import { HrButton, HrStatCard, HrStatusPill, HrTabs } from '@/shared/components/hr'
import { EmptyState } from '@/shared/components/EmptyState'
import { SkeletonBlock } from '@/shared/components/SkeletonCard'
import { Modal } from '@unifiedtree/ui-kit'
import { arr, txt } from './dc-runtime'
import { PayrollEmployees } from './PayrollEmployees'
import { PayrollOverview } from './PayrollOverview'
import { PayslipDrawer } from './PayslipDrawer'
import { ProcessSteps } from './ProcessSteps'
import './PayrollRunPage.view.css'

export function PayrollRunPageView({ v }: { v: any }) {
  return (
    <>
      <div style={{display: "grid", gridTemplateColumns: "minmax(0,1fr)", gap: "16px", minWidth: "0", fontFamily: "Inter,-apple-system,sans-serif", color: "#0f172a"}}>
        <header style={{position: "relative", overflow: "hidden", background: "#fff", border: "1px solid #e2e8f0", borderRadius: "20px", boxShadow: "0 1px 2px rgba(15,23,42,.04)"}}>
          <span aria-hidden="true" style={{position: "absolute", right: "-60px", top: "-150px", width: "380px", height: "320px", borderRadius: "999px", background: "rgba(16,185,129,.10)", filter: "blur(60px)", pointerEvents: "none"}} />
          <div style={{position: "relative", display: "grid", gridTemplateColumns: "minmax(0,1fr)", gap: "20px", padding: "clamp(18px,2.4vw,28px) clamp(18px,2.6vw,32px)"}}>
            <div style={{display: "flex", flexWrap: "wrap", alignItems: "flex-start", justifyContent: "space-between", gap: "16px 24px", minWidth: "0"}}>
              <div style={{flex: "999 1 320px", minWidth: "0", display: "grid", gap: "6px"}}>
                <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px"}}>
                  <button type="button" onClick={v.goRuns} aria-label="Back to all payroll runs" data-tip="Back to all payroll runs" style={{width: "28px", height: "28px", display: "inline-flex", alignItems: "center", justifyContent: "center", border: "1px solid #e2e8f0", borderRadius: "8px", background: "#fff", color: "#0f6e56", cursor: "pointer"}} className="dc-payroll-run-page-0">
                    {txt(v.icBack)}
                  </button>
                  <p style={{margin: "0", display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px", fontSize: "12.5px", fontWeight: "700", letterSpacing: ".08em", textTransform: "uppercase", color: "#0f6e56"}}>
                    <span>
                      {"Payroll"}
                    </span>
                    <span aria-hidden="true" style={{color: "#94a3b8"}}>
                      {"/"}
                    </span>
                    <button type="button" onClick={v.goRuns} data-tip="Back to all payroll runs" style={{padding: "0", border: "0", background: "none", font: "inherit", letterSpacing: "inherit", textTransform: "inherit", color: "#0f6e56", cursor: "pointer"}} className="dc-payroll-run-page-1">
                      {"Processing & Payslips"}
                    </button>
                  </p>
                </div>
                {v.headReady ? (
                  <>
                    <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px 12px"}}>
                      <h1 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "clamp(24px,2.6vw,32px)", fontWeight: "800", letterSpacing: "-.02em", lineHeight: "1.15"}}>
                        {txt(v.runLabel)}
                      </h1>
                      <HrStatusPill tone={v.pillTone}>
                        {txt(v.pillLabel)}
                      </HrStatusPill>
                    </div>
                    <p style={{margin: "0", fontSize: "14.5px", lineHeight: "1.5", color: "#475569"}}>
                      {txt(v.subtitle)}
                    </p>
                  </>
                ) : null}
                {v.headLoading ? (
                  <>
                    <div role="status" aria-label="Loading payroll run" style={{display: "grid", gap: "8px"}}>
                      <SkeletonBlock {...(v.skTitle || {})} />
                      <SkeletonBlock {...(v.skSub || {})} />
                    </div>
                  </>
                ) : null}
                {v.headError ? (
                  <>
                    <h1 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "clamp(24px,2.6vw,32px)", fontWeight: "800", letterSpacing: "-.02em", lineHeight: "1.15"}}>
                      {txt(v.runLabel)}
                    </h1>
                  </>
                ) : null}
              </div>
              {v.showActions ? (
                <>
                  <div style={{flex: "1 1 auto", minWidth: "0", display: "grid", gap: "8px", justifyItems: "end"}}>
                    {v.hasFinalLine ? (
                      <>
                        <span style={{display: "inline-flex", alignItems: "center", gap: "6px", fontSize: "13px", fontWeight: "600", color: "#0a5240", textAlign: "right"}}>
                          {txt(v.finalIcon)}{txt(v.finalLine)}
                        </span>
                      </>
                    ) : null}
                    <div style={{display: "flex", flexWrap: "wrap", justifyContent: "flex-end", gap: "8px"}}>
                      {v.aDraft ? (
                        <>
                          <HrButton onClick={v.askProcess} disabled={v.processDisabled} data-tip="Opens Process payroll?">
                            {txt(v.icPlay)}{" Process"}
                          </HrButton>
                        </>
                      ) : null}
                      {v.aBusy ? (
                        <>
                          <HrButton disabled={true}>
                            {txt(v.spin)}{" Processing…"}
                          </HrButton>
                        </>
                      ) : null}
                      {v.aProcessed ? (
                        <>
                          <HrButton variant="ghost" onClick={v.askReprocess} data-tip="Opens Re-process payroll?">
                            {txt(v.icRedo)}{" Re-process"}
                          </HrButton>
                          <HrButton onClick={v.askLock} data-tip="Opens Lock this payroll run?">
                            {txt(v.icLock)}{" Lock"}
                          </HrButton>
                        </>
                      ) : null}
                      {v.aLocked ? (
                        <>
                          <HrButton variant="ghost" onClick={v.askReopen} data-tip="Opens Reopen payroll?">
                            {txt(v.icPencil)}{" Reopen for corrections"}
                          </HrButton>
                          <HrButton onClick={v.askPrepare} data-tip="Opens Prepare bank disbursement?">
                            {txt(v.icBank)}{" Prepare bank disbursement"}
                          </HrButton>
                        </>
                      ) : null}
                      {v.aReady ? (
                        <>
                          <HrButton variant="ghost" onClick={v.askReopen} data-tip="Opens Reopen payroll?">
                            {txt(v.icPencil)}{" Reopen for corrections"}
                          </HrButton>
                          <HrButton onClick={v.askPaid} data-tip="Opens Mark as paid?">
                            {txt(v.icCheck)}{" Mark as paid"}
                          </HrButton>
                        </>
                      ) : null}
                      {v.aPaid ? (
                        <>
                          <HrButton variant="ghost" onClick={v.goBank} data-tip="Opens Bank Disbursement">
                            {txt(v.icBank)}{" View bank disbursement"}
                          </HrButton>
                          <HrButton variant="ghost" onClick={v.downloadRegister} data-tip="Downloads the payroll register (PDF)">
                            {txt(v.icDownload)}{" Download payroll register"}
                          </HrButton>
                        </>
                      ) : null}
                    </div>
                  </div>
                </>
              ) : null}
            </div>
            {v.showSteps ? (
              <>
                <div style={{display: "grid", gridTemplateColumns: "minmax(0,1fr)", gap: "14px", paddingTop: "18px", borderTop: "1px solid #eef2f1"}}>
                  <ProcessSteps steps={v.steps} current={v.cur} complete={v.complete} busy={v.busy} label="Payroll run progress" />
                  <p aria-live="polite" style={{margin: "0", display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "center", gap: "6px 10px", fontSize: "13px", lineHeight: "1.45", color: "#475569", textAlign: "center"}}>
                    <span style={{padding: "3px 10px", borderRadius: "999px", background: "#ecfdf5", border: "1px solid #a7f3d0", color: "#0a5240", fontSize: "12px", fontWeight: "700", whiteSpace: "nowrap"}}>
                      {txt(v.stepOf)}
                    </span>
                    <span style={{textWrap: "pretty"}}>
                      {txt(v.nextHint)}
                    </span>
                  </p>
                </div>
              </>
            ) : null}
            {v.stepsLoading ? (
              <>
                <SkeletonBlock {...(v.skSteps || {})} />
              </>
            ) : null}
          </div>
        </header>
        {v.showBanner ? (
          <>
            <section role="status" aria-label="Skipped employees" style={{display: "grid", gap: "12px", padding: "16px 18px", border: "1px solid #fcd34d", borderRadius: "16px", background: "#fffbeb"}}>
              <div style={{display: "flex", flexWrap: "wrap", alignItems: "flex-start", gap: "10px 12px"}}>
                <span style={{flex: "0 0 auto", display: "inline-flex", marginTop: "1px", color: "#b45309"}}>
                  {txt(v.icAlert)}
                </span>
                <div style={{flex: "1 1 240px", minWidth: "0", display: "grid", gap: "3px"}}>
                  <strong style={{fontSize: "14px", color: "#78350f"}}>
                    {txt(v.bannerTitle)}
                  </strong>
                  <span style={{fontSize: "13px", lineHeight: "1.5", color: "#92400e", textWrap: "pretty"}}>
                    {txt(v.bannerBody)}
                  </span>
                </div>
                <button type="button" onClick={v.viewSkipped} data-tip="Opens the Skipped tab" style={{padding: "0", border: "0", background: "none", font: "inherit", fontSize: "13px", fontWeight: "700", color: "#92400e", cursor: "pointer", whiteSpace: "nowrap"}} className="dc-payroll-run-page-1">
                  {"View list"}
                </button>
              </div>
              <div style={{display: "grid", gap: "8px"}}>
                {arr(v.skippedRows).map((k: any, $index: number) => (
                  <Fragment key={$index}>
                    <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px 12px", padding: "10px 12px", borderRadius: "12px", background: "#fff", border: "1px solid #fde68a"}}>
                      <span aria-hidden="true" style={{flex: "0 0 32px", width: "32px", height: "32px", borderRadius: "999px", background: "#fef3c7", color: "#92400e", display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: "12px", fontWeight: "800"}}>
                        {txt(k?.initials)}
                      </span>
                      <div style={{flex: "1 1 180px", minWidth: "0", display: "flex", flexWrap: "wrap", alignItems: "baseline", gap: "2px 10px"}}>
                        <strong style={{fontSize: "13.5px"}}>
                          {txt(k?.name)}
                        </strong>
                        <span style={{fontFamily: "'JetBrains Mono',ui-monospace,monospace", fontSize: "12.5px", fontWeight: "600", color: "#475569"}}>
                          {txt(k?.code)}
                        </span>
                        <span style={{fontSize: "12.5px", color: "#64748b"}}>
                          {txt(k?.meta)}
                        </span>
                      </div>
                      {k?.isFixed ? (
                        <>
                          <HrStatusPill tone="ok">
                            {"Structure added"}
                          </HrStatusPill>
                        </>
                      ) : null}
                      {k?.notFixed ? (
                        <>
                          <HrButton size="sm" onClick={k?.onFix} data-tip={k?.tip}>
                            {"Fix"}
                          </HrButton>
                        </>
                      ) : null}
                    </div>
                  </Fragment>
                ))}
              </div>
            </section>
          </>
        ) : null}
        {v.statsDesktop ? (
          <>
            <div style={{display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(min(100%,220px),1fr))", gap: "16px"}}>
              {arr(v.stats).map((c: any, $index: number) => (
                <Fragment key={$index}>
                  <HrStatCard icon={c?.icon} color={c?.color} value={c?.value} label={c?.label} sub={c?.sub} loading={c?.loading} />
                </Fragment>
              ))}
            </div>
          </>
        ) : null}
        {v.statsMobile ? (
          <>
            <div role="region" aria-label="Run totals" style={{display: "grid", gridAutoFlow: "column", gridAutoColumns: "82%", gap: "12px", overflowX: "auto", scrollSnapType: "x mandatory", paddingBottom: "4px", scrollbarWidth: "none"}}>
              {arr(v.stats).map((c: any, $index: number) => (
                <Fragment key={$index}>
                  <div style={{scrollSnapAlign: "start", minWidth: "0"}}>
                    <HrStatCard icon={c?.icon} color={c?.color} value={c?.value} label={c?.label} sub={c?.sub} loading={c?.loading} />
                  </div>
                </Fragment>
              ))}
            </div>
          </>
        ) : null}
        {v.showTabs ? (
          <>
            <HrTabs tabs={v.tabs} active={v.tab} onChange={v.setTab} />
          </>
        ) : null}
        {v.tOverview ? (
          <>
            <PayrollOverview step={v.step} busy={v.busy} disb={v.disb} skippedCount={v.nSkipped} stamps={v.stamps} log={v.log} meta={v.meta} totals={v.totals} scale={v.scale} extra={v.extraRows} onNavigate={v.navOverview} onToast={v.toast} {...(v.pxOverview || {})} />
          </>
        ) : null}
        {v.tEmployees ? (
          <>
            <PayrollEmployees step={v.step} busy={v.busy} mobile={v.mobile} extra={v.extraRows} limit={v.limit} count={v.totalsEmployees} onOpen={v.openSlip} onProcess={v.askProcess} onToast={v.toast} {...(v.pxEmployees || {})} />
          </>
        ) : null}
        {v.tSkipped ? (
          <>
            <section style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px", boxShadow: "0 1px 2px rgba(15,23,42,.04)", padding: "20px 22px", display: "grid", gap: "4px"}}>
              <div style={{display: "grid", gap: "3px", marginBottom: "8px"}}>
                <h3 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "16px", fontWeight: "700"}}>
                  {"Skipped employees"}
                </h3>
                <p style={{margin: "0", fontSize: "13px", color: "#64748b", textWrap: "pretty"}}>
                  {txt(v.skippedSub)}
                </p>
              </div>
              {arr(v.skippedRows).map((k: any, $index: number) => (
                <Fragment key={$index}>
                  <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px 12px", padding: "12px 0", borderTop: "1px solid #f1f5f9"}}>
                    <span aria-hidden="true" style={{flex: "0 0 36px", width: "36px", height: "36px", borderRadius: "999px", background: "#fef3c7", color: "#92400e", display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: "12.5px", fontWeight: "800"}}>
                      {txt(k?.initials)}
                    </span>
                    <div style={{flex: "1 1 200px", minWidth: "0", display: "grid", gap: "2px"}}>
                      <span style={{display: "flex", flexWrap: "wrap", alignItems: "baseline", gap: "2px 8px"}}>
                        <strong style={{fontSize: "14px"}}>
                          {txt(k?.name)}
                        </strong>
                        <span style={{fontFamily: "'JetBrains Mono',ui-monospace,monospace", fontSize: "12.5px", fontWeight: "600", color: "#475569"}}>
                          {txt(k?.code)}
                        </span>
                      </span>
                      <span style={{fontSize: "12.5px", color: "#64748b"}}>
                        {txt(k?.meta)}
                      </span>
                    </div>
                    {k?.isFixed ? (
                      <>
                        <HrStatusPill tone="ok">
                          {"Structure added"}
                        </HrStatusPill>
                      </>
                    ) : null}
                    {k?.notFixed ? (
                      <>
                        <HrStatusPill tone="warn">
                          {"No salary structure"}
                        </HrStatusPill>
                        <HrButton size="sm" onClick={k?.onFix} data-tip={k?.tip}>
                          {"Fix"}
                        </HrButton>
                      </>
                    ) : null}
                  </div>
                </Fragment>
              ))}
            </section>
          </>
        ) : null}
        {v.contentLoading ? (
          <>
            <div role="status" aria-label="Loading run details" style={{display: "grid", gap: "12px"}}>
              <SkeletonBlock {...(v.skBlock || {})} />
              <SkeletonBlock {...(v.skBlockSm || {})} />
            </div>
          </>
        ) : null}
        {v.contentError ? (
          <>
            <div style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px"}}>
              <EmptyState icon={v.errIcon} title="Couldn’t load this payroll run" description="Something went wrong on our side and nothing was changed. Try again in a moment." action={v.retryAction} />
            </div>
          </>
        ) : null}
        {v.contentEmpty ? (
          <>
            <div style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px"}}>
              <EmptyState icon={v.emptyIcon} title={v.emptyTitle} description="No active employee has a salary structure yet. Add salary structures, then process this run." action={v.emptyAction} />
            </div>
          </>
        ) : null}
      </div>
      {v.slipOpen ? (
        <>
          <PayslipDrawer emp={v.slipEmp} runLabel={v.runLabel} final={v.slipFinal} onClose={v.closeSlip} onToast={v.toast} {...(v.pxSlip || {})} />
        </>
      ) : null}
      <Modal open={v.mOpen} onOpenChange={v.setModalOpen} title={v.mTitle} description={v.mDesc} size="sm">
        <div style={{display: "grid", gap: "14px", marginTop: "4px", fontFamily: "Inter,-apple-system,sans-serif", color: "#0f172a"}}>
          {v.mSkipNote ? (
            <>
              <p style={{margin: "0", display: "flex", alignItems: "flex-start", gap: "8px", padding: "10px 12px", borderRadius: "12px", background: "#fffbeb", border: "1px solid #fde68a", fontSize: "13px", lineHeight: "1.45", color: "#92400e"}}>
                <span style={{display: "inline-flex", flexShrink: "0", marginTop: "1px"}}>
                  {txt(v.icAlertSm)}
                </span>
                <span>
                  {txt(v.mSkipText)}
                </span>
              </p>
            </>
          ) : null}
          {v.mAddNote ? (
            <>
              <p style={{margin: "0", display: "flex", alignItems: "flex-start", gap: "8px", padding: "10px 12px", borderRadius: "12px", background: "#ecfdf5", border: "1px solid #a7f3d0", fontSize: "13px", lineHeight: "1.45", color: "#065f46"}}>
                <span style={{display: "inline-flex", flexShrink: "0", marginTop: "1px"}}>
                  {txt(v.icCheckSm)}
                </span>
                <span>
                  {txt(v.mAddText)}
                </span>
              </p>
            </>
          ) : null}
          {v.mIsReopen ? (
            <>
              <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
                {"Reason for reopening *"}
                <textarea value={v.reason} onChange={v.setReason} rows={3} maxLength={240} placeholder="e.g. Wrong LOP for 3 people in Packaging" style={{font: "inherit", fontWeight: "400", padding: "9px 12px", border: "1px solid #cbd5e1", borderRadius: "10px", outline: "none", resize: "vertical"}} className="dc-payroll-run-page-2">

                </textarea>
                <span style={{fontSize: "12px", fontWeight: "400", color: "#64748b"}}>
                  {"Saved to the activity log. At least 5 characters."}
                </span>
              </label>
            </>
          ) : null}
          {v.mIsPaid ? (
            <>
              <label style={{display: "grid", gap: "6px", fontSize: "13px", fontWeight: "600"}}>
                {"Bank reference (UTR) *"}
                <input value={v.utr} onChange={v.setUtr} maxLength={120} placeholder="e.g. HDFCN52026092012345" style={{font: "inherit", fontWeight: "400", padding: "9px 12px", border: "1px solid #cbd5e1", borderRadius: "10px", outline: "none"}} className="dc-payroll-run-page-2" />
                <span style={{fontSize: "12px", fontWeight: "400", color: "#64748b"}}>
                  {"From your bank’s transfer confirmation. Saved with the payment."}
                </span>
              </label>
            </>
          ) : null}
          {" "}
          {v.mBankNote ? (
            <>
              <p style={{margin: "0", display: "flex", alignItems: "flex-start", gap: "8px", padding: "10px 12px", borderRadius: "12px", background: "#fffbeb", border: "1px solid #fde68a", fontSize: "13px", lineHeight: "1.45", color: "#92400e"}}>
                <span style={{display: "inline-flex", flexShrink: "0", marginTop: "1px"}}>
                  {txt(v.icAlertSm)}
                </span>
                <span>
                  {txt(v.mBankText)}
                </span>
              </p>
            </>
          ) : null}
          {v.mIsPrepare ? (
            <>
              <div style={{display: "grid", gap: "8px"}}>
                {arr(v.batchRows).map((b: any, $index: number) => (
                  <Fragment key={$index}>
                    <div style={{display: "flex", alignItems: "center", justifyContent: "space-between", gap: "12px", padding: "10px 12px", border: "1px solid #e2e8f0", borderRadius: "12px", fontSize: "13px"}}>
                      <span style={{display: "grid", gap: "2px"}}>
                        <strong>
                          {txt(b?.bank)}
                        </strong>
                        <span style={{color: "#64748b"}}>
                          {txt(b?.count)}{" employees · "}{txt(b?.file)}
                        </span>
                      </span>
                      <strong style={{fontVariantNumeric: "tabular-nums"}}>
                        {txt(b?.amount)}
                      </strong>
                    </div>
                  </Fragment>
                ))}
                <div style={{display: "flex", justifyContent: "space-between", gap: "12px", padding: "4px 12px 0", fontSize: "13.5px"}}>
                  <strong>
                    {"Total net pay"}
                  </strong>
                  <strong style={{color: "#0f6e56", fontVariantNumeric: "tabular-nums"}}>
                    {txt(v.netLabel)}
                  </strong>
                </div>
              </div>
            </>
          ) : null}
          <div style={{display: "flex", flexWrap: "wrap", justifyContent: "flex-end", gap: "8px", marginTop: "4px"}}>
            <HrButton variant="ghost" onClick={v.closeModal}>
              {"Cancel"}
            </HrButton>
            <HrButton onClick={v.mConfirm} disabled={v.mDisabled}>
              {txt(v.mConfirmLabel)}
            </HrButton>
          </div>
        </div>
      </Modal>
    </>
  )
}
