// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component PayrollEmployees.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { Fragment } from 'react'
import { HrButton, TableCard } from '@/shared/components/hr'
import { DataTable } from '@/shared/components/DataTable'
import { EmptyState } from '@/shared/components/EmptyState'
import { arr, txt } from './dc-runtime'

export function PayrollEmployeesView({ v }: { v: any }) {
  return (
    <>
      <div style={{display: "grid", gap: "12px", minWidth: "0", fontFamily: "Inter,-apple-system,sans-serif", color: "#0f172a"}}>
        {v.isDraft ? (
          <>
            <div style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px"}}>
              <EmptyState icon={v.emptyIcon} title="No payslips yet" description={v.draftText} action={v.processAction} />
            </div>
          </>
        ) : null}
        {v.showList ? (
          <>
            <TableCard search={v.search} filters={v.filters} onClearFilters={v.clear} actions={v.actions} footer={v.pager}>
              {v.isDesktop ? (
                <>
                  <DataTable columns={v.columns} data={v.pageRows} keyField="id" loading={v.busy} emptyMessage="No one matches these filters." onRowClick={v.openRow} />
                </>
              ) : null}
              {v.isMobile ? (
                <>
                  <div style={{display: "grid", gap: "8px", padding: "12px"}}>
                    {arr(v.pageRows).map((r: any, $index: number) => (
                      <Fragment key={$index}>
                        <article style={{display: "grid", gap: "10px", padding: "12px 14px", border: "1px solid #e2e8f0", borderRadius: "14px", background: "#fff"}}>
                          <div style={{display: "flex", alignItems: "flex-start", gap: "10px"}}>
                            <div style={{flex: "1", minWidth: "0", display: "grid", gap: "2px"}}>
                              <strong style={{fontSize: "14px", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap"}}>
                                {txt(r?.name)}
                              </strong>
                              <span style={{fontSize: "12px", color: "#64748b"}}>
                                <span style={{fontFamily: "'JetBrains Mono',ui-monospace,monospace", fontWeight: "600", color: "#334155"}}>
                                  {txt(r?.code)}
                                </span>
                                {" · "}{txt(r?.dept)}
                              </span>
                            </div>
                            <HrButton variant="ghost" size="sm" onClick={r?.onOpen} data-tip="Opens payslip">
                              {"Payslip"}
                            </HrButton>
                          </div>
                          <dl style={{margin: "0", display: "grid", gridTemplateColumns: "repeat(4,minmax(0,1fr))", gap: "6px", fontSize: "12px"}}>
                            <div>
                              <dt style={{color: "#64748b"}}>
                                {"Paid days"}
                              </dt>
                              <dd style={{margin: "2px 0 0", fontWeight: "600", fontVariantNumeric: "tabular-nums"}}>
                                {txt(r?.paidDays)}
                              </dd>
                            </div>
                            <div>
                              <dt style={{color: "#64748b"}}>
                                {"LOP"}
                              </dt>
                              <dd style={{margin: "2px 0 0", fontWeight: "600", fontVariantNumeric: "tabular-nums"}}>
                                {txt(r?.lop)}
                              </dd>
                            </div>
                            <div>
                              <dt style={{color: "#64748b"}}>
                                {"Gross"}
                              </dt>
                              <dd style={{margin: "2px 0 0", fontWeight: "600", fontVariantNumeric: "tabular-nums", whiteSpace: "nowrap"}}>
                                {txt(r?.grossLabel)}
                              </dd>
                            </div>
                            <div>
                              <dt style={{color: "#64748b"}}>
                                {"Net pay"}
                              </dt>
                              <dd style={{margin: "2px 0 0", fontWeight: "800", fontVariantNumeric: "tabular-nums", whiteSpace: "nowrap"}}>
                                {txt(r?.netLabel)}
                              </dd>
                            </div>
                          </dl>
                        </article>
                      </Fragment>
                    ))}
                    {v.noRows ? (
                      <>
                        <p style={{margin: "0", padding: "20px", textAlign: "center", fontSize: "13px", color: "#64748b"}}>
                          {"No one matches these filters."}
                        </p>
                      </>
                    ) : null}
                  </div>
                </>
              ) : null}
            </TableCard>
          </>
        ) : null}
      </div>
    </>
  )
}
