// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component PayRuns.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { Fragment } from 'react'
import { HrButton, HrPageHeader, HrStatusPill, TableCard } from '@/shared/components/hr'
import { DataTable } from '@/shared/components/DataTable'
import { EmptyState } from '@/shared/components/EmptyState'
import { arr, txt } from './dc-runtime'
import { NewRunModal } from './NewRunModal'
import { ProcessPipeline } from './ProcessPipeline'
import './PayRuns.view.css'

export function PayRunsView({ v }: { v: any }) {
  return (
    <>
      <div ref={v.rootRef} style={{display: "grid", gridTemplateColumns: "minmax(0,1fr)", gap: "28px", minWidth: "0", fontFamily: "Inter,-apple-system,sans-serif", color: "#0f172a"}}>
        <div style={{marginBottom: "-32px", minWidth: "0"}}>
          <HrPageHeader crumb="Payroll" title="Processing & Payslips" subtitle="Process monthly payroll, review payslips and lock the period." actions={v.headerActions} />
        </div>
        <section aria-labelledby="pr-steps-h" style={{display: "grid", gap: "16px", minWidth: "0"}}>
          <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "10px 14px", paddingBottom: "14px", borderBottom: "1px solid #e2e8f0"}}>
            <span aria-hidden="true" style={{flex: "0 0 auto", width: "36px", height: "36px", boxSizing: "border-box", borderRadius: "11px", background: "#ecfdf5", border: "1px solid #d1fae5", color: "#0f6e56", display: "inline-flex", alignItems: "center", justifyContent: "center"}}>
              {txt(v.icFlow)}
            </span>
            <h2 id="pr-steps-h" style={{margin: "0", flex: "1 1 220px", minWidth: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "21px", fontWeight: "700", letterSpacing: "-.015em", lineHeight: "1.25"}}>
              {"How a payroll run moves"}
            </h2>
            {v.noStepFilter ? (
              <>
                <span style={{flex: "0 0 auto", padding: "5px 12px", borderRadius: "999px", border: "1px solid #e2e8f0", background: "#fff", fontSize: "12.5px", fontWeight: "500", color: "#475569"}}>
                  {"Select a step to filter runs"}
                </span>
              </>
            ) : null}
            {v.hasStepFilter ? (
              <>
                <button type="button" onClick={v.clearStatus} data-tip="Show every run again" style={{flex: "0 0 auto", display: "inline-flex", alignItems: "center", gap: "6px", padding: "5px 9px 5px 12px", borderRadius: "999px", border: "1px solid #a7f3d0", background: "#ecfdf5", font: "inherit", fontSize: "12.5px", fontWeight: "600", color: "#0f6e56", cursor: "pointer"}} className="dc-pay-runs-0">
                  {"Showing "}{txt(v.statusFilterLabel)}{" runs"}{txt(v.icX)}
                </button>
              </>
            ) : null}
          </div>
          <ProcessPipeline steps={v.stages} aside={v.asideStage} loading={v.isLoading} label="Payroll run steps" />
        </section>
        <section aria-labelledby="pr-runs-h" style={{display: "grid", gap: "16px", minWidth: "0"}}>
          <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "10px 14px", paddingBottom: "14px", borderBottom: "1px solid #e2e8f0"}}>
            <span aria-hidden="true" style={{flex: "0 0 auto", width: "36px", height: "36px", boxSizing: "border-box", borderRadius: "11px", background: "#ecfdf5", border: "1px solid #d1fae5", color: "#0f6e56", display: "inline-flex", alignItems: "center", justifyContent: "center"}}>
              {txt(v.icReceipt)}
            </span>
            <h2 id="pr-runs-h" style={{margin: "0", flex: "1 1 220px", minWidth: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "21px", fontWeight: "700", letterSpacing: "-.015em", lineHeight: "1.25"}}>
              {"All runs"}
            </h2>
            <span aria-live="polite" style={{flex: "0 0 auto", padding: "5px 12px", borderRadius: "999px", border: "1px solid #e2e8f0", background: "#fff", fontSize: "12.5px", fontWeight: "500", color: "#475569", fontVariantNumeric: "tabular-nums"}}>
              {txt(v.countLabel)}
            </span>
          </div>
          {v.isLoading ? (
            <>
              <div role="status" aria-label="Loading payroll runs" style={{minWidth: "0"}}>
                <TableCard filters={v.filters}>
                  {v.asTable ? (
                    <>
                      <DataTable columns={v.skelColumns} data={v.skelData} keyField="id" />
                    </>
                  ) : null}
                  {v.asRows ? (
                    <>
                      <div style={{display: "grid"}}>
                        {arr(v.skelData).map((k: any, $index: number) => (
                          <Fragment key={$index}>
                            {k?.notFirst ? (
                              <>
                                <div aria-hidden="true" style={{height: "1px", margin: "0 clamp(16px,2.4vw,24px)", background: "#eef2f1"}} />
                              </>
                            ) : null}
                            <div style={{display: "grid", gap: "14px", padding: "18px clamp(16px,2.4vw,24px)"}}>
                              {txt(k?.top)}{txt(k?.bottom)}
                            </div>
                          </Fragment>
                        ))}
                      </div>
                    </>
                  ) : null}
                </TableCard>
              </div>
            </>
          ) : null}
          {v.isError ? (
            <>
              <div style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px", boxShadow: "0 1px 2px rgba(15,23,42,.04)"}}>
                <EmptyState icon={v.errIcon} title="Unable to load payroll runs" description="We couldn’t reach the payroll service. Nothing was changed — try again." action={v.retryAction} />
              </div>
            </>
          ) : null}
          {v.isEmpty ? (
            <>
              <div style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px", boxShadow: "0 1px 2px rgba(15,23,42,.04)"}}>
                <EmptyState icon={v.emptyIcon} title="No payroll runs" description={v.emptyDesc} action={v.emptyAction} />
              </div>
            </>
          ) : null}
          {v.live ? (
            <>
              <TableCard filters={v.filters} onClearFilters={v.clearFilters}>
                {v.asTable ? (
                  <>
                    <DataTable columns={v.columns} data={v.rows} keyField="id" emptyMessage="No runs match these filters." onRowClick={v.openRow} />
                  </>
                ) : null}
                {v.asRows ? (
                  <>
                    <div role="list" aria-label="Payroll runs" style={{display: "grid"}}>
                      {arr(v.rows).map((r: any, $index: number) => (
                        <Fragment key={$index}>
                          <div role="listitem">
                            {r?.notFirst ? (
                              <>
                                <div aria-hidden="true" style={{height: "1px", margin: "0 clamp(16px,2.4vw,24px)", background: "#eef2f1"}} />
                              </>
                            ) : null}
                            <div role="button" tabIndex={0} aria-label={r?.aria} onClick={r?.onOpen} onKeyDown={r?.onKey} style={{display: "grid", gap: "14px", padding: "16px clamp(16px,2.4vw,24px)", cursor: "pointer", outline: "none", transition: "background .15s"}} className="dc-pay-runs-1 dc-pay-runs-2">
                              <div style={{display: "flex", flexWrap: "wrap", alignItems: "flex-start", justifyContent: "space-between", gap: "8px 16px"}}>
                                <div style={{display: "grid", gap: "2px", minWidth: "0"}}>
                                  <strong style={{fontSize: "15.5px", fontWeight: "700", color: "#0f172a"}}>
                                    {txt(r?.label)}
                                  </strong>
                                  <span style={{fontSize: "12.5px", color: "#64748b"}}>
                                    {txt(r?.company)}
                                  </span>
                                </div>
                                <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px"}}>
                                  <HrStatusPill tone={r?.tone}>
                                    {txt(r?.statusLabel)}
                                  </HrStatusPill>
                                  {r?.hasExc ? (
                                    <>
                                      <span style={{display: "inline-flex", alignItems: "center", gap: "5px", padding: "2px 9px", borderRadius: "999px", background: "#fffbeb", border: "1px solid #fde68a", color: "#92400e", fontSize: "11.5px", fontWeight: "700"}}>
                                        {txt(v.icWarnSm)}{txt(r?.excLabel)}
                                      </span>
                                      <button type="button" onClick={r?.onReview} style={{border: "0", background: "none", padding: "2px 0", font: "inherit", fontSize: "12.5px", fontWeight: "700", color: "#0f6e56", textDecoration: "underline", textUnderlineOffset: "3px", cursor: "pointer"}}>
                                        {"Review"}
                                      </button>
                                    </>
                                  ) : null}
                                  <span aria-hidden="true" style={{display: "inline-flex", color: "#94a3b8"}}>
                                    {txt(v.icChevron)}
                                  </span>
                                </div>
                              </div>
                              <dl style={{margin: "0", display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(118px,1fr))", gap: "10px 16px"}}>
                                <div style={{display: "grid", gap: "3px", minWidth: "0"}}>
                                  <dt style={{fontSize: "11px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#64748b"}}>
                                    {"Employees"}
                                  </dt>
                                  {r?.empOk ? (
                                    <>
                                      <dd style={{margin: "0", fontSize: "14px", fontWeight: "600", fontVariantNumeric: "tabular-nums", color: "#0f172a"}}>
                                        {txt(r?.employeesL)}
                                      </dd>
                                    </>
                                  ) : null}
                                  {r?.empNa ? (
                                    <>
                                      <dd style={{margin: "0", fontSize: "14px", fontWeight: "500", color: "#64748b"}}>
                                        {"—"}
                                      </dd>
                                    </>
                                  ) : null}
                                </div>
                                <div style={{display: "grid", gap: "3px", minWidth: "0"}}>
                                  <dt style={{fontSize: "11px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#64748b"}}>
                                    {"Gross"}
                                  </dt>
                                  {r?.grossOk ? (
                                    <>
                                      <dd style={{margin: "0", fontSize: "14px", fontWeight: "600", fontVariantNumeric: "tabular-nums", color: "#0f172a"}}>
                                        {txt(r?.grossL)}
                                      </dd>
                                    </>
                                  ) : null}
                                  {r?.grossNa ? (
                                    <>
                                      <dd style={{margin: "0", fontSize: "14px", fontWeight: "500", color: "#64748b"}}>
                                        {"—"}
                                      </dd>
                                    </>
                                  ) : null}
                                </div>
                                <div style={{display: "grid", gap: "3px", minWidth: "0"}}>
                                  <dt style={{fontSize: "11px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#64748b"}}>
                                    {"Deductions"}
                                  </dt>
                                  {r?.dedOk ? (
                                    <>
                                      <dd style={{margin: "0", fontSize: "14px", fontWeight: "600", fontVariantNumeric: "tabular-nums", color: "#0f172a"}}>
                                        {txt(r?.dedL)}
                                      </dd>
                                    </>
                                  ) : null}
                                  {r?.dedNa ? (
                                    <>
                                      <dd style={{margin: "0", fontSize: "14px", fontWeight: "500", color: "#64748b"}}>
                                        {"—"}
                                      </dd>
                                    </>
                                  ) : null}
                                </div>
                                <div style={{display: "grid", gap: "3px", minWidth: "0"}}>
                                  <dt style={{fontSize: "11px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#64748b"}}>
                                    {"Net pay"}
                                  </dt>
                                  {r?.netOk ? (
                                    <>
                                      <dd style={{margin: "0", fontSize: "14px", fontWeight: "800", fontVariantNumeric: "tabular-nums", color: "#0f172a"}}>
                                        {txt(r?.netL)}
                                      </dd>
                                    </>
                                  ) : null}
                                  {r?.netNa ? (
                                    <>
                                      <dd style={{margin: "0", fontSize: "14px", fontWeight: "500", color: "#64748b"}}>
                                        {"—"}
                                      </dd>
                                    </>
                                  ) : null}
                                </div>
                                <div style={{display: "grid", gap: "3px", minWidth: "0"}}>
                                  <dt style={{fontSize: "11px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#64748b"}}>
                                    {"Processed"}
                                  </dt>
                                  {r?.procOk ? (
                                    <>
                                      <dd style={{margin: "0", fontSize: "14px", fontWeight: "500", fontVariantNumeric: "tabular-nums", color: "#0f172a"}}>
                                        {txt(r?.processedL)}
                                      </dd>
                                    </>
                                  ) : null}
                                  {r?.procNa ? (
                                    <>
                                      <dd style={{margin: "0", fontSize: "14px", fontWeight: "500", color: "#64748b"}}>
                                        {"—"}
                                      </dd>
                                    </>
                                  ) : null}
                                </div>
                              </dl>
                              {r?.showNext ? (
                                <>
                                  <span style={{fontSize: "12.5px", fontWeight: "500", color: "#475569"}}>
                                    {txt(r?.next)}
                                  </span>
                                </>
                              ) : null}
                            </div>
                          </div>
                        </Fragment>
                      ))}
                      {v.noRows ? (
                        <>
                          <div style={{display: "grid", justifyItems: "center", gap: "12px", padding: "40px 20px", textAlign: "center"}}>
                            <p style={{margin: "0", fontSize: "14px", color: "#64748b"}}>
                              {"No runs match these filters."}
                            </p>
                            <HrButton variant="ghost" size="sm" onClick={v.clearFilters}>
                              {"Clear filters"}
                            </HrButton>
                          </div>
                        </>
                      ) : null}
                    </div>
                  </>
                ) : null}
              </TableCard>
            </>
          ) : null}
        </section>
        <NewRunModal open={v.modalOpen} companies={v.companies} runs={v.takenRuns} onClose={v.closeModal} onCreate={v.createRun} onOpenRun={v.openExisting} />
      </div>
    </>
  )
}
