// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component PayslipDrawer.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { Fragment } from 'react'
import { HrDrawer, HrStatusPill } from '@/shared/components/hr'
import { arr, txt } from './dc-runtime'

export function PayslipDrawerView({ v }: { v: any }) {
  return (
    <>
      <HrDrawer title={v.title} onClose={v.close} footer={v.footer} width="max-w-md">
        {v.ready ? (
          <>
            <div style={{display: "grid", gap: "18px", fontFamily: "Inter,-apple-system,sans-serif", color: "#0f172a"}}>
              <div style={{display: "flex", alignItems: "flex-start", gap: "12px"}}>
                <span aria-hidden="true" style={{flex: "0 0 48px", width: "48px", height: "48px", borderRadius: "14px", background: "#0f6e56", color: "#fff", display: "inline-flex", alignItems: "center", justifyContent: "center", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "16px", fontWeight: "800", letterSpacing: "-.02em"}}>
                  {txt(v.initials)}
                </span>
                <div style={{flex: "1", minWidth: "0", display: "grid", gap: "2px"}}>
                  <h3 style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "18px", fontWeight: "700", letterSpacing: "-.01em"}}>
                    {txt(v.name)}
                  </h3>
                  <p style={{margin: "0", fontSize: "13px", color: "#475569"}}>
                    <span style={{fontFamily: "'JetBrains Mono',ui-monospace,monospace", fontWeight: "600", color: "#0f172a"}}>
                      {txt(v.code)}
                    </span>
                    {" · "}{txt(v.month)}
                  </p>
                  <p style={{margin: "0", fontSize: "12.5px", color: "#64748b"}}>
                    {txt(v.role)}{" · "}{txt(v.dept)}
                  </p>
                </div>
                <HrStatusPill tone={v.statusTone}>
                  {txt(v.statusLabel)}
                </HrStatusPill>
              </div>
              {v.preview ? (
                <>
                  <p style={{margin: "0", display: "flex", alignItems: "flex-start", gap: "8px", padding: "10px 12px", borderRadius: "12px", background: "#f8fafc", border: "1px solid #e2e8f0", fontSize: "12.5px", lineHeight: "1.45", color: "#475569"}}>
                    <span style={{display: "inline-flex", flexShrink: "0", marginTop: "1px", color: "#0f6e56"}}>
                      {txt(v.icInfo)}
                    </span>
                    {"Preview. These figures become final when the run is locked."}
                  </p>
                </>
              ) : null}
              <dl style={{margin: "0", display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: "10px"}}>
                {arr(v.info).map((i: any, $index: number) => (
                  <Fragment key={$index}>
                    <div style={{display: "grid", gap: "3px", padding: "10px 12px", borderRadius: "12px", background: "#f8fafc", border: "1px solid #f1f5f9"}}>
                      <dt style={{fontSize: "11px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#64748b"}}>
                        {txt(i?.k)}
                      </dt>
                      <dd style={{margin: "0", fontSize: "13.5px", fontWeight: "600", fontVariantNumeric: "tabular-nums", overflowWrap: "anywhere"}}>
                        {txt(i?.v)}
                      </dd>
                    </div>
                  </Fragment>
                ))}
              </dl>
              <section aria-label="Earnings" style={{display: "grid"}}>
                <h4 style={{margin: "0 0 4px", fontSize: "11px", fontWeight: "700", letterSpacing: ".08em", textTransform: "uppercase", color: "#64748b"}}>
                  {"Earnings"}
                </h4>
                {arr(v.earnings).map((l: any, $index: number) => (
                  <Fragment key={$index}>
                    <div style={{display: "flex", alignItems: "baseline", justifyContent: "space-between", gap: "12px", padding: "9px 0", borderBottom: "1px dashed #e2e8f0", fontSize: "13.5px"}}>
                      <span style={{color: "#334155"}}>
                        {txt(l?.label)}
                      </span>
                      <span style={{fontWeight: "600", fontVariantNumeric: "tabular-nums", whiteSpace: "nowrap"}}>
                        {txt(l?.amount)}
                      </span>
                    </div>
                  </Fragment>
                ))}
                <div style={{display: "flex", justifyContent: "space-between", gap: "12px", padding: "10px 0 0", fontSize: "13.5px"}}>
                  <strong>
                    {"Gross earnings"}
                  </strong>
                  <strong style={{fontVariantNumeric: "tabular-nums"}}>
                    {txt(v.grossLabel)}
                  </strong>
                </div>
              </section>
              <section aria-label="Deductions" style={{display: "grid"}}>
                <h4 style={{margin: "0 0 4px", fontSize: "11px", fontWeight: "700", letterSpacing: ".08em", textTransform: "uppercase", color: "#64748b"}}>
                  {"Deductions"}
                </h4>
                {arr(v.deductions).map((l: any, $index: number) => (
                  <Fragment key={$index}>
                    <div style={{display: "flex", alignItems: "baseline", justifyContent: "space-between", gap: "12px", padding: "9px 0", borderBottom: "1px dashed #e2e8f0", fontSize: "13.5px"}}>
                      <span style={{color: "#334155"}}>
                        {txt(l?.label)}
                      </span>
                      <span style={{fontWeight: "600", fontVariantNumeric: "tabular-nums", whiteSpace: "nowrap"}}>
                        {txt(l?.amount)}
                      </span>
                    </div>
                  </Fragment>
                ))}
                <div style={{display: "flex", justifyContent: "space-between", gap: "12px", padding: "10px 0 0", fontSize: "13.5px"}}>
                  <strong>
                    {"Total deductions"}
                  </strong>
                  <strong style={{fontVariantNumeric: "tabular-nums"}}>
                    {txt(v.dedLabel)}
                  </strong>
                </div>
              </section>
              <div style={{display: "grid", gap: "4px", padding: "16px", borderRadius: "14px", background: "#ecfdf5", border: "1px solid #a7f3d0"}}>
                <div style={{display: "flex", flexWrap: "wrap", alignItems: "baseline", justifyContent: "space-between", gap: "4px 12px"}}>
                  <strong style={{fontSize: "14px", color: "#065f46"}}>
                    {"Net pay"}
                  </strong>
                  <strong style={{fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "26px", fontWeight: "800", letterSpacing: "-.02em", color: "#0f6e56", fontVariantNumeric: "tabular-nums"}}>
                    {txt(v.netLabel)}
                  </strong>
                </div>
                <span style={{fontSize: "12.5px", color: "#047857", textWrap: "pretty"}}>
                  {txt(v.netWords)}
                </span>
              </div>
            </div>
          </>
        ) : null}
        {" "}{txt(v.stateBlock)}{" "}
      </HrDrawer>
    </>
  )
}
