// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component ProcessPipeline.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { Fragment } from 'react'
import { arr, txt } from './dc-runtime'
import './ProcessPipeline.view.css'

export function ProcessPipelineView({ v }: { v: any }) {
  return (
    <>
      <div ref={v.rootRef} role="group" aria-label={v.label} style={{minWidth: "0", fontFamily: "Inter,-apple-system,sans-serif", color: "#0f172a"}}>
        <ol style={{listStyle: "none", margin: "0", padding: "0", display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(200px,1fr))", gap: "16px", minWidth: "0"}}>
          {arr(v.tiles).map((t: any, $index: number) => (
            <Fragment key={$index}>
              <li style={{position: "relative", display: "grid", minWidth: "0", borderRadius: "16px", transition: "transform .15s ease,box-shadow .15s ease"}} className="dc-process-pipeline-0">
                {t?.fGray ? (
                  <>
                    <span aria-hidden="true" style={{position: "absolute", inset: "0", borderRadius: "16px", border: "1px solid #e2e8f0", background: "#fff", boxShadow: "0 1px 2px rgba(15,23,42,.04)", pointerEvents: "none"}} />
                  </>
                ) : null}
                {t?.fBlue ? (
                  <>
                    <span aria-hidden="true" style={{position: "absolute", inset: "0", borderRadius: "16px", border: "1px solid #bfdbfe", background: "#fff", boxShadow: "0 1px 2px rgba(15,23,42,.04)", pointerEvents: "none"}} />
                  </>
                ) : null}
                {t?.fTeal ? (
                  <>
                    <span aria-hidden="true" style={{position: "absolute", inset: "0", borderRadius: "16px", border: "1px solid #99f6e4", background: "#fff", boxShadow: "0 1px 2px rgba(15,23,42,.04)", pointerEvents: "none"}} />
                  </>
                ) : null}
                {t?.fGreen ? (
                  <>
                    <span aria-hidden="true" style={{position: "absolute", inset: "0", borderRadius: "16px", border: "1px solid #a7f3d0", background: "#fff", boxShadow: "0 1px 2px rgba(15,23,42,.04)", pointerEvents: "none"}} />
                  </>
                ) : null}
                {t?.fRed ? (
                  <>
                    <span aria-hidden="true" style={{position: "absolute", inset: "0", borderRadius: "16px", border: "1px solid #fecdd3", background: "#fff", boxShadow: "0 1px 2px rgba(15,23,42,.04)", pointerEvents: "none"}} />
                  </>
                ) : null}
                {t?.fAside ? (
                  <>
                    <span aria-hidden="true" style={{position: "absolute", inset: "0", borderRadius: "16px", border: "1px dashed #cbd5e1", background: "#fff", pointerEvents: "none"}} />
                  </>
                ) : null}
                {t?.fActive ? (
                  <>
                    <span aria-hidden="true" style={{position: "absolute", inset: "0", borderRadius: "16px", border: "2px solid #10b981", background: "#f3fcf8", boxShadow: "0 0 0 4px rgba(16,185,129,.12)", pointerEvents: "none"}} />
                  </>
                ) : null}
                <button type="button" aria-pressed={t?.pressed} disabled={t?.disabled} onClick={t?.onClick} data-tip={t?.tip} style={{position: "relative", display: "grid", gap: "10px", alignContent: "start", minWidth: "0", height: "100%", boxSizing: "border-box", padding: "16px", border: "0", borderRadius: "16px", background: "transparent", font: "inherit", color: "inherit", textAlign: "left", cursor: "pointer", outline: "none"}} className="dc-process-pipeline-1">
                  <span style={{display: "grid", gridTemplateColumns: "auto minmax(0,1fr) auto", alignItems: "center", gap: "12px", minWidth: "0"}}>
                    {t?.cGray ? (
                      <>
                        <span aria-hidden="true" style={{width: "40px", height: "40px", boxSizing: "border-box", borderRadius: "12px", background: "#f1f5f9", border: "1px solid #e2e8f0", color: "#475569", display: "inline-flex", alignItems: "center", justifyContent: "center"}}>
                          {txt(t?.icon)}
                        </span>
                      </>
                    ) : null}
                    {t?.cBlue ? (
                      <>
                        <span aria-hidden="true" style={{width: "40px", height: "40px", boxSizing: "border-box", borderRadius: "12px", background: "#eff6ff", border: "1px solid #bfdbfe", color: "#2563eb", display: "inline-flex", alignItems: "center", justifyContent: "center"}}>
                          {txt(t?.icon)}
                        </span>
                      </>
                    ) : null}
                    {t?.cTeal ? (
                      <>
                        <span aria-hidden="true" style={{width: "40px", height: "40px", boxSizing: "border-box", borderRadius: "12px", background: "#f0fdfa", border: "1px solid #99f6e4", color: "#0d9488", display: "inline-flex", alignItems: "center", justifyContent: "center"}}>
                          {txt(t?.icon)}
                        </span>
                      </>
                    ) : null}
                    {t?.cGreen ? (
                      <>
                        <span aria-hidden="true" style={{width: "40px", height: "40px", boxSizing: "border-box", borderRadius: "12px", background: "#ecfdf5", border: "1px solid #a7f3d0", color: "#047857", display: "inline-flex", alignItems: "center", justifyContent: "center"}}>
                          {txt(t?.icon)}
                        </span>
                      </>
                    ) : null}
                    {t?.cRed ? (
                      <>
                        <span aria-hidden="true" style={{width: "40px", height: "40px", boxSizing: "border-box", borderRadius: "12px", background: "#fff1f2", border: "1px solid #fecdd3", color: "#e11d48", display: "inline-flex", alignItems: "center", justifyContent: "center"}}>
                          {txt(t?.icon)}
                        </span>
                      </>
                    ) : null}
                    <span style={{display: "grid", gap: "1px", minWidth: "0"}}>
                      <span style={{fontSize: "11px", fontWeight: "700", letterSpacing: ".08em", textTransform: "uppercase", color: "#64748b"}}>
                        {txt(t?.stepLabel)}
                      </span>
                      <span style={{fontSize: "15px", fontWeight: "700", color: "#0f172a", overflowWrap: "anywhere"}}>
                        {txt(t?.label)}
                      </span>
                    </span>
                    <span style={{display: "grid", justifyItems: "end", gap: "1px"}}>
                      {txt(t?.valueNode)}
                      <span style={{fontSize: "12px", fontWeight: "500", color: "#64748b"}}>
                        {txt(t?.unit)}
                      </span>
                    </span>
                  </span>
                  <span style={{fontSize: "12.5px", lineHeight: "1.45", color: "#475569", textWrap: "pretty"}}>
                    {txt(t?.desc)}
                  </span>
                  {t?.hasAlert ? (
                    <>
                      <span style={{justifySelf: "start", display: "inline-flex", alignItems: "center", gap: "6px", padding: "3px 9px", borderRadius: "999px", background: "#fffbeb", border: "1px solid #fde68a", color: "#92400e", fontSize: "12px", fontWeight: "600"}}>
                        {txt(v.icWarn)}{txt(t?.alert)}
                      </span>
                    </>
                  ) : null}
                </button>
                {t?.hasArrow ? (
                  <>
                    <span aria-hidden="true" style={{position: "absolute", right: "-20px", top: "50%", transform: "translateY(-50%)", zIndex: "2", width: "24px", height: "24px", boxSizing: "border-box", borderRadius: "999px", background: "#fff", border: "1px solid #e2e8f0", color: "#64748b", display: "inline-flex", alignItems: "center", justifyContent: "center", boxShadow: "0 1px 3px rgba(15,23,42,.08)"}}>
                      {txt(v.icNext)}
                    </span>
                  </>
                ) : null}
              </li>
            </Fragment>
          ))}
        </ol>
      </div>
    </>
  )
}
