// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component SeatsTile.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { HrButton, HrStatusPill } from '@/shared/components/hr'
import { txt } from './dc-runtime'

export function SeatsTileView({ v }: { v: any }) {
  return (
    <>
      {v.isOk ? (
        <>
          <div style={{height: "100%", boxSizing: "border-box", background: "#fff", border: "1px solid #a7f3d0", borderRadius: "16px", padding: "18px 20px", display: "flex", flexDirection: "column", gap: "10px"}}>
            <div style={{display: "flex", alignItems: "center", justifyContent: "space-between", gap: "10px"}}>
              <span style={{display: "inline-flex", alignItems: "center", gap: "8px", fontSize: "12px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#475569"}}>
                <span style={{display: "inline-flex", width: "28px", height: "28px", borderRadius: "8px", background: "#ecfdf5", color: "#059669", alignItems: "center", justifyContent: "center"}}>
                  {txt(v.icSeats)}
                </span>
                {"Seats used"}
              </span>
              <HrStatusPill tone="ok">
                {"Healthy"}
              </HrStatusPill>
            </div>
            <p style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "30px", fontWeight: "800", lineHeight: "1", letterSpacing: "-.02em", color: "#0f172a", fontVariantNumeric: "tabular-nums"}}>
              {txt(v.used)}{" "}
              <span style={{fontSize: "15px", fontWeight: "600", color: "#64748b"}}>
                {"/ "}{txt(v.purchased)}
              </span>
            </p>
            <svg viewBox="0 0 100 8" preserveAspectRatio="none" role="progressbar" aria-valuenow={v.used} aria-valuemin={0} aria-valuemax={v.purchased} style={{display: "block", width: "100%", height: "8px", borderRadius: "4px", overflow: "hidden"}}>
              <rect width="100" height="8" fill="#ecfdf5" />
              <rect width={v.pct} height="8" fill="#10b981" />
              <rect x="85" width="0.6" height="8" fill="#ffffff" />
              <rect x="95" width="0.6" height="8" fill="#ffffff" />
            </svg>
            <div style={{display: "flex", alignItems: "center", justifyContent: "space-between", gap: "8px", flexWrap: "wrap"}}>
              <span style={{fontSize: "13px", color: "#047857", fontWeight: "600", fontVariantNumeric: "tabular-nums"}}>
                {txt(v.remaining)}{" seats left · admins included"}
              </span>
              <button type="button" onClick={v.manage} data-tip="→ /settings/billing" style={{background: "none", border: "0", padding: "0", font: "inherit", fontSize: "13px", fontWeight: "600", color: "#0f6e56", cursor: "pointer"}}>
                {"Manage plan →"}
              </button>
            </div>
          </div>
        </>
      ) : null}
      {v.isLow ? (
        <>
          <div style={{height: "100%", boxSizing: "border-box", background: "#fffbeb", border: "1px solid #fcd34d", borderRadius: "16px", padding: "18px 20px", display: "flex", flexDirection: "column", gap: "10px", boxShadow: "0 10px 24px -16px rgba(217,119,6,.6)"}}>
            <div style={{display: "flex", alignItems: "center", justifyContent: "space-between", gap: "10px"}}>
              <span style={{display: "inline-flex", alignItems: "center", gap: "8px", fontSize: "12px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#92400e"}}>
                <span style={{display: "inline-flex", width: "28px", height: "28px", borderRadius: "8px", background: "#fef3c7", color: "#b45309", alignItems: "center", justifyContent: "center"}}>
                  {txt(v.icSeats)}
                </span>
                {"Seats used"}
              </span>
              <HrStatusPill tone="warn">
                {"Running low"}
              </HrStatusPill>
            </div>
            <p style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "30px", fontWeight: "800", lineHeight: "1", letterSpacing: "-.02em", color: "#0f172a", fontVariantNumeric: "tabular-nums"}}>
              {txt(v.used)}{" "}
              <span style={{fontSize: "15px", fontWeight: "600", color: "#78716c"}}>
                {"/ "}{txt(v.purchased)}
              </span>
            </p>
            <svg viewBox="0 0 100 8" preserveAspectRatio="none" role="progressbar" aria-valuenow={v.used} aria-valuemin={0} aria-valuemax={v.purchased} style={{display: "block", width: "100%", height: "8px", borderRadius: "4px", overflow: "hidden"}}>
              <rect width="100" height="8" fill="#fef3c7" />
              <rect width={v.pct} height="8" fill="#f59e0b" />
              <rect x="85" width="0.6" height="8" fill="#fffbeb" />
              <rect x="95" width="0.6" height="8" fill="#fffbeb" />
            </svg>
            <p style={{margin: "0", fontSize: "13px", color: "#92400e", lineHeight: "1.45", textWrap: "pretty"}}>
              <strong style={{fontVariantNumeric: "tabular-nums"}}>
                {"Only "}{txt(v.remaining)}{" seats left."}
              </strong>
              {" Plan ahead before your next hires join."}
            </p>
            <div>
              <HrButton variant="ghost" size="sm" onClick={v.manage} data-tip="→ /settings/billing">
                {"Manage plan"}
              </HrButton>
            </div>
          </div>
        </>
      ) : null}
      {v.isCritical ? (
        <>
          <div style={{height: "100%", boxSizing: "border-box", background: "#fff7ed", border: "1.5px solid #fb923c", borderRadius: "16px", padding: "18px 20px", display: "flex", flexDirection: "column", gap: "10px", boxShadow: "0 0 0 4px #ffedd5,0 12px 28px -16px rgba(234,88,12,.7)"}}>
            <div style={{display: "flex", alignItems: "center", justifyContent: "space-between", gap: "10px"}}>
              <span style={{display: "inline-flex", alignItems: "center", gap: "8px", fontSize: "12px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#9a3412"}}>
                <span style={{display: "inline-flex", width: "28px", height: "28px", borderRadius: "8px", background: "#ffedd5", color: "#ea580c", alignItems: "center", justifyContent: "center"}}>
                  {txt(v.icSeats)}
                </span>
                {"Seats used"}
              </span>
              <span style={{display: "inline-flex", alignItems: "center", gap: "8px"}}>
                {txt(v.pulseOrange)}
                <HrStatusPill tone="late">
                  {"Almost full"}
                </HrStatusPill>
              </span>
            </div>
            <p style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "30px", fontWeight: "800", lineHeight: "1", letterSpacing: "-.02em", color: "#0f172a", fontVariantNumeric: "tabular-nums"}}>
              {txt(v.used)}{" "}
              <span style={{fontSize: "15px", fontWeight: "600", color: "#78716c"}}>
                {"/ "}{txt(v.purchased)}
              </span>
            </p>
            <svg viewBox="0 0 100 8" preserveAspectRatio="none" role="progressbar" aria-valuenow={v.used} aria-valuemin={0} aria-valuemax={v.purchased} style={{display: "block", width: "100%", height: "8px", borderRadius: "4px", overflow: "hidden"}}>
              <rect width="100" height="8" fill="#ffedd5" />
              <rect width={v.pct} height="8" fill="#ea580c" />
              <rect x="85" width="0.6" height="8" fill="#fff7ed" />
              <rect x="95" width="0.6" height="8" fill="#fff7ed" />
            </svg>
            <p style={{margin: "0", fontSize: "13px", color: "#9a3412", lineHeight: "1.45", textWrap: "pretty"}}>
              <strong style={{fontVariantNumeric: "tabular-nums"}}>
                {txt(v.remainingLabel)}
              </strong>
              {" New employees will be blocked once seats run out."}
            </p>
            <div>
              <HrButton size="sm" onClick={v.manage} data-tip="→ /settings/billing">
                {"Add seats"}
              </HrButton>
            </div>
          </div>
        </>
      ) : null}
      {v.isExhausted ? (
        <>
          <div role="alert" style={{height: "100%", boxSizing: "border-box", background: "#fff1f2", border: "1.5px solid #f43f5e", borderRadius: "16px", padding: "18px 20px", display: "flex", flexDirection: "column", gap: "10px", boxShadow: "0 0 0 4px #ffe4e6,0 14px 30px -16px rgba(225,29,72,.75)"}}>
            <div style={{display: "flex", alignItems: "center", justifyContent: "space-between", gap: "10px"}}>
              <span style={{display: "inline-flex", alignItems: "center", gap: "8px", fontSize: "12px", fontWeight: "700", letterSpacing: ".06em", textTransform: "uppercase", color: "#9f1239"}}>
                <span style={{display: "inline-flex", width: "28px", height: "28px", borderRadius: "8px", background: "#ffe4e6", color: "#e11d48", alignItems: "center", justifyContent: "center"}}>
                  {txt(v.icSeats)}
                </span>
                {"Seats used"}
              </span>
              <span style={{display: "inline-flex", alignItems: "center", gap: "8px"}}>
                {txt(v.pulseRed)}
                <HrStatusPill tone="red">
                  {"Seats exhausted"}
                </HrStatusPill>
              </span>
            </div>
            <p style={{margin: "0", fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "30px", fontWeight: "800", lineHeight: "1", letterSpacing: "-.02em", color: "#881337", fontVariantNumeric: "tabular-nums"}}>
              {txt(v.used)}{" "}
              <span style={{fontSize: "15px", fontWeight: "600", color: "#9f1239"}}>
                {"/ "}{txt(v.purchased)}
              </span>
            </p>
            <svg viewBox="0 0 100 8" preserveAspectRatio="none" role="progressbar" aria-valuenow={v.used} aria-valuemin={0} aria-valuemax={v.purchased} style={{display: "block", width: "100%", height: "8px", borderRadius: "4px", overflow: "hidden"}}>
              <rect width="100" height="8" fill="#e11d48" />
            </svg>
            <p style={{margin: "0", fontSize: "13px", color: "#9f1239", lineHeight: "1.45", textWrap: "pretty"}}>
              <strong>
                {"All "}{txt(v.purchased)}{" seats are in use."}
              </strong>
              {" Adding employees is blocked until you add seats."}
            </p>
            <div>
              <HrButton variant="danger" size="sm" onClick={v.manage} data-tip="→ /settings/billing">
                {"Upgrade to add more employees"}
              </HrButton>
            </div>
          </div>
        </>
      ) : null}
    </>
  )
}
