// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component SectionState.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { HrButton } from '@/shared/components/hr'
import { EmptyState } from '@/shared/components/EmptyState'
import { SkeletonBlock } from '@/shared/components/SkeletonCard'
import { txt } from './dc-runtime'

export function SectionStateView({ v }: { v: any }) {
  return (
    <>
      {v.isLoading ? (
        <>
          <div role="status" aria-label="Loading" style={{display: "grid", gap: "12px", padding: "6px 0"}}>
            <SkeletonBlock {...(v.skA || {})} />
            <SkeletonBlock {...(v.skB || {})} />
            <SkeletonBlock {...(v.skC || {})} />
          </div>
        </>
      ) : null}
      {v.isEmpty ? (
        <>
          <EmptyState icon={v.emptyIcon} title={v.title} description={v.description} />
        </>
      ) : null}
      {v.isError ? (
        <>
          <div role="alert" style={{display: "flex", flexDirection: "column", alignItems: "center", gap: "10px", padding: "28px 0", textAlign: "center"}}>
            <span style={{display: "inline-flex", width: "36px", height: "36px", borderRadius: "999px", background: "#fff1f2", color: "#be123c", alignItems: "center", justifyContent: "center"}}>
              {txt(v.errorIcon)}
            </span>
            <p style={{margin: "0", fontSize: "14px", fontWeight: "600", color: "#0f172a"}}>
              {"Unable to load this section."}
            </p>
            <HrButton variant="ghost" size="sm" onClick={v.retry}>
              {"Try again"}
            </HrButton>
          </div>
        </>
      ) : null}
    </>
  )
}
