// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component ShiftBar.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { Fragment } from 'react'
import { arr } from './dc-runtime'

export function ShiftBarView({ v }: { v: any }) {
  return (
    <>
      <div role="img" aria-label={v.aria} style={{display: "grid", gap: "5px", minWidth: "0", fontFamily: "Inter,-apple-system,sans-serif"}}>
        <div style={{position: "relative", height: "12px", borderRadius: "999px", overflow: "hidden", background: "#f1f5f9"}}>
          <span aria-hidden="true" style={{position: "absolute", left: "0", top: "0", bottom: "0", width: "25%", background: "#e4e9f2"}} />
          <span aria-hidden="true" style={{position: "absolute", right: "0", top: "0", bottom: "0", width: "16.667%", background: "#e4e9f2"}} />
          <svg width="100%" height="12" aria-hidden="true" style={{position: "absolute", left: "0", top: "0", display: "block"}}>
            {arr(v.segs).map((s: any, $index: number) => (
              <Fragment key={$index}>
                <rect x={s?.x} y="0" width={s?.w} height="12" rx="6" fill={v.color} />
              </Fragment>
            ))}
          </svg>
        </div>
        {v.ticks ? (
          <>
            <div aria-hidden="true" style={{position: "relative", height: "14px", fontSize: "10.5px", lineHeight: "14px", color: "#94a3b8", whiteSpace: "nowrap"}}>
              <span style={{position: "absolute", left: "0"}}>
                {"12 AM"}
              </span>
              <span style={{position: "absolute", left: "25%", transform: "translateX(-50%)"}}>
                {"6 AM"}
              </span>
              <span style={{position: "absolute", left: "50%", transform: "translateX(-50%)"}}>
                {"Noon"}
              </span>
              <span style={{position: "absolute", left: "75%", transform: "translateX(-50%)"}}>
                {"6 PM"}
              </span>
              <span style={{position: "absolute", right: "0"}}>
                {"12 AM"}
              </span>
            </div>
          </>
        ) : null}
      </div>
    </>
  )
}
