// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component SubTabs.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { Fragment } from 'react'
import { arr, txt } from './dc-runtime'
import './SubTabs.view.css'

export function SubTabsView({ v }: { v: any }) {
  return (
    <>
      <div role="group" aria-label={v.label} style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px", fontFamily: "Inter,-apple-system,sans-serif"}}>
        {arr(v.items).map((it: any, $index: number) => (
          <Fragment key={$index}>
            {it?.active ? (
              <>
                <button type="button" aria-pressed="true" onClick={it?.onClick} data-tip={it?.tip} style={{display: "inline-flex", alignItems: "center", gap: "7px", height: "36px", padding: "0 14px", borderRadius: "999px", border: "1px solid #6ee7b7", background: "#ecfdf5", color: "#0a5240", font: "inherit", fontSize: "13px", fontWeight: "700", cursor: "pointer", whiteSpace: "nowrap", boxShadow: "0 1px 2px rgba(15,110,86,.14)"}}>
                  {txt(it?.icon)}
                  <span>
                    {txt(it?.label)}
                  </span>
                  {it?.hasCount ? (
                    <>
                      <span style={{minWidth: "22px", height: "20px", padding: "0 6px", boxSizing: "border-box", borderRadius: "999px", background: "#0f6e56", color: "#fff", fontSize: "11px", fontWeight: "800", display: "inline-flex", alignItems: "center", justifyContent: "center", fontVariantNumeric: "tabular-nums"}}>
                        {txt(it?.count)}
                      </span>
                    </>
                  ) : null}
                </button>
              </>
            ) : null}
            {it?.inactive ? (
              <>
                <button type="button" aria-pressed="false" onClick={it?.onClick} data-tip={it?.tip} style={{display: "inline-flex", alignItems: "center", gap: "7px", height: "36px", padding: "0 14px", borderRadius: "999px", border: "1px solid #e2e8f0", background: "#fff", color: "#475569", font: "inherit", fontSize: "13px", fontWeight: "600", cursor: "pointer", whiteSpace: "nowrap", transition: "border-color .15s,background .15s"}} className="dc-sub-tabs-0">
                  {txt(it?.icon)}
                  <span>
                    {txt(it?.label)}
                  </span>
                  {it?.plainCount ? (
                    <>
                      <span style={{minWidth: "22px", height: "20px", padding: "0 6px", boxSizing: "border-box", borderRadius: "999px", background: "#f1f5f9", color: "#475569", fontSize: "11px", fontWeight: "800", display: "inline-flex", alignItems: "center", justifyContent: "center", fontVariantNumeric: "tabular-nums"}}>
                        {txt(it?.count)}
                      </span>
                    </>
                  ) : null}
                  {it?.urgentCount ? (
                    <>
                      <span style={{minWidth: "22px", height: "20px", padding: "0 6px", boxSizing: "border-box", borderRadius: "999px", background: "#fef3c7", border: "1px solid #fde68a", color: "#92400e", fontSize: "11px", fontWeight: "800", display: "inline-flex", alignItems: "center", justifyContent: "center", fontVariantNumeric: "tabular-nums"}}>
                        {txt(it?.count)}
                      </span>
                    </>
                  ) : null}
                </button>
              </>
            ) : null}
          </Fragment>
        ))}
      </div>
    </>
  )
}
