// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component TimePicker.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { Fragment } from 'react'
import { arr, txt, UTPortal } from './dc-runtime'
import './TimePicker.view.css'

export function TimePickerView({ v }: { v: any }) {
  return (
    <>
      <div ref={v.rootRef} style={{position: "relative", width: "100%", minWidth: "0", fontFamily: "Inter,-apple-system,sans-serif", color: "#0f172a"}}>
        <button ref={v.triggerRef} type="button" onClick={v.toggle} onKeyDown={v.triggerKey} aria-haspopup="dialog" aria-expanded={v.open} aria-label={v.triggerAria} style={{position: "relative", width: "100%", height: "42px", display: "flex", alignItems: "center", gap: "10px", padding: "0 12px", boxSizing: "border-box", border: "1px solid #cbd5e1", borderRadius: "10px", background: "#fff", font: "inherit", fontSize: "14px", fontWeight: "500", color: "#0f172a", textAlign: "left", cursor: "pointer", outline: "none", transition: "border-color .15s,box-shadow .15s"}} className="dc-time-picker-0 dc-time-picker-1">
          {v.open ? (
            <>
              <span aria-hidden="true" style={{position: "absolute", inset: "-1px", borderRadius: "10px", boxShadow: "0 0 0 1px #0f6e56,0 0 0 4px #a7f3d0", pointerEvents: "none"}} />
            </>
          ) : null}
          <span aria-hidden="true" style={{display: "inline-flex", flexShrink: "0", color: "#0f6e56"}}>
            {txt(v.icClock)}
          </span>
          {v.hasValue ? (
            <>
              <span style={{flex: "1", minWidth: "0", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontVariantNumeric: "tabular-nums"}}>
                {txt(v.display)}
              </span>
            </>
          ) : null}
          {v.noValue ? (
            <>
              <span style={{flex: "1", minWidth: "0", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", color: "#94a3b8", fontWeight: "400"}}>
                {txt(v.placeholder)}
              </span>
            </>
          ) : null}
          <span aria-hidden="true" style={{display: "inline-flex", flexShrink: "0", color: "#94a3b8"}}>
            {txt(v.icChev)}
          </span>
        </button>
        {v.open ? (
          <>
            <UTPortal>
              <div ref={v.setPop} role="dialog" aria-label={v.heading} onMouseDown={v.keepFocus} style={{position: "fixed", top: "0", left: "0", zIndex: "1200", width: "276px", boxSizing: "border-box", padding: "12px", background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px", boxShadow: "0 24px 48px -16px rgba(15,23,42,.32),0 2px 6px rgba(15,23,42,.06)", display: "grid", gap: "10px", fontFamily: "Inter,-apple-system,sans-serif", fontSize: "13px", fontWeight: "500", color: "#0f172a", textAlign: "left", userSelect: "none"}}>
                <div style={{display: "flex", alignItems: "center", justifyContent: "space-between", gap: "8px", padding: "2px 4px 0"}}>
                  <span style={{fontSize: "11px", fontWeight: "700", letterSpacing: ".08em", textTransform: "uppercase", color: "#64748b"}}>
                    {txt(v.heading)}
                  </span>
                  <strong style={{fontFamily: "'Plus Jakarta Sans',Inter,sans-serif", fontSize: "20px", fontWeight: "800", letterSpacing: "-.01em", fontVariantNumeric: "tabular-nums", color: "#0f172a"}}>
                    {txt(v.big)}
                  </strong>
                </div>
                <div style={{display: "grid", gridTemplateColumns: "minmax(0,1fr) minmax(0,1fr) 62px", gap: "6px"}}>
                  <div ref={v.hRef} role="listbox" aria-label="Hour" style={{position: "relative", height: "208px", overflowY: "auto", display: "grid", gap: "2px", alignContent: "start", padding: "3px", borderRadius: "12px", background: "#f8fafc", scrollbarWidth: "thin"}}>
                    {arr(v.hours).map((o: any, $index: number) => (
                      <Fragment key={$index}>
                        {o?.sel ? (
                          <>
                            <button type="button" tabIndex={-1} role="option" aria-selected="true" data-sel="1" onClick={o?.onClick} style={{height: "34px", border: "0", borderRadius: "9px", background: "#0f6e56", color: "#fff", font: "inherit", fontSize: "14px", fontWeight: "700", fontVariantNumeric: "tabular-nums", cursor: "pointer", boxShadow: "0 6px 14px -8px rgba(15,110,86,.8)"}}>
                              {txt(o?.label)}
                            </button>
                          </>
                        ) : null}
                        {o?.unsel ? (
                          <>
                            <button type="button" tabIndex={-1} role="option" aria-selected="false" onClick={o?.onClick} style={{height: "34px", border: "0", borderRadius: "9px", background: "transparent", color: "#334155", font: "inherit", fontSize: "14px", fontWeight: "500", fontVariantNumeric: "tabular-nums", cursor: "pointer"}} className="dc-time-picker-2">
                              {txt(o?.label)}
                            </button>
                          </>
                        ) : null}
                      </Fragment>
                    ))}
                  </div>
                  <div ref={v.mRef} role="listbox" aria-label="Minute" style={{position: "relative", height: "208px", overflowY: "auto", display: "grid", gap: "2px", alignContent: "start", padding: "3px", borderRadius: "12px", background: "#f8fafc", scrollbarWidth: "thin"}}>
                    {arr(v.minutes).map((o: any, $index: number) => (
                      <Fragment key={$index}>
                        {o?.sel ? (
                          <>
                            <button type="button" tabIndex={-1} role="option" aria-selected="true" data-sel="1" onClick={o?.onClick} style={{height: "34px", border: "0", borderRadius: "9px", background: "#0f6e56", color: "#fff", font: "inherit", fontSize: "14px", fontWeight: "700", fontVariantNumeric: "tabular-nums", cursor: "pointer", boxShadow: "0 6px 14px -8px rgba(15,110,86,.8)"}}>
                              {txt(o?.label)}
                            </button>
                          </>
                        ) : null}
                        {o?.unsel ? (
                          <>
                            <button type="button" tabIndex={-1} role="option" aria-selected="false" onClick={o?.onClick} style={{height: "34px", border: "0", borderRadius: "9px", background: "transparent", color: "#334155", font: "inherit", fontSize: "14px", fontWeight: "500", fontVariantNumeric: "tabular-nums", cursor: "pointer"}} className="dc-time-picker-2">
                              {txt(o?.label)}
                            </button>
                          </>
                        ) : null}
                      </Fragment>
                    ))}
                  </div>
                  <div role="listbox" aria-label="AM or PM" style={{display: "grid", gap: "6px", alignContent: "start"}}>
                    {arr(v.periods).map((o: any, $index: number) => (
                      <Fragment key={$index}>
                        {o?.sel ? (
                          <>
                            <button type="button" tabIndex={-1} role="option" aria-selected="true" onClick={o?.onClick} style={{height: "46px", border: "0", borderRadius: "11px", background: "#0f6e56", color: "#fff", font: "inherit", fontSize: "13px", fontWeight: "800", letterSpacing: ".04em", cursor: "pointer", boxShadow: "0 6px 14px -8px rgba(15,110,86,.8)"}}>
                              {txt(o?.label)}
                            </button>
                          </>
                        ) : null}
                        {o?.unsel ? (
                          <>
                            <button type="button" tabIndex={-1} role="option" aria-selected="false" onClick={o?.onClick} style={{height: "46px", border: "1px solid #e2e8f0", borderRadius: "11px", background: "#fff", color: "#334155", font: "inherit", fontSize: "13px", fontWeight: "700", letterSpacing: ".04em", cursor: "pointer"}} className="dc-time-picker-3">
                              {txt(o?.label)}
                            </button>
                          </>
                        ) : null}
                      </Fragment>
                    ))}
                  </div>
                </div>
                <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "6px", paddingTop: "10px", borderTop: "1px solid #f1f5f9"}}>
                  {arr(v.presets).map((pr: any, $index: number) => (
                    <Fragment key={$index}>
                      {pr?.active ? (
                        <>
                          <button type="button" tabIndex={-1} onClick={pr?.onClick} style={{height: "28px", padding: "0 9px", borderRadius: "999px", border: "1px solid #6ee7b7", background: "#ecfdf5", color: "#0a5240", font: "inherit", fontSize: "12px", fontWeight: "700", fontVariantNumeric: "tabular-nums", cursor: "pointer"}}>
                            {txt(pr?.label)}
                          </button>
                        </>
                      ) : null}
                      {pr?.inactive ? (
                        <>
                          <button type="button" tabIndex={-1} onClick={pr?.onClick} style={{height: "28px", padding: "0 9px", borderRadius: "999px", border: "1px solid #e2e8f0", background: "#fff", color: "#334155", font: "inherit", fontSize: "12px", fontWeight: "600", fontVariantNumeric: "tabular-nums", cursor: "pointer"}} className="dc-time-picker-4">
                            {txt(pr?.label)}
                          </button>
                        </>
                      ) : null}
                    </Fragment>
                  ))}
                  <button type="button" tabIndex={-1} onClick={v.done} style={{marginLeft: "auto", height: "30px", padding: "0 14px", border: "0", borderRadius: "8px", background: "#0f6e56", color: "#fff", font: "inherit", fontSize: "12.5px", fontWeight: "700", cursor: "pointer"}} className="dc-time-picker-5">
                    {"Done"}
                  </button>
                </div>
              </div>
            </UTPortal>
          </>
        ) : null}
      </div>
    </>
  )
}
