// GENERATED by scripts/dc-to-tsx.mjs from the Claude Design component WorkforceAnalytics.dc.html.
// Do not edit by hand — change the design (or the view model) and regenerate.
import { Fragment } from 'react'
import { HrButton, HrPageHeader, HrSelect, HrStatCard, HrStatusPill, TableCard } from '@/shared/components/hr'
import { DataTable } from '@/shared/components/DataTable'
import { EmptyState } from '@/shared/components/EmptyState'
import { SkeletonBlock, SkeletonRow } from '@/shared/components/SkeletonCard'
import { arr, txt } from './dc-runtime'
import './WorkforceAnalytics.view.css'

export function WorkforceAnalyticsView({ v }: { v: any }) {
  return (
    <>
      <div style={{display: "flex", flexDirection: "column", gap: "14px", fontFamily: "'Plus Jakarta Sans',sans-serif", color: "#0f172a", minWidth: "0", fontVariantNumeric: "tabular-nums"}}>
        {v.allowed ? (
          <>
            <HrPageHeader crumb="Reports & Analytics" title="Workforce Analytics" subtitle="Headcount, diversity, and attrition across your organization" actions={v.headerActions} className="!mb-0" />
          </>
        ) : null}
        {v.denied ? (
          <>
            <div style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px"}}>
              <EmptyState icon={v.lockIcon} title="Access restricted" description="You do not have the required permissions to view this page." />
            </div>
          </>
        ) : null}
        {v.allowed ? (
          <>
            <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px"}}>
              <div style={{position: "relative", flex: "0 1 250px", minWidth: "0"}}>
                {v.noCo ? (
                  <>
                    <span aria-hidden="true" style={{position: "absolute", inset: "0", borderRadius: "10px", boxShadow: "0 0 0 3px rgba(15,110,86,.25)", pointerEvents: "none", zIndex: "1"}} />
                  </>
                ) : null}
                <HrSelect value={v.company} options={v.companies} onChange={v.setCompany} placeholder="Select company…" size="sm" disabled={v.locked} />
              </div>
              <div style={{flex: "0 1 200px", minWidth: "0"}}>
                <HrSelect value={v.period} options={v.periods} onChange={v.setPeriod} size="sm" disabled={v.noCo} />
              </div>
              <span style={{fontSize: "12.5px", color: "#64748b", fontWeight: "500"}}>
                {txt(v.asOfText)}
              </span>
              {v.locked ? (
                <>
                  <span style={{display: "inline-flex", alignItems: "center", gap: "6px", fontSize: "12.5px", color: "#64748b", fontWeight: "500"}}>
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                      <path d="M5 11h14a2 2 0 0 1 2 2v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2zM7 11V7a5 5 0 0 1 10 0v4" />
                    </svg>
                    {"You can't browse companies. Ask an admin for access."}
                  </span>
                </>
              ) : null}
            </div>
          </>
        ) : null}
        {v.vNoCo ? (
          <>
            <div style={{background: "#fff", border: "1.5px dashed #cbd5e1", borderRadius: "16px"}}>
              <EmptyState icon={v.coIcon} title="Select a company" description="Choose a company from the filter above to load workforce analytics." />
            </div>
          </>
        ) : null}
        {v.vEmpty ? (
          <>
            <div style={{background: "#fff", border: "1.5px dashed #cbd5e1", borderRadius: "16px"}}>
              <EmptyState icon={v.noDataIcon} title="No data for this period" description="Try adjusting your filters or selecting a different date range." />
            </div>
          </>
        ) : null}
        {v.vError ? (
          <>
            <div role="alert" style={{background: "#fff", border: "1px solid #fecdd3", borderRadius: "16px", padding: "18px 20px", display: "flex", flexWrap: "wrap", alignItems: "center", gap: "12px 16px"}}>
              <span style={{width: "42px", height: "42px", borderRadius: "12px", background: "#fff1f2", border: "1px solid #fecdd3", color: "#e11d48", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: "0"}}>
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20zM12 8v4M12 16h.01" />
                </svg>
              </span>
              <div style={{flex: "1 1 240px", minWidth: "0"}}>
                <div style={{fontSize: "15px", fontWeight: "700"}}>
                  {"Failed to load analytics"}
                </div>
                <div style={{fontSize: "13px", color: "#64748b", marginTop: "2px", lineHeight: "1.5"}}>
                  {txt(v.errText)}
                </div>
              </div>
              <HrButton variant="ghost" onClick={v.retry}>
                {"Retry"}
              </HrButton>
            </div>
          </>
        ) : null}
        {v.vBody ? (
          <>
            <div style={{display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(150px,1fr))", gap: "12px"}}>
              {arr(v.kpis).map((k: any, $index: number) => (
                <Fragment key={$index}>
                  <HrStatCard icon={k?.icon} color={k?.color} value={k?.value} label={k?.label} sub={k?.sub} loading={k?.loading} onClick={k?.open} />
                </Fragment>
              ))}
            </div>
            <div style={{display: "flex", flexWrap: "wrap", gap: "12px", alignItems: "stretch"}}>
              {v.canHead ? (
                <>
                  <section style={{flex: "2 1 520px", minWidth: "0", background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px", boxShadow: "0 1px 2px rgba(15,23,42,.05)", padding: "16px 18px 14px", display: "flex", flexDirection: "column"}}>
                    <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px 12px", marginBottom: "14px"}}>
                      <h2 style={{margin: "0", fontSize: "15px", fontWeight: "700"}}>
                        {"Headcount by department"}
                      </h2>
                      <HrStatusPill tone="green">
                        {txt(v.deptCount)}
                      </HrStatusPill>
                      <span style={{flex: "1"}} />
                      <span style={{display: "inline-flex", alignItems: "center", gap: "6px", fontSize: "12px", color: "#334155", fontWeight: "600"}}>
                        <span style={{width: "10px", height: "10px", borderRadius: "3px", background: "#0f6e56"}} />
                        {"Active"}
                      </span>
                      <span style={{display: "inline-flex", alignItems: "center", gap: "6px", fontSize: "12px", color: "#334155", fontWeight: "600"}}>
                        <span style={{width: "10px", height: "10px", borderRadius: "3px", background: "#34d399"}} />
                        {"On notice"}
                      </span>
                      <span style={{display: "inline-flex", alignItems: "center", gap: "6px", fontSize: "12px", color: "#334155", fontWeight: "600"}}>
                        <span style={{width: "10px", height: "10px", borderRadius: "3px", background: "#a7f3d0"}} />
                        {"Probation"}
                      </span>
                      {v.ready ? (
                        <>
                          <button type="button" onClick={v.dlHead} title="Download chart as PNG" aria-label="Download chart as PNG" style={{width: "30px", height: "30px", borderRadius: "8px", border: "1px solid #e2e8f0", background: "#fff", color: "#475569", display: "inline-flex", alignItems: "center", justifyContent: "center", cursor: "pointer"}} className="dc-workforce-analytics-0">
                            <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3" />
                            </svg>
                          </button>
                        </>
                      ) : null}
                    </div>
                    {v.vLoading ? (
                      <>
                        <div style={{height: "236px", display: "flex", alignItems: "flex-end", justifyContent: "space-around", gap: "16px", padding: "0 12px 0 40px", borderBottom: "1px solid #f1f5f9"}}>
                          {arr(v.skelBars).map((c: any, $index: number) => (
                            <Fragment key={$index}>
                              <SkeletonBlock className={c} />
                            </Fragment>
                          ))}
                        </div>
                      </>
                    ) : null}
                    {v.ready ? (
                      <>
                        <div style={{overflowX: "auto", paddingTop: "4px"}}>
                          <div style={{minWidth: "480px"}}>
                            <div style={{position: "relative", height: "216px", marginLeft: "34px"}} onMouseLeave={v.clearHi}>
                              <div style={{position: "absolute", left: "0", right: "0", bottom: "0%", height: "0", borderTop: "1px solid #e2e8f0"}}>
                                <span style={{position: "absolute", right: "calc(100% + 8px)", top: "-8px", fontSize: "11px", color: "#94a3b8", fontWeight: "600"}}>
                                  {"0"}
                                </span>
                              </div>
                              <div style={{position: "absolute", left: "0", right: "0", bottom: "25%", height: "0", borderTop: "1px dashed #e2e8f0"}}>
                                <span style={{position: "absolute", right: "calc(100% + 8px)", top: "-8px", fontSize: "11px", color: "#94a3b8", fontWeight: "600"}}>
                                  {txt(v.tk?.t1)}
                                </span>
                              </div>
                              <div style={{position: "absolute", left: "0", right: "0", bottom: "50%", height: "0", borderTop: "1px dashed #e2e8f0"}}>
                                <span style={{position: "absolute", right: "calc(100% + 8px)", top: "-8px", fontSize: "11px", color: "#94a3b8", fontWeight: "600"}}>
                                  {txt(v.tk?.t2)}
                                </span>
                              </div>
                              <div style={{position: "absolute", left: "0", right: "0", bottom: "75%", height: "0", borderTop: "1px dashed #e2e8f0"}}>
                                <span style={{position: "absolute", right: "calc(100% + 8px)", top: "-8px", fontSize: "11px", color: "#94a3b8", fontWeight: "600"}}>
                                  {txt(v.tk?.t3)}
                                </span>
                              </div>
                              <div style={{position: "absolute", left: "0", right: "0", bottom: "100%", height: "0", borderTop: "1px dashed #e2e8f0"}}>
                                <span style={{position: "absolute", right: "calc(100% + 8px)", top: "-8px", fontSize: "11px", color: "#94a3b8", fontWeight: "600"}}>
                                  {txt(v.tk?.t4)}
                                </span>
                              </div>
                              <div style={{position: "absolute", inset: "0", display: "flex", alignItems: "stretch"}}>
                                {arr(v.bars).map((b: any, $index: number) => (
                                  <Fragment key={$index}>
                                    <div onMouseEnter={b?.enter} onClick={b?.open} title={b?.hint} style={{flex: "1", minWidth: "0", position: "relative", display: "flex", flexDirection: "column", justifyContent: "flex-end", alignItems: "center", borderRadius: "10px 10px 0 0", cursor: "pointer", transition: "background .15s"}} className="dc-workforce-analytics-1">
                                      <span style={{fontSize: "11.5px", fontWeight: "700", color: "#334155", marginBottom: "5px"}}>
                                        {txt(b?.top)}
                                      </span>
                                      <svg width="44" height={b?.H} aria-hidden="true" style={{display: "block", overflow: "visible", flexShrink: "0"}}>
                                        <rect x="0" y={b?.ya} width="44" height={b?.ha} rx="4" fill="#0f6e56" />
                                        <rect x="0" y={b?.yn} width="44" height={b?.hn} rx="2" fill="#34d399" />
                                        <rect x="0" y={b?.yp} width="44" height={b?.hp} rx="2" fill="#a7f3d0" />
                                      </svg>
                                      {b?.hot ? (
                                        <>
                                          <div role="tooltip" style={{position: "absolute", zIndex: "5", top: "4px", left: "50%", transform: "translateX(-50%)", width: "164px", background: "#0f172a", color: "#fff", borderRadius: "12px", padding: "10px 12px", boxShadow: "0 16px 40px -12px rgba(15,23,42,.5)", pointerEvents: "none", textAlign: "left"}}>
                                            <div style={{fontSize: "13px", fontWeight: "700"}}>
                                              {txt(b?.label)}
                                            </div>
                                            <div style={{fontSize: "11.5px", color: "#a7f3d0", marginBottom: "6px"}}>
                                              {txt(b?.tipSub)}
                                            </div>
                                            <div style={{display: "flex", alignItems: "center", gap: "7px", fontSize: "12px", padding: "2px 0"}}>
                                              <span style={{width: "9px", height: "9px", borderRadius: "3px", background: "#0f6e56"}} />
                                              <span style={{flex: "1", color: "#cbd5e1"}}>
                                                {"Active"}
                                              </span>
                                              <b>
                                                {txt(b?.va)}
                                              </b>
                                            </div>
                                            <div style={{display: "flex", alignItems: "center", gap: "7px", fontSize: "12px", padding: "2px 0"}}>
                                              <span style={{width: "9px", height: "9px", borderRadius: "3px", background: "#34d399"}} />
                                              <span style={{flex: "1", color: "#cbd5e1"}}>
                                                {"On notice"}
                                              </span>
                                              <b>
                                                {txt(b?.vb)}
                                              </b>
                                            </div>
                                            <div style={{display: "flex", alignItems: "center", gap: "7px", fontSize: "12px", padding: "2px 0"}}>
                                              <span style={{width: "9px", height: "9px", borderRadius: "3px", background: "#a7f3d0"}} />
                                              <span style={{flex: "1", color: "#cbd5e1"}}>
                                                {"Probation"}
                                              </span>
                                              <b>
                                                {txt(b?.vc)}
                                              </b>
                                            </div>
                                            <div style={{fontSize: "11px", color: "#94a3b8", marginTop: "6px"}}>
                                              {"Click to open in directory"}
                                            </div>
                                          </div>
                                        </>
                                      ) : null}
                                    </div>
                                  </Fragment>
                                ))}
                              </div>
                            </div>
                            <div style={{display: "flex", marginLeft: "34px", paddingTop: "8px", borderTop: "1px solid #e2e8f0"}}>
                              {arr(v.bars).map((b: any, $index: number) => (
                                <Fragment key={$index}>
                                  <div style={{flex: "1", minWidth: "0", textAlign: "center", fontSize: "12px", fontWeight: "600", color: "#334155", padding: "0 2px", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}}>
                                    {b?.named ? (
                                      <>
                                        {txt(b?.label)}
                                      </>
                                    ) : null}
                                    {b?.none ? (
                                      <>
                                        <span style={{fontStyle: "italic", color: "#64748b"}}>
                                          {txt(b?.label)}
                                        </span>
                                      </>
                                    ) : null}
                                  </div>
                                </Fragment>
                              ))}
                            </div>
                          </div>
                        </div>
                      </>
                    ) : null}
                    <div style={{display: "flex", justifyContent: "flex-end", marginTop: "auto", paddingTop: "10px"}}>
                      <button type="button" onClick={v.openHeadcount} style={{border: "0", background: "transparent", padding: "4px 2px", font: "700 12.5px 'Plus Jakarta Sans',sans-serif", color: "#0f6e56", cursor: "pointer", display: "inline-flex", alignItems: "center", gap: "4px"}} className="dc-workforce-analytics-2">
                        {"Open Headcount Report"}
                        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">
                          <path d="M5 12h14M12 5l7 7-7 7" />
                        </svg>
                      </button>
                    </div>
                  </section>
                </>
              ) : null}
              {v.canDiv ? (
                <>
                  <section style={{flex: "1 1 300px", minWidth: "0", background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px", boxShadow: "0 1px 2px rgba(15,23,42,.05)", padding: "16px 18px 14px", display: "flex", flexDirection: "column"}}>
                    <div style={{display: "flex", alignItems: "center", gap: "8px", marginBottom: "10px"}}>
                      <h2 style={{margin: "0", fontSize: "15px", fontWeight: "700", flex: "1"}}>
                        {"Gender diversity"}
                      </h2>
                      <HrStatusPill tone="purple">
                        {txt(v.peopleCount)}
                      </HrStatusPill>
                    </div>
                    {v.vLoading ? (
                      <>
                        <div style={{display: "flex", justifyContent: "center", padding: "20px 0"}}>
                          <SkeletonBlock className="h-40 w-40 rounded-full" />
                        </div>
                      </>
                    ) : null}
                    {v.ready ? (
                      <>
                        <div style={{display: "flex", flexDirection: "column", alignItems: "center", gap: "14px", flex: "1"}} onMouseLeave={v.clearSeg}>
                          <div style={{position: "relative", width: "180px", height: "180px"}}>
                            <svg width="180" height="180" viewBox="0 0 180 180" aria-label="Gender split" role="img" style={{display: "block", transform: "rotate(-90deg)"}}>
                              <circle cx="90" cy="90" r="70" fill="none" stroke="#f1f5f9" stroke-width="22" />
                              {arr(v.segs).map((g: any, $index: number) => (
                                <Fragment key={$index}>
                                  <circle cx="90" cy="90" r="70" fill="none" stroke={g?.c} stroke-width={g?.sw} stroke-dasharray={g?.da} stroke-dashoffset={g?.off} onMouseEnter={g?.enter} style={{cursor: "pointer", transition: "stroke-width .15s"}} />
                                </Fragment>
                              ))}
                            </svg>
                            <div style={{position: "absolute", inset: "0", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", pointerEvents: "none"}}>
                              <div style={{fontSize: "26px", fontWeight: "800"}}>
                                {txt(v.center?.v)}
                              </div>
                              <div style={{fontSize: "11px", fontWeight: "700", letterSpacing: ".06em", color: "#64748b", textTransform: "uppercase"}}>
                                {txt(v.center?.l)}
                              </div>
                            </div>
                          </div>
                          <div style={{width: "100%", display: "flex", flexDirection: "column", gap: "2px"}}>
                            {arr(v.segs).map((g: any, $index: number) => (
                              <Fragment key={$index}>
                                <div onMouseEnter={g?.enter} style={{display: "flex", alignItems: "center", gap: "8px", padding: "7px 9px", borderRadius: "9px", fontSize: "13px", cursor: "default"}} className="dc-workforce-analytics-3">
                                  {g?.i0 ? (
                                    <>
                                      <span style={{width: "10px", height: "10px", borderRadius: "3px", background: "#0f6e56", flexShrink: "0"}} />
                                    </>
                                  ) : null}
                                  {g?.i1 ? (
                                    <>
                                      <span style={{width: "10px", height: "10px", borderRadius: "3px", background: "#34d399", flexShrink: "0"}} />
                                    </>
                                  ) : null}
                                  {g?.i2 ? (
                                    <>
                                      <span style={{width: "10px", height: "10px", borderRadius: "3px", background: "#a7f3d0", flexShrink: "0"}} />
                                    </>
                                  ) : null}
                                  <span style={{flex: "1", color: "#334155", fontWeight: "600"}}>
                                    {txt(g?.label)}
                                  </span>
                                  <b>
                                    {txt(g?.count)}
                                  </b>
                                  <span style={{width: "40px", textAlign: "right", color: "#64748b", fontWeight: "600"}}>
                                    {txt(g?.pct)}
                                  </span>
                                </div>
                              </Fragment>
                            ))}
                          </div>
                          <div style={{width: "100%", padding: "9px 11px", borderRadius: "10px", background: "#f8fafc", border: "1px solid #f1f5f9", fontSize: "12.5px", color: "#475569", fontWeight: "500", boxSizing: "border-box"}}>
                            {"Most balanced: "}
                            <b style={{color: "#0f172a"}}>
                              {txt(v.balanced)}
                            </b>
                          </div>
                        </div>
                      </>
                    ) : null}
                    <div style={{display: "flex", justifyContent: "flex-end", marginTop: "auto", paddingTop: "10px"}}>
                      <button type="button" onClick={v.openDiversity} style={{border: "0", background: "transparent", padding: "4px 2px", font: "700 12.5px 'Plus Jakarta Sans',sans-serif", color: "#0f6e56", cursor: "pointer", display: "inline-flex", alignItems: "center", gap: "4px"}} className="dc-workforce-analytics-2">
                        {"Open Diversity Report"}
                        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">
                          <path d="M5 12h14M12 5l7 7-7 7" />
                        </svg>
                      </button>
                    </div>
                  </section>
                </>
              ) : null}
            </div>
            {v.canAttr ? (
              <>
                <section style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px", boxShadow: "0 1px 2px rgba(15,23,42,.05)", padding: "16px 18px 14px", minWidth: "0"}}>
                  <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px 12px", marginBottom: "12px"}}>
                    <h2 style={{margin: "0", fontSize: "15px", fontWeight: "700"}}>
                      {"Monthly attrition"}
                    </h2>
                    <span style={{fontSize: "12.5px", color: "#64748b", fontWeight: "500"}}>
                      {txt(v.periodText)}
                    </span>
                    <span style={{flex: "1"}} />
                    <span style={{display: "inline-flex", alignItems: "center", gap: "6px", fontSize: "12px", color: "#334155", fontWeight: "600"}}>
                      <span style={{width: "14px", height: "3px", borderRadius: "2px", background: "#0f6e56"}} />
                      {"Attrition %"}
                    </span>
                    {v.ready ? (
                      <>
                        <button type="button" onClick={v.dlAttr} title="Download chart as PNG" aria-label="Download chart as PNG" style={{width: "30px", height: "30px", borderRadius: "8px", border: "1px solid #e2e8f0", background: "#fff", color: "#475569", display: "inline-flex", alignItems: "center", justifyContent: "center", cursor: "pointer"}} className="dc-workforce-analytics-0">
                          <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3" />
                          </svg>
                        </button>
                      </>
                    ) : null}
                  </div>
                  {v.vLoading ? (
                    <>
                      <SkeletonBlock className="h-48 w-full rounded-lg" />
                    </>
                  ) : null}
                  {v.ready ? (
                    <>
                      <div style={{display: "flex", flexWrap: "wrap", alignItems: "center", gap: "6px 18px", padding: "10px 12px", borderRadius: "12px", background: "#f0fdf4", border: "1px solid #d1fae5", marginBottom: "12px"}}>
                        <span style={{fontSize: "13.5px", fontWeight: "800", color: "#0a5240"}}>
                          {txt(v.ro?.label)}
                        </span>
                        <span style={{fontSize: "13px", color: "#334155"}}>
                          <b style={{color: "#0f172a"}}>
                            {txt(v.ro?.pct)}
                          </b>
                          {" attrition"}
                        </span>
                        <span style={{fontSize: "13px", color: "#334155"}}>
                          <b style={{color: "#0f172a"}}>
                            {txt(v.ro?.exits)}
                          </b>
                          {" exits · "}{txt(v.ro?.split)}
                        </span>
                        <span style={{fontSize: "13px", color: "#334155"}}>
                          {"Headcount "}
                          <b style={{color: "#0f172a"}}>
                            {txt(v.ro?.hc)}
                          </b>
                        </span>
                      </div>
                      <div style={{overflowX: "auto", paddingTop: "10px"}}>
                        <div style={{minWidth: "560px"}}>
                          <div style={{position: "relative", marginLeft: "38px"}} onMouseLeave={v.clearMonth}>
                            <div style={{position: "absolute", left: "0", right: "0", top: "0", bottom: "0", pointerEvents: "none"}}>
                              <div style={{position: "absolute", left: "0", right: "0", bottom: "0%", borderTop: "1px solid #e2e8f0"}}>
                                <span style={{position: "absolute", right: "calc(100% + 8px)", top: "-8px", fontSize: "11px", color: "#94a3b8", fontWeight: "600"}}>
                                  {"0%"}
                                </span>
                              </div>
                              <div style={{position: "absolute", left: "0", right: "0", bottom: "33.333%", borderTop: "1px dashed #e2e8f0"}}>
                                <span style={{position: "absolute", right: "calc(100% + 8px)", top: "-8px", fontSize: "11px", color: "#94a3b8", fontWeight: "600"}}>
                                  {txt(v.ay?.a1)}
                                </span>
                              </div>
                              <div style={{position: "absolute", left: "0", right: "0", bottom: "66.667%", borderTop: "1px dashed #e2e8f0"}}>
                                <span style={{position: "absolute", right: "calc(100% + 8px)", top: "-8px", fontSize: "11px", color: "#94a3b8", fontWeight: "600"}}>
                                  {txt(v.ay?.a2)}
                                </span>
                              </div>
                              <div style={{position: "absolute", left: "0", right: "0", bottom: "100%", borderTop: "1px dashed #e2e8f0"}}>
                                <span style={{position: "absolute", right: "calc(100% + 8px)", top: "-8px", fontSize: "11px", color: "#94a3b8", fontWeight: "600"}}>
                                  {txt(v.ay?.a3)}
                                </span>
                              </div>
                            </div>
                            <svg viewBox={v.vb} width="100%" aria-label="Monthly attrition" role="img" style={{display: "block", height: "auto", overflow: "visible"}}>
                              <defs>
                                <linearGradient id="waArea" x1="0" y1="0" x2="0" y2="1">
                                  <stop offset="0" stop-color="#34d399" stop-opacity=".35" />
                                  <stop offset="1" stop-color="#34d399" stop-opacity="0" />
                                </linearGradient>
                              </defs>
                              {arr(v.months).map((m: any, $index: number) => (
                                <Fragment key={$index}>
                                  <rect x={m?.x0} y="0" width="100" height="220" fill={m?.band} onMouseEnter={m?.enter} onClick={m?.enter} style={{cursor: "pointer"}} />
                                </Fragment>
                              ))}
                              <path d={v.areaD} fill="url(#waArea)" pointer-events="none" />
                              <path d={v.lineD} fill="none" stroke="#0f6e56" stroke-width="3" stroke-linejoin="round" stroke-linecap="round" pointer-events="none" />
                              {arr(v.months).map((m: any, $index: number) => (
                                <Fragment key={$index}>
                                  <circle cx={m?.cx} cy={m?.cy} r={m?.r} fill="#fff" stroke="#0f6e56" stroke-width="3" pointer-events="none" />
                                </Fragment>
                              ))}
                            </svg>
                          </div>
                          <div style={{display: "flex", marginLeft: "38px", paddingTop: "8px", borderTop: "1px solid #e2e8f0"}}>
                            {arr(v.months).map((m: any, $index: number) => (
                              <Fragment key={$index}>
                                <div style={{flex: "1", minWidth: "0", textAlign: "center", fontSize: "11.5px", fontWeight: "600", color: "#64748b", whiteSpace: "nowrap"}}>
                                  {txt(m?.short)}
                                </div>
                              </Fragment>
                            ))}
                          </div>
                        </div>
                      </div>
                    </>
                  ) : null}
                  <div style={{display: "flex", justifyContent: "flex-end", paddingTop: "10px"}}>
                    <button type="button" onClick={v.openAttrition} style={{border: "0", background: "transparent", padding: "4px 2px", font: "700 12.5px 'Plus Jakarta Sans',sans-serif", color: "#0f6e56", cursor: "pointer", display: "inline-flex", alignItems: "center", gap: "4px"}} className="dc-workforce-analytics-2">
                      {"Open Attrition Report"}
                      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">
                        <path d="M5 12h14M12 5l7 7-7 7" />
                      </svg>
                    </button>
                  </div>
                </section>
              </>
            ) : null}
            {v.vLoading ? (
              <>
                <div style={{background: "#fff", border: "1px solid #e2e8f0", borderRadius: "16px", padding: "8px 20px"}}>
                  {arr(v.skelRows).map((x: any, $index: number) => (
                    <Fragment key={$index}>
                      <SkeletonRow />
                    </Fragment>
                  ))}
                </div>
              </>
            ) : null}
            {v.tableDesk ? (
              <>
                <TableCard filters={v.tTitle}>
                  <DataTable columns={v.cols} data={v.tRows} keyField="id" onRowClick={v.openDept} footer={v.tfoot} />
                </TableCard>
              </>
            ) : null}
            {v.tableMob ? (
              <>
                <TableCard filters={v.tTitle}>
                  <div style={{display: "flex", flexDirection: "column", gap: "8px", padding: "12px", background: "#f8fafc"}}>
                    {arr(v.mRows).map((r: any, $index: number) => (
                      <Fragment key={$index}>
                        <button type="button" onClick={r?.open} style={{textAlign: "left", width: "100%", background: "#fff", border: "1px solid #e2e8f0", borderRadius: "14px", padding: "12px 14px", display: "flex", flexDirection: "column", gap: "10px", cursor: "pointer", fontFamily: "inherit", color: "inherit", boxSizing: "border-box"}}>
                          <span style={{display: "flex", alignItems: "center", gap: "8px"}}>
                            {r?.named ? (
                              <>
                                <span style={{flex: "1", minWidth: "0", fontSize: "14px", fontWeight: "700", color: "#0f6e56"}}>
                                  {txt(r?.dept)}
                                </span>
                              </>
                            ) : null}
                            {r?.none ? (
                              <>
                                <span style={{flex: "1", minWidth: "0", fontSize: "14px", fontWeight: "700", fontStyle: "italic", color: "#64748b"}}>
                                  {txt(r?.dept)}
                                </span>
                              </>
                            ) : null}
                            <span style={{fontSize: "18px", fontWeight: "800"}}>
                              {txt(r?.total)}
                            </span>
                            <span style={{fontSize: "12px", fontWeight: "600", color: "#64748b"}}>
                              {txt(r?.share)}
                            </span>
                          </span>
                          <span style={{display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: "6px"}}>
                            <span style={{background: "#f8fafc", borderRadius: "9px", padding: "6px 8px", display: "flex", flexDirection: "column"}}>
                              <span style={{fontSize: "11px", color: "#64748b", fontWeight: "600"}}>
                                {"Active"}
                              </span>
                              <b style={{fontSize: "13.5px"}}>
                                {txt(r?.active)}
                              </b>
                            </span>
                            <span style={{background: "#f8fafc", borderRadius: "9px", padding: "6px 8px", display: "flex", flexDirection: "column"}}>
                              <span style={{fontSize: "11px", color: "#64748b", fontWeight: "600"}}>
                                {"Notice · Prob."}
                              </span>
                              <b style={{fontSize: "13.5px"}}>
                                {txt(r?.np)}
                              </b>
                            </span>
                            <span style={{background: "#f8fafc", borderRadius: "9px", padding: "6px 8px", display: "flex", flexDirection: "column"}}>
                              <span style={{fontSize: "11px", color: "#64748b", fontWeight: "600"}}>
                                {"Women"}
                              </span>
                              <b style={{fontSize: "13.5px"}}>
                                {txt(r?.women)}
                              </b>
                            </span>
                          </span>
                        </button>
                      </Fragment>
                    ))}
                  </div>
                </TableCard>
              </>
            ) : null}
          </>
        ) : null}
        {v.toastOn ? (
          <>
            <div role="status" style={{position: "fixed", left: "50%", bottom: "24px", transform: "translateX(-50%)", zIndex: "90", display: "flex", alignItems: "center", gap: "10px", width: "max-content", maxWidth: "calc(100% - 32px)", padding: "11px 16px", borderRadius: "12px", background: "#0f172a", color: "#fff", fontSize: "13.5px", fontWeight: "600", boxShadow: "0 18px 40px -14px rgba(15,23,42,.5)", boxSizing: "border-box"}}>
              <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="#6ee7b7" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" style={{flexShrink: "0"}}>
                <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14M22 4 12 14.01l-3-3" />
              </svg>
              {txt(v.toastMsg)}
            </div>
          </>
        ) : null}
        {v.toastErr ? (
          <>
            <div role="alert" style={{position: "fixed", left: "50%", bottom: "24px", transform: "translateX(-50%)", zIndex: "90", display: "flex", alignItems: "center", gap: "10px", width: "max-content", maxWidth: "calc(100% - 32px)", padding: "11px 16px", borderRadius: "12px", background: "#be123c", color: "#fff", fontSize: "13.5px", fontWeight: "600", boxShadow: "0 18px 40px -14px rgba(15,23,42,.5)", boxSizing: "border-box"}}>
              {txt(v.toastMsg)}
            </div>
          </>
        ) : null}
      </div>
    </>
  )
}
